#!/usr/bin/env python3
"""
vlm2.py  —  Ameca HRI dialogue prototype
Extended with Adaptive Reliability-Aware Late Fusion (ARALF)

Fusion pipeline per conversational turn:
  Linguistic  →  LLM emotion probs  +  r_L  (ASR word confidence × length × speech prob)
  Acoustic    →  Prosody probs       +  r_A  (RMS energy × voiced ratio)
  Visual      →  Qwen2.5-VL probs    +  r_V  (face detect conf × FER conf × face area)
  ─────────────────────────────────────────────────────────────────────────────────────
  P_fused(e) = Σ_m  w_m · P_m(e)  /  Σ_m w_m   where  w_m = r_m  (gated at θ=0.30)
"""
from __future__ import annotations

import base64
import json
import os
import queue
import re
import sys
import tempfile
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Tuple

if sys.platform.startswith("linux"):
    os.environ["QT_QPA_PLATFORM"] = "xcb"

os.environ["OPENCV_VIDEOIO_PRIORITY_MSMF"] = "0"

import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf
import torch
from faster_whisper import WhisperModel
from ollama import Client
from silero_vad import load_silero_vad, VADIterator
import platform

# ── Optional librosa import (acoustic modality) ────────────────────────────
try:
    import librosa
    LIBROSA_AVAILABLE = True
except ImportError:
    LIBROSA_AVAILABLE = False
    print("[WARN] librosa not installed. Acoustic modality will be disabled.")
    print("       Install with: pip install librosa")

IS_MAC   = platform.system() == "Darwin"
IS_LINUX = platform.system() == "Linux"

CAMERA_DEVICE        = 0 if IS_MAC else 1
USE_ZED_HALF_FRAME_CROP = IS_LINUX

# ══════════════════════════════════════════════════════════════════════════════
# Local Ollama configuration
# ══════════════════════════════════════════════════════════════════════════════

OLLAMA_HOST        = "http://127.0.0.1:11434"
MODEL_NAME         = "llama3:8b"
VISION_MODEL_NAME  = "llama3.2-vision:11b"

# ══════════════════════════════════════════════════════════════════════════════
# Adaptive Reliability-Aware Late Fusion configuration
# ══════════════════════════════════════════════════════════════════════════════

# Modalities whose reliability score falls below this threshold are gated out.
FUSION_GATE_THRESHOLD = 0.30

# Fixed fallback weights used ONLY for logging / comparison experiments.
# The live system always uses dynamic reliability weights.
FUSION_FALLBACK_WEIGHTS = {"linguistic": 0.50, "acoustic": 0.25, "visual": 0.25}

# Acoustic reliability: reference RMS level for comfortable conversational speech.
ACOUSTIC_REF_RMS = 0.08

# Linguistic reliability: minimum number of words for full length credit.
LINGUISTIC_MIN_WORDS_FOR_FULL_CREDIT = 5

# ══════════════════════════════════════════════════════════════════════════════
# Persistent memory / transcript configuration
# ══════════════════════════════════════════════════════════════════════════════

DATA_DIR    = "conversation_data"
USERS_FILE  = os.path.join(DATA_DIR, "users.json")
SESSIONS_DIR = os.path.join(DATA_DIR, "sessions")
ENABLE_LLM_SESSION_SUMMARY = False

# ══════════════════════════════════════════════════════════════════════════════
# Ameca identity prompt
# ══════════════════════════════════════════════════════════════════════════════

AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information.
Treat the conversation as ephemeral in speech, but save the local JSON transcript when the session ends.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""

# ══════════════════════════════════════════════════════════════════════════════
# faster-whisper configuration
# ══════════════════════════════════════════════════════════════════════════════

FAST_WHISPER_CONFIG = {
    "profile": "home_macbook_cpu",
    "model": "large-v3",
    "device": "cuda",
    "compute_type": "float16",
    "language": "en",
    "beam_size": 1,
    "vad_filter": False,
}

# ══════════════════════════════════════════════════════════════════════════════
# Audio / Silero VAD configuration
# ══════════════════════════════════════════════════════════════════════════════

TARGET_SAMPLE_RATE          = 16000
INPUT_DEVICE: Optional[int] = None
SILERO_SAMPLE_RATE          = 16000
SILERO_CHUNK_SIZE           = 512
SILERO_THRESHOLD            = 0.55
SILERO_MIN_SILENCE_DURATION_MS = 700
SILERO_SPEECH_PAD_MS        = 250
VAD_MAX_UTTERANCE_SECONDS   = 15.0
VAD_MIN_UTTERANCE_SECONDS   = 0.60
VAD_PRE_ROLL_SECONDS        = 0.35
MIN_PEAK_THRESHOLD          = 0.01
MIN_RMS_THRESHOLD           = 0.003

# ══════════════════════════════════════════════════════════════════════════════
# Camera / Qwen2.5-VL configuration
# ══════════════════════════════════════════════════════════════════════════════

CAMERA_DEVICE: Optional[int] = 0

ZED_STEREO_WIDTH    = 2560
ZED_STEREO_HEIGHT   = 720
CAMERA_FRAME_WIDTH  = ZED_STEREO_WIDTH  if IS_LINUX else 1280
CAMERA_FRAME_HEIGHT = ZED_STEREO_HEIGHT if IS_LINUX else 720
CAMERA_PREVIEW_WIDTH  = 960
CAMERA_PREVIEW_HEIGHT = 540
CAMERA_PREVIEW_ENABLED     = True
CAMERA_PREVIEW_WINDOW_NAME = "Camera Preview - press q to close preview"
CAMERA_SAMPLE_EVERY_SECONDS = float(os.environ.get("CAMERA_SAMPLE_EVERY_SECONDS", "999.0"))
CAMERA_WARMUP_SECONDS       = float(os.environ.get("CAMERA_WARMUP_SECONDS", "0.35"))

VISION_JPEG_QUALITY         = int(os.environ.get("VISION_JPEG_QUALITY", "80"))
VISION_MODEL_TIMEOUT_SECONDS = int(os.environ.get("VISION_MODEL_TIMEOUT_SECONDS", "20"))
VISION_DEBUG                = os.environ.get("VISION_DEBUG", "1") == "1"
VISION_DEBUG_DIR            = os.environ.get("VISION_DEBUG_DIR", "vision_debug_frames")
VISION_MAX_IMAGE_SIDE       = int(os.environ.get("VISION_MAX_IMAGE_SIDE", "640"))
VISION_DENOISE_ENABLED      = os.environ.get("VISION_DENOISE_ENABLED", "1") == "1"
VISION_LIGHTING_ENHANCE_ENABLED = os.environ.get("VISION_LIGHTING_ENHANCE_ENABLED", "1") == "1"
VISION_SHARPEN_ENABLED      = os.environ.get("VISION_SHARPEN_ENABLED", "1") == "1"
VISION_DENOISE_H            = float(os.environ.get("VISION_DENOISE_H", "5"))
VISION_DENOISE_H_COLOR      = float(os.environ.get("VISION_DENOISE_H_COLOR", "5"))
VISION_CLAHE_CLIP_LIMIT     = float(os.environ.get("VISION_CLAHE_CLIP_LIMIT", "2.0"))
VISION_MIN_BRIGHTNESS       = float(os.environ.get("VISION_MIN_BRIGHTNESS", "35.0"))
VISION_MAX_BRIGHTNESS       = float(os.environ.get("VISION_MAX_BRIGHTNESS", "220.0"))
VISION_MIN_SHARPNESS        = float(os.environ.get("VISION_MIN_SHARPNESS", "20.0"))
FACE_MIN_TOP_SCORE          = float(os.environ.get("FACE_MIN_TOP_SCORE", "35.0"))
FACE_MIN_MARGIN             = float(os.environ.get("FACE_MIN_MARGIN", "8.0"))

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy":          "😊",
    "trust":        "🙂",
    "fear":         "😨",
    "surprise":     "😮",
    "sadness":      "😢",
    "disgust":      "🤢",
    "anger":        "😠",
    "anticipation": "🤔",
}
ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())


# ══════════════════════════════════════════════════════════════════════════════
# Dataclasses
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class EmotionResult:
    """Backward-compatible single-label emotion result for response generation."""
    emotion:    str
    confidence: float
    reason:     str


@dataclass
class TranscriptionResult:
    """ASR output with quality signals for linguistic reliability scoring."""
    text:             str
    word_confidences: list[float]   # per-word probability from faster-whisper
    no_speech_prob:   float         # mean segment-level no-speech probability
    avg_logprob:      float = -1.0  # mean segment-level log-probability


@dataclass
class ProsodyFeatures:
    """Acoustic feature vector extracted by librosa."""
    f0_mean:          float   # mean voiced fundamental frequency (Hz)
    f0_std:           float   # F0 variability (indicates emotional arousal)
    rms_energy:       float   # mean RMS energy (speech loudness)
    speaking_rate:    float   # onset events per second (syllable proxy)
    zcr_mean:         float   # zero-crossing rate
    voiced_ratio:     float   # proportion of voiced frames in the utterance
    duration_seconds: float


@dataclass
class ModalityEmotionResult:
    """
    Per-modality output for the fusion module.
    probs: probability distribution over Plutchik's 8 emotions (sums to 1.0).
    reliability: scalar in [0, 1] computed from observable quality signals.
    """
    probs:       dict[str, float]
    reliability: float
    modality:    str   # "linguistic" | "acoustic" | "visual"


@dataclass
class FusedEmotionResult:
    """
    Output of the adaptive reliability-aware late fusion module.
    Wraps both the final label and the full internal state for logging.
    """
    emotion:     str
    confidence:  float
    probs:       dict[str, float]
    weights:     dict[str, float]   # effective normalised weights: L, A, V
    raw_weights: dict[str, float]   # raw reliability scores before normalisation
    reason:      str
    linguistic:  Optional[ModalityEmotionResult]
    acoustic:    Optional[ModalityEmotionResult]
    visual:      Optional[ModalityEmotionResult]


@dataclass
class FaceEmotionCapture:
    emotion_score_samples: list[dict[str, float]]
    frame_count:           int
    sampled_frame_count:   int
    started_at:            str
    ended_at:              str
    error:                 Optional[str] = None

    @property
    def averaged_scores(self) -> dict[str, float]:
        if not self.emotion_score_samples:
            return {}
        totals: dict[str, float] = {}
        for sample in self.emotion_score_samples:
            for emotion, score in sample.items():
                totals[emotion] = totals.get(emotion, 0.0) + score
        count = len(self.emotion_score_samples)
        return {emotion: total / count for emotion, total in totals.items()}

    @property
    def dominant_emotion(self) -> Optional[str]:
        scores = self.averaged_scores
        if not scores:
            return None
        return max(scores.items(), key=lambda item: item[1])[0]

    @property
    def is_reliable(self) -> bool:
        scores = self.averaged_scores
        if not scores:
            return False
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        top_score   = ordered[0][1]
        second_score = ordered[1][1] if len(ordered) > 1 else 0.0
        return top_score >= FACE_MIN_TOP_SCORE and (top_score - second_score) >= FACE_MIN_MARGIN

    @property
    def summary_text(self) -> str:
        if self.error:
            return f"No facial-expression hint available because: {self.error}"
        scores = self.averaged_scores
        if not scores:
            return "No reliable facial-expression hint was captured during speech."
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        if not self.is_reliable:
            top_parts = [f"{emo}={score:.0f}%" for emo, score in ordered[:3]]
            return (
                "Facial-expression hint was weak or mixed; "
                f"top_signals=({', '.join(top_parts)}); "
                f"samples={self.sampled_frame_count}"
            )
        parts = [f"{emo}={score:.0f}%" for emo, score in ordered if score >= 5.0]
        return (
            f"dominant={self.dominant_emotion}; "
            f"averaged_scores=({', '.join(parts)}); "
            f"samples={self.sampled_frame_count}"
        )

    @property
    def as_json(self) -> dict:
        scores = self.averaged_scores
        return {
            "available":       self.error is None and bool(scores),
            "reliable":        self.is_reliable,
            "dominant_emotion": self.dominant_emotion,
            "averaged_scores": scores,
            "frame_count":     self.frame_count,
            "sampled_frame_count": self.sampled_frame_count,
            "started_at":      self.started_at,
            "ended_at":        self.ended_at,
            "error":           self.error,
            "note": (
                "Qwen2.5-VL facial expression analysis is a weak supporting signal. "
                "Fusion weights are computed dynamically from reliability scores."
            ),
        }


# ══════════════════════════════════════════════════════════════════════════════
# Timestamp helpers
# ══════════════════════════════════════════════════════════════════════════════

def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")

def normalize_command(text: str) -> Optional[str]:
    stripped = text.strip().lower()
    if not stripped.startswith(("/", "\\")):
        return None
    return re.sub(r"^[\\/]+", "", stripped)

def default_face_emotion_json() -> dict:
    return {
        "available": False, "reliable": False,
        "dominant_emotion": None, "averaged_scores": {},
        "frame_count": 0, "sampled_frame_count": 0,
        "started_at": None, "ended_at": None,
        "error": "No face emotion capture was provided.",
    }


# ══════════════════════════════════════════════════════════════════════════════
# Persistent memory helpers  (unchanged from original)
# ══════════════════════════════════════════════════════════════════════════════

def ensure_data_dirs() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(SESSIONS_DIR, exist_ok=True)

def slugify_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    return name.strip("_") or "unknown_user"

def load_users() -> dict:
    ensure_data_dirs()
    if not os.path.exists(USERS_FILE):
        return {}
    try:
        with open(USERS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {}

def save_users(users: dict) -> None:
    ensure_data_dirs()
    with open(USERS_FILE, "w", encoding="utf-8") as f:
        json.dump(users, f, indent=2, ensure_ascii=False)

def clean_spoken_name(spoken_name: str) -> str:
    spoken_name = spoken_name.strip()
    for pattern in [
        r"^my name is\s+", r"^my name's\s+", r"^i am\s+",
        r"^i'm\s+", r"^this is\s+", r"^it is\s+",
        r"^it's\s+", r"^call me\s+",
    ]:
        spoken_name = re.sub(pattern, "", spoken_name, flags=re.IGNORECASE).strip()
    spoken_name = re.sub(r"[^a-zA-Z0-9\s\-]", "", spoken_name)
    return spoken_name[:40].strip() or "Guest"

def clean_spelled_name(text: str) -> Optional[str]:
    text = text.upper().strip()
    for pat in [r"\bMY NAME IS\b", r"\bIT IS\b", r"\bIT'S\b", r"\bSPELL(?:ED|ING)?\b"]:
        text = re.sub(pat, "", text)
    text = re.sub(r"[^A-Z\s]", " ", text)
    letters = [p for p in text.split() if len(p) == 1 and p.isalpha()]
    return "".join(letters).title() if len(letters) >= 2 else None

def extract_name_from_text(text: str) -> Optional[str]:
    for pattern in [
        r"\bmy name is\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bmy name's\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bcall me\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
    ]:
        match = re.search(pattern, text.strip(), flags=re.IGNORECASE)
        if match:
            candidate = clean_spoken_name(match.group(1))
            if 1 <= len(candidate.split()) <= 4:
                return candidate
    return None

def looks_like_invalid_name(name: str) -> bool:
    return name.strip().lower() in {
        "hello","hi","hey","good morning","good afternoon",
        "good evening","yes","no","okay","ok","thanks","thank you","bye","goodbye",
    }

def rename_current_user(old_user_key, user_profile, new_name):
    users = load_users()
    new_name = clean_spoken_name(new_name)
    new_key  = slugify_name(new_name)
    if not new_name or looks_like_invalid_name(new_name):
        return old_user_key, user_profile
    existing = users.get(new_key)
    if existing:
        existing["last_seen"] = now_ts()
        save_users(users)
        return new_key, existing
    old_profile = users.pop(old_user_key, user_profile)
    old_profile["name"]      = new_name
    old_profile["last_seen"] = now_ts()
    users[new_key] = old_profile
    save_users(users)
    return new_key, users[new_key]

def build_user_memory_context(user_profile: Optional[dict]) -> str:
    if not user_profile:
        return ""
    name    = user_profile.get("name", "the user")
    summary = user_profile.get("conversation_summary", "").strip() or "No previous conversation summary is available."
    return f"""
USER MEMORY CONTEXT
The user's name is {name}.

Previous conversation summary:
{summary}

Rules:
- Use the user's name naturally when appropriate.
- Do not claim to remember anything beyond this saved local JSON context.
- Do not reveal the raw JSON file unless the user asks.
""".strip()

def save_session_transcript(user_key, user_profile, session_log) -> str:
    ensure_data_dirs()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(SESSIONS_DIR, f"{user_key}_{timestamp}.json")
    data = {
        "user": {"key": user_key, "name": user_profile.get("name", "Guest")},
        "session": {
            "started_at": session_log[0]["timestamp"] if session_log else now_ts(),
            "ended_at": now_ts(),
            "model": MODEL_NAME,
            "fusion": {
                "algorithm": "adaptive_reliability_aware_late_fusion",
                "gate_threshold": FUSION_GATE_THRESHOLD,
                "modalities": ["linguistic", "acoustic", "visual"],
            },
            "asr":  {"backend": "faster-whisper", **FAST_WHISPER_CONFIG},
            "face_emotion": {
                "backend": "qwen2.5vl via Ollama",
                "camera_device": CAMERA_DEVICE,
                "vision_model": VISION_MODEL_NAME,
            },
            "vad": {
                "backend": "Silero VAD",
                "sample_rate": SILERO_SAMPLE_RATE,
                "threshold": SILERO_THRESHOLD,
            },
        },
        "messages": session_log,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    return path

def summarize_session_with_llm(client, session_log, previous_summary="") -> str:
    if not session_log:
        return previous_summary
    compact = [f"{i['role']}: {i['content']}" for i in session_log[-20:]]
    prompt = f"""
Summarize this human-robot conversation for future continuity.

Previous saved summary:
{previous_summary or "None"}

Recent session:
{chr(10).join(compact)}

Return a concise memory summary in 3-6 bullet points.
Include: user's name, main topics, preferences, emotional context.
Do not invent facts.
""".strip()
    try:
        resp = client.chat(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "You summarize conversations accurately."},
                {"role": "user",   "content": prompt},
            ],
            options={"temperature": 0.2, "num_predict": 180, "num_ctx": 2048},
            stream=False,
        )
        return resp["message"]["content"].strip()
    except Exception as exc:
        print_ts(f"Could not summarize session: {exc}")
        return previous_summary

def update_user_after_session(client, user_key, session_path, session_log) -> None:
    users = load_users()
    if user_key not in users:
        return
    users[user_key]["last_seen"] = now_ts()
    users[user_key].setdefault("session_files", []).append(session_path)
    if ENABLE_LLM_SESSION_SUMMARY:
        prev = users[user_key].get("conversation_summary", "")
        users[user_key]["conversation_summary"] = summarize_session_with_llm(
            client, session_log, prev)
    save_users(users)


# ══════════════════════════════════════════════════════════════════════════════
# Ollama setup helpers
# ══════════════════════════════════════════════════════════════════════════════

def check_ollama_available(max_attempts: int = 10, delay_seconds: float = 1.0) -> None:
    client = Client(host=OLLAMA_HOST)
    for attempt in range(1, max_attempts + 1):
        try:
            client.list()
            print_ts(f"Ollama is reachable at {OLLAMA_HOST}.")
            return
        except Exception as exc:
            print_ts(f"Ollama not reachable yet, attempt {attempt}/{max_attempts}: {exc}")
            time.sleep(delay_seconds)
    raise RuntimeError(f"Could not connect to Ollama at {OLLAMA_HOST}.")

def ensure_model_available(model_name: str = MODEL_NAME) -> None:
    print_ts(f"Using Ollama model '{model_name}'. Skipping local pull.")


# ══════════════════════════════════════════════════════════════════════════════
# Audio helpers
# ══════════════════════════════════════════════════════════════════════════════

def list_input_devices() -> None:
    print("\nAvailable input devices:")
    try:
        devices  = sd.query_devices()
        hostapis = sd.query_hostapis()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return
    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            hostapi_name = hostapis[device["hostapi"]]["name"]
            print(f"[mic {idx}] {device['name']} | hostapi={hostapi_name} | "
                  f"inputs={device['max_input_channels']}")
    print()

def get_input_samplerate(input_device: Optional[int]) -> int:
    info = sd.query_devices(kind="input") if input_device is None else sd.query_devices(input_device)
    sr = int(round(info["default_samplerate"]))
    return sr if sr > 0 else TARGET_SAMPLE_RATE

def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32, copy=False)
    if audio.size == 0:
        return audio.astype(np.float32, copy=False)
    duration   = len(audio) / original_sr
    new_len    = max(1, int(round(duration * target_sr)))
    old_times  = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_times  = np.linspace(0.0, duration, num=new_len,   endpoint=False)
    return np.interp(new_times, old_times, audio).astype(np.float32)

def save_audio_to_temp_wav(audio_16k: np.ndarray) -> Optional[str]:
    if audio_16k.size == 0:
        return None
    peak = float(np.max(np.abs(audio_16k)))
    rms  = float(np.sqrt(np.mean(audio_16k ** 2)))
    print_ts(f"Captured utterance: peak={peak:.4f}, rms={rms:.4f}")
    if peak < MIN_PEAK_THRESHOLD or rms < MIN_RMS_THRESHOLD:
        print("Captured audio was too quiet.")
        return None
    audio_16k = np.clip(audio_16k * min(0.9 / max(peak, 1e-6), 10.0), -1.0, 1.0)
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        wav_path = tmp.name
    sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
    return wav_path


# ══════════════════════════════════════════════════════════════════════════════
# ASR: transcription with word-level confidence
# ══════════════════════════════════════════════════════════════════════════════

def transcribe_with_confidence(
    wav_path: str,
    whisper_model: WhisperModel,
) -> TranscriptionResult:
    """
    Transcribe with faster-whisper and return a TranscriptionResult containing:
    - text
    - word_confidences: per-word probability (0..1) when word_timestamps=True
    - no_speech_prob: mean segment-level no-speech probability
    - avg_logprob: mean segment-level log-probability (fallback confidence proxy)

    These signals feed directly into compute_linguistic_reliability().
    """
    segments, info = whisper_model.transcribe(
        wav_path,
        language=FAST_WHISPER_CONFIG.get("language"),
        beam_size=int(FAST_WHISPER_CONFIG.get("beam_size", 1)),
        vad_filter=bool(FAST_WHISPER_CONFIG.get("vad_filter", False)),
        condition_on_previous_text=False,
        word_timestamps=True,   # ← enables per-word probability
    )

    all_segments     = list(segments)
    text_parts       = []
    word_confidences = []
    no_speech_probs  = []
    avg_logprobs     = []

    for seg in all_segments:
        text_parts.append(seg.text.strip())
        no_speech_probs.append(getattr(seg, "no_speech_prob", 0.0))
        avg_logprobs.append(getattr(seg, "avg_logprob", -1.0))
        if seg.words:
            for word in seg.words:
                prob = getattr(word, "probability", None)
                if prob is not None:
                    word_confidences.append(float(prob))

    text = re.sub(r"\s+", " ", " ".join(text_parts)).strip()
    if len(text.split()) <= 1 and len(text) < 3:
        text = ""

    return TranscriptionResult(
        text=text,
        word_confidences=word_confidences,
        no_speech_prob=float(np.mean(no_speech_probs)) if no_speech_probs else 0.0,
        avg_logprob=float(np.mean(avg_logprobs))       if avg_logprobs    else -1.0,
    )


# Backward-compatible alias for any callers that still use the old signature.
def transcribe_with_faster_whisper(wav_path: str, whisper_model: WhisperModel) -> str:
    return transcribe_with_confidence(wav_path, whisper_model).text

transcribe_audio = transcribe_with_faster_whisper


# ══════════════════════════════════════════════════════════════════════════════
# Linguistic reliability score
# ══════════════════════════════════════════════════════════════════════════════

def compute_linguistic_reliability(transcription: TranscriptionResult) -> float:
    """
    r_L = mean_word_confidence × length_factor × (1 − no_speech_prob)

    - mean_word_confidence: average per-word ASR probability.
      Falls back to an approximation from avg_logprob if word timestamps
      were unavailable.
    - length_factor: min(1, n_words / 5)  — penalises very short utterances.
    - (1 − no_speech_prob): complement of the segment-level silence score.
    """
    if not transcription.text.strip():
        return 0.0

    # ── mean word-level confidence ──────────────────────────────────────────
    if transcription.word_confidences:
        mean_conf = float(np.mean(transcription.word_confidences))
    else:
        # Approximate from log-prob: e^logprob clips to [0, 1]
        lp = transcription.avg_logprob
        mean_conf = float(np.clip(np.exp(lp), 0.0, 1.0)) if lp > -10.0 else 0.40

    # ── length factor ────────────────────────────────────────────────────────
    n_words = len(transcription.text.split())
    length_factor = min(1.0, n_words / LINGUISTIC_MIN_WORDS_FOR_FULL_CREDIT)

    # ── speech activity ──────────────────────────────────────────────────────
    speech_factor = max(0.0, 1.0 - transcription.no_speech_prob)

    r_L = mean_conf * length_factor * speech_factor
    return float(np.clip(r_L, 0.0, 1.0))


# ══════════════════════════════════════════════════════════════════════════════
# Acoustic modality: prosody extraction + Plutchik mapping
# ══════════════════════════════════════════════════════════════════════════════

def extract_prosody_features(wav_path: str) -> Optional[ProsodyFeatures]:
    """
    Extract a prosodic feature vector from a WAV file using librosa.
    Returns None if librosa is not installed or extraction fails.

    Features:
    - F0 mean and std via librosa.yin (faster than pYIN for real-time)
    - RMS energy (speech loudness proxy)
    - Speaking rate (onset events per second — syllable proxy)
    - Zero-crossing rate (voice quality correlate)
    - Voiced ratio (proportion of voiced frames)
    """
    if not LIBROSA_AVAILABLE:
        return None

    try:
        y, sr = librosa.load(wav_path, sr=None, mono=True)
        if sr != 16000:
            y = librosa.resample(y, orig_sr=sr, target_sr=16000)
        sr = 16000

        duration = len(y) / sr
        if duration < 0.1:
            return None

        # F0 via YIN
        f0 = librosa.yin(y, fmin=60, fmax=400, sr=sr)
        voiced_f0 = f0[f0 > 0]
        f0_mean  = float(np.mean(voiced_f0))    if len(voiced_f0) > 0 else 0.0
        f0_std   = float(np.std(voiced_f0))     if len(voiced_f0) > 0 else 0.0
        voiced_ratio = float(len(voiced_f0) / max(1, len(f0)))

        # RMS energy
        rms_mean = float(np.mean(librosa.feature.rms(y=y)[0]))

        # Zero-crossing rate
        zcr_mean = float(np.mean(librosa.feature.zero_crossing_rate(y)[0]))

        # Speaking rate (onset events as syllable proxy)
        onset_env    = librosa.onset.onset_strength(y=y, sr=sr)
        onset_frames = librosa.onset.onset_detect(onset_envelope=onset_env, sr=sr)
        speaking_rate = float(len(onset_frames) / max(0.1, duration))

        return ProsodyFeatures(
            f0_mean=f0_mean, f0_std=f0_std,
            rms_energy=rms_mean, speaking_rate=speaking_rate,
            zcr_mean=zcr_mean, voiced_ratio=voiced_ratio,
            duration_seconds=duration,
        )

    except Exception as exc:
        print_ts(f"Prosody extraction failed: {exc}")
        return None


def prosody_to_plutchik_probs(features: ProsodyFeatures) -> dict[str, float]:
    """
    Rule-based mapping from prosodic features to a Plutchik probability distribution.
    Grounded in Scherer (1986) vocal affect expression research.

    Threshold calibration for NORMAL CONVERSATIONAL SPEECH:
    ─────────────────────────────────────────────────────────
    Female speakers typically have F0 in the range 160–220 Hz in conversation.
    Normal conversational RMS energy is approximately 0.04–0.15.
    Normal speaking rate is 4–6 syllable-like onsets per second.
    F0 variability in neutral speech is roughly 20–45 Hz std.

    The thresholds below are set to fire ONLY for clearly elevated values
    that exceed the normal conversational baseline, so neutral speech
    defaults to trust/anticipation rather than anger.

    Emotional speech thresholds (must CLEARLY exceed baseline):
    - high_energy:  rms  > 0.15  (very loud; normal conv is 0.04–0.12)
    - low_energy:   rms  < 0.008 (near-silent)
    - high_pitch:   f0   > 260   (clearly elevated; female normal is 160–220)
    - low_pitch:    f0   < 110   (clearly lowered; indicates flat/sad delivery)
    - high_var:     f0var > 70   (highly variable; normal is 20–45)
    - fast_rate:    rate > 7.5   (rushed; normal conv is 4–6/s)
    - slow_rate:    rate < 1.5   (very slow/drawn out)
    """
    probs = {e: 0.05 for e in PLUTCHIK_EMOTIONS}

    rms   = features.rms_energy
    f0    = features.f0_mean
    f0var = features.f0_std
    rate  = features.speaking_rate

    # Recalibrated thresholds — see docstring above
    high_energy = rms   > 0.18   # loud speech; normal conv peaks ~0.12–0.15
    low_energy  = rms   < 0.008
    high_pitch  = f0    > 260    # clearly elevated; female normal = 160–220 Hz
    low_pitch   = 0 < f0 < 110
    high_var    = f0var > 70     # highly variable; normal conv = 20–45 Hz std
    fast_rate   = rate  > 7.5    # rushed speech; normal conv = 4–6/s
    slow_rate   = rate  < 1.5

    # ── Emotional speech patterns ─────────────────────────────────────────
    if high_energy and high_pitch and fast_rate and high_var:
        # Shouting with high pitch variability → anger dominant
        probs["anger"]        += 0.35
        probs["fear"]         += 0.15
        probs["joy"]          += 0.10

    elif high_energy and high_pitch and fast_rate:
        # Loud, high-pitched, fast → excited joy or agitated anger
        probs["joy"]          += 0.30
        probs["anger"]        += 0.15

    elif low_energy and low_pitch and slow_rate:
        # Quiet, low-pitched, slow → sadness or fear
        probs["sadness"]      += 0.40
        probs["fear"]         += 0.15

    elif high_pitch and high_var and fast_rate:
        # High pitch variability + fast → fear or surprise
        probs["fear"]         += 0.30
        probs["surprise"]     += 0.20

    elif high_energy and not high_pitch:
        # Loud but not high-pitched → anger or disgust
        probs["anger"]        += 0.20
        probs["disgust"]      += 0.10

    elif fast_rate and not high_energy:
        # Fast but not loud → anticipation or mild anxiety
        probs["anticipation"] += 0.20
        probs["fear"]         += 0.10

    elif slow_rate and not low_energy:
        # Slow and audible → thoughtful trust or mild sadness
        probs["trust"]        += 0.20
        probs["sadness"]      += 0.10

    else:
        # ── DEFAULT: normal conversational speech ─────────────────────────
        # This branch now fires for the vast majority of ordinary conversation,
        # replacing the previous behaviour where normal female speech
        # (f0≈180–210 Hz, rms≈0.09, rate≈5–7/s) incorrectly triggered anger.
        probs["trust"]        += 0.45
        probs["anticipation"] += 0.15

    total = sum(probs.values())
    return {e: v / total for e, v in probs.items()}


def compute_acoustic_reliability(features: ProsodyFeatures) -> float:
    """
    r_A = normalised_RMS × voiced_ratio

    - normalised_RMS: RMS / reference_RMS, clipped to [0, 1].
      Near-silent audio → reliability ≈ 0.
    - voiced_ratio: proportion of the utterance that is voiced.
      Unvoiced or noise-only frames → lower reliability.
    - Very short utterances (< 0.3 s) → excluded entirely.
    """
    if features.duration_seconds < 0.3:
        return 0.0

    rms_score    = float(np.clip(features.rms_energy / ACOUSTIC_REF_RMS, 0.0, 1.0))
    voiced_score = float(np.clip(features.voiced_ratio, 0.0, 1.0))

    return float(np.clip(rms_score * voiced_score, 0.0, 1.0))


def build_acoustic_modal(wav_path: str) -> Optional[ModalityEmotionResult]:
    """
    Full acoustic modality pipeline: extract features → map to probs → compute reliability.
    Returns None if librosa is unavailable or extraction fails.
    """
    features = extract_prosody_features(wav_path)
    if features is None:
        return None

    probs       = prosody_to_plutchik_probs(features)
    reliability = compute_acoustic_reliability(features)

    print_ts(
        f"Acoustic: f0={features.f0_mean:.1f}Hz, rms={features.rms_energy:.4f}, "
        f"rate={features.speaking_rate:.1f}/s, voiced={features.voiced_ratio:.2f}, "
        f"reliability={reliability:.3f}"
    )

    return ModalityEmotionResult(
        probs=probs, reliability=reliability, modality="acoustic"
    )


# ══════════════════════════════════════════════════════════════════════════════
# Visual modality: face capture → ModalityEmotionResult
# ══════════════════════════════════════════════════════════════════════════════

def compute_visual_reliability(face_capture: FaceEmotionCapture) -> float:
    """
    r_V = detection_confidence × FER_confidence × face_area_factor

    In this implementation:
    - detection_confidence: 1.0 if at least one frame was analysed, 0.0 on error.
    - FER_confidence: top_score / 100, normalised from Qwen's percentage scores.
    - face_area_factor: encoded as the margin between top-1 and top-2 scores,
      which reflects how clearly the expression was captured.
    """
    if face_capture.error or not face_capture.averaged_scores:
        return 0.0

    scores = face_capture.averaged_scores
    if not scores:
        return 0.0

    ordered     = sorted(scores.values(), reverse=True)
    top_score   = ordered[0]
    second_score = ordered[1] if len(ordered) > 1 else 0.0

    # detection_confidence: 1.0 if we got samples, 0 otherwise
    detection_conf = 1.0 if face_capture.sampled_frame_count > 0 else 0.0

    # FER confidence: top score normalised to [0, 1]
    fer_conf = float(np.clip(top_score / 100.0, 0.0, 1.0))

    # Face area proxy: margin between top-1 and top-2 (clearer = higher)
    margin_norm = float(np.clip((top_score - second_score) / 50.0, 0.0, 1.0))

    r_V = detection_conf * fer_conf * 0.6 + margin_norm * 0.4
    return float(np.clip(r_V, 0.0, 1.0))


def build_visual_modal(
    face_capture: Optional[FaceEmotionCapture],
) -> Optional[ModalityEmotionResult]:
    """
    Convert FaceEmotionCapture averaged scores to a ModalityEmotionResult.
    Returns None if no capture was performed.
    """
    if face_capture is None:
        return None

    reliability = compute_visual_reliability(face_capture)
    scores      = face_capture.averaged_scores

    if not scores:
        probs = _uniform_probs()
    else:
        total = sum(scores.values())
        if total > 0:
            probs = {e: scores.get(e, 0.0) / total for e in PLUTCHIK_EMOTIONS}
        else:
            probs = _uniform_probs()

    print_ts(
        f"Visual: dominant={face_capture.dominant_emotion}, "
        f"reliable={face_capture.is_reliable}, "
        f"reliability={reliability:.3f}"
    )

    return ModalityEmotionResult(
        probs=probs, reliability=reliability, modality="visual"
    )


# ══════════════════════════════════════════════════════════════════════════════
# Linguistic modality: LLM → Plutchik distribution
# ══════════════════════════════════════════════════════════════════════════════

def _uniform_probs() -> dict[str, float]:
    return {e: 1.0 / len(PLUTCHIK_EMOTIONS) for e in PLUTCHIK_EMOTIONS}


def get_linguistic_emotion_probs(
    client: Client,
    text: str,
    facial_hint: Optional[str] = None,
) -> dict[str, float]:
    """
    Ask the LLM for a full Plutchik probability distribution over the user's utterance.
    Text is the primary signal; facial hint is a weak secondary signal.
    Returns a normalised dict summing to 1.0.
    """
    emotions      = ", ".join(PLUTCHIK_EMOTIONS.keys())
    facial_section = (
        f"Facial-expression hint (weak secondary signal): {facial_hint}\n"
        if facial_hint else "No facial-expression hint available.\n"
    )

    prompt = f"""
You are an emotion analysis system for a human-robot interaction prototype.

Assign a probability to each of Plutchik's 8 primary emotions for the user's message.
The probabilities must sum to 1.0.

Emotions: {emotions}

Rules:
- Use the user's text as the primary signal.
- Use the facial-expression hint only as a weak secondary signal.
- If text and facial hint conflict, trust the text more.
- For greetings (hello, hi, good morning) → assign high probability to "trust".
- For farewells (bye, goodbye) → assign high probability to "trust".
- Return valid JSON only, no markdown, no extra text.

Required JSON format:
{{
  "joy": 0.0, "trust": 0.0, "fear": 0.0, "surprise": 0.0,
  "sadness": 0.0, "disgust": 0.0, "anger": 0.0, "anticipation": 0.0,
  "reason": "brief explanation"
}}

User text: {text}
{facial_section}
""".strip()

    try:
        resp = client.chat(
            model=MODEL_NAME,
            format="json",
            messages=[
                {"role": "system", "content": "You return valid JSON only."},
                {"role": "user",   "content": prompt},
            ],
            options={"temperature": 0.1, "num_predict": 160, "num_ctx": 2048},
            stream=False,
        )
        raw  = resp["message"]["content"]
        data = safe_json_extract(raw)

        if not data:
            return _uniform_probs()

        probs: dict[str, float] = {}
        for e in PLUTCHIK_EMOTIONS:
            try:
                probs[e] = max(0.0, float(data.get(e, 0.0)))
            except Exception:
                probs[e] = 0.0

        total = sum(probs.values())
        if total > 0:
            return {e: v / total for e, v in probs.items()}
        return _uniform_probs()

    except Exception as exc:
        print_ts(f"Linguistic emotion prob detection failed: {exc}")
        return _uniform_probs()


def build_linguistic_modal(
    client: Client,
    transcription: TranscriptionResult,
    facial_hint: Optional[str] = None,
) -> ModalityEmotionResult:
    """
    Full linguistic modality pipeline:
    transcription → reliability score + Plutchik distribution.
    """
    reliability = compute_linguistic_reliability(transcription)

    if not transcription.text.strip():
        return ModalityEmotionResult(
            probs=_uniform_probs(), reliability=0.0, modality="linguistic"
        )

    probs = get_linguistic_emotion_probs(
        client=client,
        text=transcription.text,
        facial_hint=facial_hint,
    )

    print_ts(
        f"Linguistic: words={len(transcription.text.split())}, "
        f"mean_conf={np.mean(transcription.word_confidences):.3f}"
        if transcription.word_confidences else
        f"Linguistic: words={len(transcription.text.split())}, "
        f"logprob={transcription.avg_logprob:.2f}, "
        f"no_speech={transcription.no_speech_prob:.3f}, "
        f"reliability={reliability:.3f}"
    )

    return ModalityEmotionResult(
        probs=probs, reliability=reliability, modality="linguistic"
    )


# ══════════════════════════════════════════════════════════════════════════════
# Adaptive Reliability-Aware Late Fusion
# ══════════════════════════════════════════════════════════════════════════════

def adaptive_reliability_fusion(
    linguistic: Optional[ModalityEmotionResult],
    acoustic:   Optional[ModalityEmotionResult],
    visual:     Optional[ModalityEmotionResult],
) -> FusedEmotionResult:
    """
    Fuse three modality emotion distributions using dynamic reliability weights.

    Formula:
        P_fused(e) = Σ_m  w_m · P_m(e)  /  Σ_m w_m
        where  w_m = r_m  (reliability score, already in [0, 1])

    Gating: modalities with r_m < FUSION_GATE_THRESHOLD are excluded entirely.
    Fallback: if all modalities are gated, return a neutral "trust" label.

    The full weight vector and per-modality details are logged to the session
    transcript for benchmarking and ablation analysis.
    """
    modalities = [
        ("linguistic", linguistic),
        ("acoustic",   acoustic),
        ("visual",     visual),
    ]

    raw_weights = {
        name: (m.reliability if m is not None else 0.0)
        for name, m in modalities
    }

    # Apply gating threshold
    active = [
        (name, m)
        for name, m in modalities
        if m is not None and m.reliability >= FUSION_GATE_THRESHOLD
    ]

    print_ts(
        f"Fusion gate ({FUSION_GATE_THRESHOLD}): "
        + " | ".join(
            f"{name}={raw_weights[name]:.3f} "
            f"({'PASS' if raw_weights[name] >= FUSION_GATE_THRESHOLD else 'GATE'})"
            for name, _ in modalities
        )
    )

    # Fallback when all modalities are gated
    if not active:
        print_ts("All modalities gated. Using neutral fallback (trust).")
        return FusedEmotionResult(
            emotion="trust", confidence=0.3,
            probs=_uniform_probs(),
            weights={n: 0.0 for n, _ in modalities},
            raw_weights=raw_weights,
            reason="All modalities below reliability threshold; neutral fallback used.",
            linguistic=linguistic, acoustic=acoustic, visual=visual,
        )

    # Normalise weights across active modalities
    total_weight = sum(m.reliability for _, m in active)
    fused_probs  = {e: 0.0 for e in PLUTCHIK_EMOTIONS}

    for _, m in active:
        w = m.reliability / total_weight
        for e in PLUTCHIK_EMOTIONS:
            fused_probs[e] += w * m.probs.get(e, 0.0)

    # Normalised effective weights (for logging)
    eff_weights = {name: 0.0 for name, _ in modalities}
    for name, m in active:
        eff_weights[name] = m.reliability / total_weight

    # Dominant label
    dominant_emotion, dominant_prob = max(fused_probs.items(), key=lambda x: x[1])

    active_names = [name for name, _ in active]
    reason = (
        f"Adaptive fusion from [{', '.join(active_names)}]. "
        f"Effective weights: "
        + ", ".join(f"{n}={eff_weights[n]:.2f}" for n in ["linguistic", "acoustic", "visual"])
        + f". Dominant: {dominant_emotion} ({dominant_prob:.2f})"
    )

    print_ts(f"Fused emotion: {dominant_emotion} (conf={dominant_prob:.3f})")
    print_ts(f"  {reason}")

    return FusedEmotionResult(
        emotion=dominant_emotion,
        confidence=dominant_prob,
        probs=fused_probs,
        weights=eff_weights,
        raw_weights=raw_weights,
        reason=reason,
        linguistic=linguistic,
        acoustic=acoustic,
        visual=visual,
    )


def fused_to_emotion_result(fused: FusedEmotionResult) -> EmotionResult:
    """Convert FusedEmotionResult to the EmotionResult expected by generate_response."""
    return EmotionResult(
        emotion=fused.emotion,
        confidence=fused.confidence,
        reason=fused.reason,
    )


def fused_to_session_json(fused: FusedEmotionResult) -> dict:
    """Serialise the full fusion state for transcript logging."""
    return {
        "algorithm": "adaptive_reliability_aware_late_fusion",
        "fused_emotion": fused.emotion,
        "fused_confidence": round(fused.confidence, 4),
        "fused_probs": {k: round(v, 4) for k, v in fused.probs.items()},
        "effective_weights": {k: round(v, 4) for k, v in fused.weights.items()},
        "raw_reliability_scores": {k: round(v, 4) for k, v in fused.raw_weights.items()},
        "reason": fused.reason,
        "modalities": {
            "linguistic": {
                "reliability": round(fused.linguistic.reliability, 4),
                "dominant": max(fused.linguistic.probs, key=fused.linguistic.probs.get),
                "probs": {k: round(v, 4) for k, v in fused.linguistic.probs.items()},
            } if fused.linguistic else None,
            "acoustic": {
                "reliability": round(fused.acoustic.reliability, 4),
                "dominant": max(fused.acoustic.probs, key=fused.acoustic.probs.get),
                "probs": {k: round(v, 4) for k, v in fused.acoustic.probs.items()},
            } if fused.acoustic else None,
            "visual": {
                "reliability": round(fused.visual.reliability, 4),
                "dominant": max(fused.visual.probs, key=fused.visual.probs.get),
                "probs": {k: round(v, 4) for k, v in fused.visual.probs.items()},
            } if fused.visual else None,
        },
    }


# ══════════════════════════════════════════════════════════════════════════════
# Camera / Qwen2.5-VL helpers  (unchanged from original)
# ══════════════════════════════════════════════════════════════════════════════

def normalize_camera_frame(frame: np.ndarray) -> np.ndarray:
    if USE_ZED_HALF_FRAME_CROP:
        height, width = frame.shape[:2]
        frame = frame[:, : width // 2]
    return frame

def get_camera_backend() -> int:
    if sys.platform == "darwin":
        return cv2.CAP_AVFOUNDATION
    if sys.platform.startswith("linux"):
        return cv2.CAP_V4L2
    return cv2.CAP_ANY

def open_camera(camera_device: Optional[int]) -> cv2.VideoCapture:
    candidates = list({camera_device, 0, 1, 2, 3}) if camera_device is not None else [0, 1, 2, 3]
    for idx in candidates:
        if idx is None:
            continue
        cap = cv2.VideoCapture(idx, get_camera_backend())
        if not cap.isOpened():
            cap.release()
            continue
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
        cap.set(cv2.CAP_PROP_FRAME_WIDTH,  CAMERA_FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_FRAME_HEIGHT)
        cap.set(cv2.CAP_PROP_FPS, 30)
        time.sleep(0.2)
        ok, frame = cap.read()
        if ok and frame is not None:
            print_ts(f"Using camera /dev/video{idx} at "
                     f"{int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))}x"
                     f"{int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))}")
            return cap
        cap.release()
    return cv2.VideoCapture(-1)

def resize_keep_aspect(frame_bgr: np.ndarray, max_side: int = VISION_MAX_IMAGE_SIDE) -> np.ndarray:
    h, w = frame_bgr.shape[:2]
    longest = max(h, w)
    if longest <= max_side:
        return frame_bgr
    scale = max_side / float(longest)
    return cv2.resize(frame_bgr, (max(1, int(w*scale)), max(1, int(h*scale))), interpolation=cv2.INTER_AREA)

def image_quality_metrics(frame_bgr: np.ndarray) -> dict:
    try:
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        return {"brightness": float(np.mean(gray)), "sharpness": float(cv2.Laplacian(gray, cv2.CV_64F).var())}
    except Exception:
        return {"brightness": 0.0, "sharpness": 0.0}

def denoise_frame(frame_bgr):
    if not VISION_DENOISE_ENABLED: return frame_bgr
    try:
        return cv2.fastNlMeansDenoisingColored(frame_bgr, None, h=VISION_DENOISE_H,
            hColor=VISION_DENOISE_H_COLOR, templateWindowSize=7, searchWindowSize=21)
    except Exception:
        return frame_bgr

def enhance_lighting(frame_bgr):
    if not VISION_LIGHTING_ENHANCE_ENABLED: return frame_bgr
    try:
        lab = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=VISION_CLAHE_CLIP_LIMIT, tileGridSize=(8,8))
        return cv2.cvtColor(cv2.merge((clahe.apply(l), a, b)), cv2.COLOR_LAB2BGR)
    except Exception:
        return frame_bgr

def sharpen_frame(frame_bgr):
    if not VISION_SHARPEN_ENABLED: return frame_bgr
    try:
        blurred = cv2.GaussianBlur(frame_bgr, (0,0), sigmaX=1.0)
        return cv2.addWeighted(frame_bgr, 1.35, blurred, -0.35, 0)
    except Exception:
        return frame_bgr

def crop_largest_face_or_center(frame_bgr):
    h, w = frame_bgr.shape[:2]
    try:
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        cascade = cv2.CascadeClassifier(
            os.path.join(cv2.data.haarcascades, "haarcascade_frontalface_default.xml"))
        faces = cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(60,60))
        if len(faces) > 0:
            x, y, fw, fh = max(faces, key=lambda b: b[2]*b[3])
            pad = int(max(fw, fh) * 0.65)
            crop = frame_bgr[max(0,y-pad):min(h,y+fh+pad), max(0,x-pad):min(w,x+fw+pad)]
            if crop.size > 0:
                return resize_keep_aspect(crop)
    except Exception:
        pass
    side = min(h, w)
    x1, y1 = (w - side) // 2, (h - side) // 2
    crop = frame_bgr[max(0,y1):y1+side, max(0,x1):x1+side]
    return resize_keep_aspect(crop if crop.size > 0 else frame_bgr)

def preprocess_frame_for_vlm(frame_bgr):
    prep = crop_largest_face_or_center(frame_bgr)
    before = image_quality_metrics(prep)
    prep = denoise_frame(prep)
    prep = enhance_lighting(prep)
    prep = sharpen_frame(prep)
    prep = resize_keep_aspect(prep)
    after = image_quality_metrics(prep)
    return prep, {**{f"before_{k}": v for k,v in before.items()}, **{f"after_{k}": v for k,v in after.items()},
                  "width": float(prep.shape[1]), "height": float(prep.shape[0])}

def is_vlm_image_quality_usable(metrics):
    b = metrics.get("after_brightness", 0.0)
    s = metrics.get("after_sharpness",  0.0)
    if b < VISION_MIN_BRIGHTNESS: return False, f"too dark: {b:.1f}"
    if b > VISION_MAX_BRIGHTNESS: return False, f"too bright: {b:.1f}"
    if s < VISION_MIN_SHARPNESS:  return False, f"too blurry: {s:.1f}"
    return True, "ok"

def save_debug_frame(frame_bgr, prefix="vlm_frame"):
    if not VISION_DEBUG: return None
    try:
        os.makedirs(VISION_DEBUG_DIR, exist_ok=True)
        path = os.path.join(VISION_DEBUG_DIR, f"{prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}.jpg")
        cv2.imwrite(path, frame_bgr, [int(cv2.IMWRITE_JPEG_QUALITY), VISION_JPEG_QUALITY])
        return path
    except Exception:
        return None

def encode_frame_for_ollama(frame_bgr):
    try:
        prep, metrics = preprocess_frame_for_vlm(frame_bgr)
        usable, reason = is_vlm_image_quality_usable(metrics)
        if VISION_DEBUG:
            print_ts(f"VLM image quality: {metrics.get('after_brightness',0):.1f}brightness, "
                     f"{metrics.get('after_sharpness',0):.1f}sharpness — {reason}")
            save_debug_frame(prep, "qwen_face_input_clean")
        if not usable:
            return None
        ok, buf = cv2.imencode(".jpg", prep, [int(cv2.IMWRITE_JPEG_QUALITY), VISION_JPEG_QUALITY])
        return base64.b64encode(buf.tobytes()).decode("utf-8") if ok else None
    except Exception as exc:
        print_ts(f"Frame encode failed: {exc}")
        return None

EMOTION_ALIASES = {
    "happy":"joy","happiness":"joy","smile":"joy","smiling":"joy",
    "neutral":"trust","calm":"trust","friendly":"trust","relaxed":"trust",
    "concern":"fear","concerned":"fear","anxious":"fear","anxiety":"fear","afraid":"fear",
    "surprised":"surprise","sad":"sadness","unhappy":"sadness",
    "angry":"anger","mad":"anger","annoyed":"anger",
    "disgusted":"disgust","expectant":"anticipation","curious":"anticipation","thinking":"anticipation",
}

def canonical_emotion_name(name: str) -> Optional[str]:
    cleaned = re.sub(r"[^a-zA-Z]+", "", str(name).strip().lower())
    if cleaned in PLUTCHIK_EMOTIONS: return cleaned
    return EMOTION_ALIASES.get(cleaned)

def normalize_plutchik_scores(raw_data: dict) -> Optional[dict[str, float]]:
    if not isinstance(raw_data, dict): return None
    raw_scores = raw_data.get("scores") if isinstance(raw_data.get("scores"), dict) else raw_data
    scores = {e: 0.0 for e in PLUTCHIK_EMOTIONS}
    if isinstance(raw_scores, dict):
        for key, value in raw_scores.items():
            emotion = canonical_emotion_name(str(key))
            if not emotion: continue
            try: scores[emotion] += max(0.0, float(value))
            except Exception: continue
    total = sum(scores.values())
    if total <= 0:
        dominant = canonical_emotion_name(str(raw_data.get("dominant_emotion", raw_data.get("emotion", ""))))
        if dominant:
            conf = max(0.05, min(1.0, float(raw_data.get("confidence", 0.55))))
            other = max(0.0, 1.0 - conf) / max(1, len(PLUTCHIK_EMOTIONS) - 1)
            return {e: (conf if e == dominant else other) * 100.0 for e in PLUTCHIK_EMOTIONS}
        return None
    return {e: (s * 100.0 if total <= 1.5 else (s / total) * 100.0) for e, s in scores.items()}

def build_qwen_face_prompt() -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    return f"""
You are a conservative facial-expression classifier for a human-robot interaction system.

Analyze the visible human face. Use only facial expression, not age, gender, race, or identity.
Map the expression to exactly one of Plutchik's 8 primary emotions: {emotions}

CRITICAL MAPPING RULES — read carefully before assigning:

trust:
  - A relaxed, neutral, or politely attentive face
  - A mild, closed-mouth, or social smile (the kind seen in everyday conversation)
  - A calm, composed expression with no strong emotional activation
  - DEFAULT for any ambiguous or low-intensity expression

joy:
  - A CLEARLY enthusiastic, delighted, or laughing expression
  - Wide open smile showing teeth with raised cheeks and eye crinkles (Duchenne smile)
  - Visibly elevated excitement or happiness — NOT a polite conversational smile
  - Only assign joy when the expression is UNAMBIGUOUSLY positive and strong

anticipation:
  - A concentrated, curious, or thinking face
  - Slightly raised brows with a neutral or mild expression

fear:
  - Wide eyes, tense brow, or visibly startled expression

sadness:
  - Downturned mouth, drooping eyes, or visible distress

anger:
  - Furrowed brow, tightened jaw, or tense aggressive expression

surprise:
  - Raised eyebrows AND open mouth simultaneously

disgust:
  - Nose wrinkle, raised upper lip, or visible aversion

IMPORTANT:
- In a laboratory or conversational setting, most expressions are mild.
- A person simply talking or listening will usually show trust, not joy.
- Do NOT assign joy unless the expression is clearly and strongly joyful.
- When uncertain between joy and trust, ALWAYS choose trust.
- If no face is visible, set dominant_emotion="trust", confidence=0.1, flat scores.

Return JSON only — no markdown, no extra text:
{{
  "dominant_emotion": "joy|trust|fear|surprise|sadness|disgust|anger|anticipation",
  "scores": {{
    "joy": 0.0, "trust": 0.0, "fear": 0.0, "surprise": 0.0,
    "sadness": 0.0, "disgust": 0.0, "anger": 0.0, "anticipation": 0.0
  }},
  "confidence": 0.0,
  "reason": "short explanation referencing specific facial features observed"
}}
""".strip()

def _dampen_reflexive_joy(scores: dict[str, float]) -> dict[str, float]:
    """
    In a laboratory conversational setting, Qwen2.5-VL frequently assigns
    joy > 70% to any smiling face, conflating polite social smiles with
    genuine delight. This post-processor redistributes excess joy probability
    toward trust when the joy score is very high and no other signal is strong.

    Rule: if joy > 0.60 and the second-highest emotion < 0.20,
    redistribute 40% of the excess joy above 0.60 into trust.
    This leaves a clear joy signal intact when it is genuinely strong
    but prevents a 90% joy score from a polite smile dominating the fusion.
    """
    joy = scores.get("joy", 0.0)
    if joy <= 0.60:
        return scores

    ordered = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    second_score = ordered[1][1] if len(ordered) > 1 else 0.0

    if second_score >= 0.20:
        # Second emotion is already meaningful — do not dampen
        return scores

    excess    = joy - 0.60
    transfer  = excess * 0.40        # move 40% of the excess to trust
    new_joy   = joy - transfer
    new_trust = scores.get("trust", 0.0) + transfer

    updated = dict(scores)
    updated["joy"]   = new_joy
    updated["trust"] = new_trust

    # Re-normalise
    total = sum(updated.values())
    return {e: v / total for e, v in updated.items()} if total > 0 else scores


def analyze_frame_emotion_scores(frame_bgr, vision_client) -> Optional[dict[str, float]]:
    image_b64 = encode_frame_for_ollama(frame_bgr)
    if not image_b64: return None
    try:
        resp = vision_client.chat(
            model=VISION_MODEL_NAME, format="json",
            messages=[{"role":"user","content":build_qwen_face_prompt(),"images":[image_b64]}],
            options={"temperature":0.0,"num_predict":220,"num_ctx":2048},
            stream=False,
        )
        raw  = resp.get("message",{}).get("content","")
        if VISION_DEBUG: print_ts(f"Qwen2.5-VL raw: {raw[:300]}")
        data = safe_json_extract(raw)
        if not isinstance(data, dict): return None
        scores = normalize_plutchik_scores(data)
        if not scores: return None

        # Dampen reflexive high-joy scores from polite conversational smiles
        scores = _dampen_reflexive_joy(scores)

        top_e, top_s = max(scores.items(), key=lambda x: x[1])
        if top_s < FACE_MIN_TOP_SCORE:
            print_ts(f"Qwen result rejected (weak): {top_e}={top_s:.1f}%")
            return None
        return scores
    except Exception as exc:
        print_ts(f"Qwen2.5-VL failed: {exc}")
        return None


class FaceEmotionSampler:
    def __init__(self, camera_device, vision_client):
        self.camera_device   = camera_device
        self.vision_client   = vision_client
        self.cap             = None
        self.window_created  = False
        self.started_at      = now_ts()
        self.error           = None
        self.emotion_score_samples: list[dict[str, float]] = []
        self.frame_count     = 0
        self.sampled_frame_count = 0
        self.capture_start_time  = None
        self.last_sample_time    = 0.0
        self.last_status         = "warming up..."
        self.snapshot_frame      = None
        self.snapshot_taken_at   = None

    def start(self):
        self.started_at = now_ts()
        self.capture_start_time = time.time()
        self.cap = open_camera(self.camera_device)
        if not self.cap.isOpened():
            self.error = "Could not open camera."
            self.cap.release()
            self.cap = None
            return
        if CAMERA_PREVIEW_ENABLED:
            try:
                cv2.namedWindow(CAMERA_PREVIEW_WINDOW_NAME, cv2.WINDOW_NORMAL)
                self.window_created = True
            except Exception as exc:
                self.error = f"Preview could not start: {exc}"

    def _draw_preview(self, frame):
        if not (CAMERA_PREVIEW_ENABLED and self.window_created): return
        try:
            pf = frame.copy()
            cv2.putText(pf, "Recording speech...", (20,35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2, cv2.LINE_AA)
            cv2.putText(pf, f"Emotion: {self.last_status}", (20,70), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,255), 2, cv2.LINE_AA)
            cv2.imshow(CAMERA_PREVIEW_WINDOW_NAME, cv2.resize(pf, (CAMERA_PREVIEW_WIDTH, CAMERA_PREVIEW_HEIGHT)))
            cv2.waitKey(1)
        except Exception as exc:
            self.error = f"Preview failed: {exc}"

    def sample_if_due(self):
        if self.cap is None or self.capture_start_time is None: return
        ok, frame = self.cap.read()
        if not ok or frame is None: return
        frame = normalize_camera_frame(frame)
        self.frame_count += 1
        elapsed = time.time() - self.capture_start_time
        self._draw_preview(frame)
        if elapsed >= CAMERA_WARMUP_SECONDS and self.snapshot_frame is None:
            self.snapshot_frame    = frame.copy()
            self.snapshot_taken_at = now_ts()
            self.sampled_frame_count = 1
            self.last_status = "snapshot captured"
            print_ts("Facial snapshot captured; Qwen analysis deferred to speech end.")

    def _analyze_snapshot_now(self):
        if self.snapshot_frame is None:
            self.last_status = "no snapshot"
            return
        print_ts("Analyzing facial snapshot with Qwen2.5-VL...")
        scores = analyze_frame_emotion_scores(self.snapshot_frame, self.vision_client)
        if not scores:
            self.last_status = "no reliable VLM result"
            return
        top_e, top_s = max(scores.items(), key=lambda x: x[1])
        if top_s < FACE_MIN_TOP_SCORE:
            self.last_status = f"weak: {top_e}={top_s:.0f}%"
            return
        self.emotion_score_samples.append(scores)
        self.last_status = f"{top_e}: {top_s:.0f}%"
        print_ts(f"Qwen2.5-VL accepted: {self.last_status}")

    def finish(self) -> FaceEmotionCapture:
        if self.cap is not None:
            self.cap.release(); self.cap = None
        if self.window_created:
            try: cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME); cv2.waitKey(1)
            except Exception: pass
        try:
            self._analyze_snapshot_now()
        except Exception as exc:
            self.error = f"Qwen2.5-VL analysis failed: {exc}"
            print_ts(self.error)
        return FaceEmotionCapture(
            emotion_score_samples=self.emotion_score_samples,
            frame_count=self.frame_count,
            sampled_frame_count=self.sampled_frame_count,
            started_at=self.started_at,
            ended_at=now_ts(),
            error=self.error,
        )


# ══════════════════════════════════════════════════════════════════════════════
# Silero VAD listener  (unchanged from original)
# ══════════════════════════════════════════════════════════════════════════════

def listen_for_utterance_with_silero_vad(input_device, silero_model, prompt_label="utterance"):
    input_sr   = get_input_samplerate(input_device)
    block_size = max(1, int(input_sr * 0.05))
    audio_q: queue.Queue[np.ndarray] = queue.Queue()
    vad_it = VADIterator(silero_model, threshold=SILERO_THRESHOLD,
                         sampling_rate=SILERO_SAMPLE_RATE,
                         min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
                         speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll, recorded = [], []
    is_recording, speech_started_at = False, None
    leftover = np.array([], dtype=np.float32)

    def cb(indata, frames, t, status): audio_q.put(indata[:,0].copy())

    print_ts(f"Listening for {prompt_label}. Speak when ready.")
    try:
        sd.check_input_settings(device=input_device, samplerate=input_sr, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sr, channels=1, dtype="float32",
                            device=input_device, blocksize=block_size, callback=cb):
            while True:
                try: block = audio_q.get(timeout=0.1)
                except queue.Empty: continue
                b16k     = resample_audio(block, input_sr, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover, b16k]).astype(np.float32, copy=False)
                usable   = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable == 0: leftover = combined; continue
                chunks  = combined[:usable].reshape(-1, SILERO_CHUNK_SIZE)
                leftover = combined[usable:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll.append(chunk.copy())
                        if len(pre_roll) > pre_roll_max: pre_roll.pop(0)
                    else:
                        recorded.append(chunk.copy())
                    ev  = vad_it(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if ev:
                        if "start" in ev and not is_recording:
                            is_recording = True; speech_started_at = now
                            recorded = list(pre_roll); recorded.append(chunk.copy()); pre_roll.clear()
                            print_ts("Speech detected.")
                        if "end" in ev and is_recording:
                            if now - (speech_started_at or now) >= VAD_MIN_UTTERANCE_SECONDS:
                                raise StopIteration
                    if is_recording and speech_started_at and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        raise StopIteration
    except StopIteration: pass
    except KeyboardInterrupt: raise
    except Exception as exc: print_ts(f"VAD error: {exc}"); return None
    finally:
        try: vad_it.reset_states()
        except Exception: pass
    if not recorded: return None
    return save_audio_to_temp_wav(np.concatenate(recorded).astype(np.float32, copy=False))


def listen_for_utterance_with_silero_vad_and_face_emotion(
    input_device, silero_model, vision_client,
    camera_device=CAMERA_DEVICE, prompt_label="utterance",
) -> Tuple[Optional[str], Optional[FaceEmotionCapture]]:
    input_sr   = get_input_samplerate(input_device)
    block_size = max(1, int(input_sr * 0.05))
    audio_q: queue.Queue[np.ndarray] = queue.Queue()
    vad_it = VADIterator(silero_model, threshold=SILERO_THRESHOLD,
                         sampling_rate=SILERO_SAMPLE_RATE,
                         min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
                         speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll, recorded = [], []
    is_recording, speech_started_at = False, None
    leftover = np.array([], dtype=np.float32)
    face_sampler: Optional[FaceEmotionSampler] = None
    face_capture: Optional[FaceEmotionCapture] = None

    def cb(indata, frames, t, status): audio_q.put(indata[:,0].copy())

    print_ts(f"Listening for {prompt_label}. Speak when ready.")
    try:
        sd.check_input_settings(device=input_device, samplerate=input_sr, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sr, channels=1, dtype="float32",
                            device=input_device, blocksize=block_size, callback=cb):
            while True:
                try: block = audio_q.get(timeout=0.1)
                except queue.Empty:
                    if face_sampler: face_sampler.sample_if_due()
                    continue
                b16k     = resample_audio(block, input_sr, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover, b16k]).astype(np.float32, copy=False)
                usable   = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable == 0: leftover = combined; continue
                chunks   = combined[:usable].reshape(-1, SILERO_CHUNK_SIZE)
                leftover = combined[usable:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll.append(chunk.copy())
                        if len(pre_roll) > pre_roll_max: pre_roll.pop(0)
                    else:
                        recorded.append(chunk.copy())
                        if face_sampler: face_sampler.sample_if_due()
                    ev  = vad_it(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if ev:
                        if "start" in ev and not is_recording:
                            is_recording = True; speech_started_at = now
                            recorded = list(pre_roll); recorded.append(chunk.copy()); pre_roll.clear()
                            print_ts("Speech detected. Starting facial capture...")
                            face_sampler = FaceEmotionSampler(camera_device=camera_device, vision_client=vision_client)
                            face_sampler.start()
                            face_sampler.sample_if_due()
                        if "end" in ev and is_recording:
                            if now - (speech_started_at or now) >= VAD_MIN_UTTERANCE_SECONDS:
                                raise StopIteration
                    if is_recording and speech_started_at and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        raise StopIteration
    except StopIteration: pass
    except KeyboardInterrupt: raise
    except Exception as exc: print_ts(f"VAD/camera error: {exc}"); return None, face_capture
    finally:
        if face_sampler: face_capture = face_sampler.finish()
        try: vad_it.reset_states()
        except Exception: pass
    if not recorded: return None, face_capture
    return save_audio_to_temp_wav(np.concatenate(recorded).astype(np.float32, copy=False)), face_capture


# ══════════════════════════════════════════════════════════════════════════════
# Name-handling helpers  (unchanged from original)
# ══════════════════════════════════════════════════════════════════════════════

def ask_user_to_spell_name(whisper_model, silero_model, input_device=INPUT_DEVICE):
    print_ts("Please spell your name letter by letter. For example: L E T I C I A.")
    wav_path = listen_for_utterance_with_silero_vad(input_device, silero_model, "spelled name")
    if not wav_path: return None
    try:
        transcript = transcribe_with_confidence(wav_path, whisper_model).text
    finally:
        try: os.remove(wav_path)
        except OSError: pass
    print_ts(f"Spelling transcript: {transcript}")
    return clean_spelled_name(transcript)

def generate_introduction_response(client, user_name) -> str:
    system = f"""
You are Ameca, a humanoid social robot.
A new user just introduced themselves. Greet them warmly in 1-2 short sentences.
Use their name. End with exactly one emoji: 🙂. Do not sound robotic.
""".strip()
    try:
        resp = client.chat(model=MODEL_NAME,
            messages=[{"role":"system","content":system},{"role":"user","content":f"My name is {user_name}"}],
            options={"temperature":0.5,"num_predict":60,"num_ctx":1024}, stream=False)
        return normalize_reply(resp["message"]["content"], "trust")
    except Exception:
        return f"Hello {user_name}, I am Ameca. It is nice to meet you. 🙂"

def prompt_for_user_name(client, whisper_model, silero_model, input_device=INPUT_DEVICE):
    users, spoken_name = load_users(), ""
    for _ in range(2):
        print_ts("Please say your name.")
        wav = listen_for_utterance_with_silero_vad(input_device, silero_model, "name")
        if wav:
            try: spoken_name = transcribe_with_confidence(wav, whisper_model).text.strip()
            finally:
                try: os.remove(wav)
                except OSError: pass
        extracted = extract_name_from_text(spoken_name)
        spoken_name = extracted or clean_spoken_name(spoken_name)
        if spoken_name and not looks_like_invalid_name(spoken_name): break
        print_ts(f"'{spoken_name or 'nothing'}' does not sound like a name.")
    if not spoken_name or looks_like_invalid_name(spoken_name): spoken_name = "Guest"
    spelled = ask_user_to_spell_name(whisper_model, silero_model, input_device)
    if spelled: spoken_name = spelled
    user_key  = slugify_name(spoken_name)
    is_new    = user_key not in users
    if is_new:
        users[user_key] = {"name": spoken_name, "created_at": now_ts(),
                           "last_seen": now_ts(), "session_files": [], "conversation_summary": ""}
    else:
        users[user_key]["last_seen"] = now_ts()
    save_users(users)
    print_ts(f"{'Nice to meet you' if is_new else 'Welcome back'}, {users[user_key]['name']}.")
    intro = generate_introduction_response(client, users[user_key]["name"])
    print_ts(f"Assistant: {intro}")
    return user_key, users[user_key], intro


# ══════════════════════════════════════════════════════════════════════════════
# JSON helpers
# ══════════════════════════════════════════════════════════════════════════════

def safe_json_extract(text: str) -> Optional[dict]:
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip(), flags=re.IGNORECASE|re.DOTALL).strip()
    try: return json.loads(text)
    except json.JSONDecodeError: pass
    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)
    if not match: return None
    try: return json.loads(match.group(0))
    except json.JSONDecodeError: return None


# ══════════════════════════════════════════════════════════════════════════════
# Legacy single-label emotion detection  (kept for fallback / compat)
# ══════════════════════════════════════════════════════════════════════════════

def simple_emotion_fallback(transcribed_text: str) -> Optional[EmotionResult]:
    text = transcribed_text.strip().lower()
    greetings = {"hello","hi","hey","good morning","good afternoon","good evening"}
    farewells  = {"bye","goodbye","see you","see you later","talk later","have a good day","have a nice day"}
    if text.rstrip(".!?") in greetings:
        return EmotionResult("trust", 0.6, "Friendly social opening.")
    if any(p in text for p in farewells):
        return EmotionResult("trust", 0.7, "Polite farewell.")
    if any(p in text for p in ["today's date","todays date","what is the date"]):
        return EmotionResult("anticipation", 0.5, "User requesting date information.")
    return None

def detect_emotion(client, transcribed_text, facial_emotion_hint=None) -> EmotionResult:
    """Legacy single-label fallback. Use build_linguistic_modal for fusion pipeline."""
    fallback = simple_emotion_fallback(transcribed_text)
    if fallback: return fallback
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    facial_s = f"Facial hint: {facial_emotion_hint}\n" if facial_emotion_hint else ""
    prompt = f"""
Classify the user's emotion. Return JSON:
{{"emotion": "one of: {emotions}", "confidence": 0.0, "reason": "explanation"}}

Rules: confidence 0-1. For greetings → trust. For farewells → trust. No markdown.
User text: {transcribed_text}
{facial_s}""".strip()
    try:
        resp = client.chat(model=MODEL_NAME, format="json",
            messages=[{"role":"system","content":"Return valid JSON only."},
                      {"role":"user","content":prompt}],
            options={"temperature":0.1,"num_predict":120,"num_ctx":2048}, stream=False)
        data = safe_json_extract(resp["message"]["content"])
        if not data: return EmotionResult("trust", 0.3, "Parse failure fallback.")
        emotion = str(data.get("emotion","")).strip().lower()
        if emotion not in PLUTCHIK_EMOTIONS: emotion = "trust"
        return EmotionResult(emotion, max(0.0, min(1.0, float(data.get("confidence",0.0)))),
                             str(data.get("reason","")))
    except Exception:
        return EmotionResult("trust", 0.3, "LLM error fallback.")


# ══════════════════════════════════════════════════════════════════════════════
# Emoji / reply normalisation  (unchanged)
# ══════════════════════════════════════════════════════════════════════════════

def remove_all_emojis_except_allowed_faces(text):
    result = []
    for char in text:
        if char in ALLOWED_FACE_EMOJIS: result.append(char); continue
        code = ord(char)
        if (0x1F300 <= code <= 0x1FAFF or 0x2600 <= code <= 0x27BF or code in {0x200D, 0xFE0F}):
            continue
        result.append(char)
    return "".join(result)

def normalize_reply(raw_reply, emotion) -> str:
    required_emoji = PLUTCHIK_EMOTIONS[emotion]
    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = "".join(c for c in cleaned if c not in ALLOWED_FACE_EMOJIS)
    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)
    if not cleaned: cleaned = "I'm here with you."
    return f"{cleaned} {required_emoji}"


# ══════════════════════════════════════════════════════════════════════════════
# Date / time helpers and response generation  (unchanged)
# ══════════════════════════════════════════════════════════════════════════════

def runtime_context() -> str:
    return f"RUNTIME CONTEXT\nCurrent local date and time: {now_ts()}."

def deterministic_reply_if_applicable(user_text, emotion) -> Optional[str]:
    text  = user_text.strip().lower()
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")
    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"
    if "what is the time" in text or "what time is it" in text or "current time" in text:
        return f"The current time is {datetime.now().strftime('%H:%M')}. {emoji}"
    farewells = {"bye","goodbye","see you","see you later","talk later","have a nice day","have a good day"}
    if any(p in text for p in farewells): return "Thank you, and take care. 🙂"
    return None

def build_response_system_prompt(emotion_result, user_profile=None, face_emotion_json=None, fusion_json=None) -> str:
    memory_ctx = build_user_memory_context(user_profile)
    if face_emotion_json is None: face_emotion_json = default_face_emotion_json()
    text_emo = {"emotion": emotion_result.emotion, "confidence": emotion_result.confidence, "reason": emotion_result.reason}
    fusion_section = f"\nFusion state:\n{json.dumps(fusion_json, indent=2)}\n" if fusion_json else ""
    return f"""
{AMECA_SYSTEM_PROMPT}

{runtime_context()}

{memory_ctx}

PRIVATE EMOTION CONTEXT (use only for tone; do not mention to user)
Text/LLM emotion:
{json.dumps(text_emo, indent=2)}

Face/Qwen2.5-VL emotion:
{json.dumps(face_emotion_json, indent=2)}
{fusion_section}
Interpretation: text signal is primary; face signal is secondary. If they conflict, trust text.
Do not mention camera, VLM, facial analysis, fusion, or emotion labels to the user.

Return JSON only:
{{"reply": "response without emoji", "emoji": "one facial emoji", "tone": "short label"}}

Rules:
- 1-2 short sentences unless user asks for detail.
- No markdown, bullets, or numbered lists unless asked.
- Occasional name use, not every response.
- Never begin with "As Ameca" or reintroduce yourself unprompted.
- End with exactly one emoji from: 🙂 😊 😌 😔 😟 🤔 😮 😢 😠 🤢
""".strip()

def generate_response(client, user_text, emotion_result, history, user_profile=None, face_emotion_json=None, fusion_json=None) -> str:
    det = deterministic_reply_if_applicable(user_text, emotion_result.emotion)
    if det: return det
    system_prompt = build_response_system_prompt(emotion_result, user_profile, face_emotion_json, fusion_json)
    messages = [{"role":"system","content":system_prompt[:6000]},
                *[{"role":i["role"],"content":i["content"]} for i in history[-6:]],
                {"role":"user","content":user_text[:1500]}]
    resp = client.chat(model=MODEL_NAME, messages=messages,
        options={"temperature":0.4,"num_predict":120,"repeat_penalty":1.25,"num_ctx":2048},
        stream=False)
    raw  = resp["message"]["content"]
    data = safe_json_extract(raw)
    if data and isinstance(data, dict):
        reply_text = str(data.get("reply","")).strip()
        emoji      = str(data.get("emoji","")).strip()
        if emoji in {":)",":-)",""}: emoji = PLUTCHIK_EMOTIONS.get(emotion_result.emotion,"🙂")
        return normalize_reply(f"{reply_text} {emoji}", emotion_result.emotion)
    return normalize_reply(raw, emotion_result.emotion)

def trim_history(history): return history[-MAX_HISTORY_MESSAGES:]


# ══════════════════════════════════════════════════════════════════════════════
# Main loop
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print_ts("Ameca HRI prototype — Adaptive Reliability-Aware Late Fusion")
    print_ts(f"Fusion: gate_threshold={FUSION_GATE_THRESHOLD}, modalities=[linguistic, acoustic, visual]")
    print_ts(f"Acoustic modality: {'ENABLED (librosa)' if LIBROSA_AVAILABLE else 'DISABLED (install librosa)'}")
    print_ts(f"Ollama host: {OLLAMA_HOST}  |  Chat: {MODEL_NAME}  |  Vision: {VISION_MODEL_NAME}")
    print()

    ensure_data_dirs()
    check_ollama_available()
    ensure_model_available(MODEL_NAME)
    ensure_model_available(VISION_MODEL_NAME)

    client = Client(host=OLLAMA_HOST)
    list_input_devices()

    print_ts("Loading Silero VAD...")
    silero_model = load_silero_vad()
    print_ts("Silero VAD ready.")

    print_ts("Loading faster-whisper...")
    whisper_model = WhisperModel(
        FAST_WHISPER_CONFIG["model"],
        device=FAST_WHISPER_CONFIG["device"],
        compute_type=FAST_WHISPER_CONFIG["compute_type"],
    )
    print_ts("faster-whisper ready.")

    user_key, user_profile, intro_reply = prompt_for_user_name(
        client=client, whisper_model=whisper_model,
        silero_model=silero_model, input_device=INPUT_DEVICE,
    )

    if user_profile.get("conversation_summary"):
        print_ts("Loaded previous conversation memory.")

    print()
    print("Adaptive reliability-aware fusion active: linguistic + acoustic + visual.")
    print("Speak naturally. Say '/exit' or press Ctrl+C to save and quit.")
    print()

    history: list[dict]     = []
    session_log: list[dict] = []

    session_log.append({"role":"assistant","content":intro_reply,"timestamp":now_ts(),"intent":"self_introduction"})
    history.append({"role":"assistant","content":intro_reply})

    try:
        while True:
            # ── 1. Capture audio + visual simultaneously ───────────────────
            wav_path, face_capture = listen_for_utterance_with_silero_vad_and_face_emotion(
                input_device=INPUT_DEVICE, silero_model=silero_model,
                vision_client=client, camera_device=CAMERA_DEVICE, prompt_label="utterance",
            )

            if face_capture:
                if face_capture.error:
                    print_ts(f"Face capture error: {face_capture.error}")
                else:
                    print_ts(f"Face summary: {face_capture.summary_text}")

            if not wav_path:
                continue

            # ── 2. Transcribe with word-level confidence ───────────────────
            try:
                transcription = transcribe_with_confidence(wav_path, whisper_model)
            finally:
                # Extract prosody BEFORE deleting the wav file
                acoustic_modal = build_acoustic_modal(wav_path)
                try: os.remove(wav_path)
                except OSError: pass

            user_text = transcription.text
            if not user_text:
                print_ts("No speech detected after transcription.")
                continue

            print_ts(f"Transcript: {user_text}")
            print_ts(
                f"ASR quality: words={len(user_text.split())}, "
                f"word_conf_samples={len(transcription.word_confidences)}, "
                f"no_speech={transcription.no_speech_prob:.3f}"
            )

            # ── 3. Name detection (early return) ──────────────────────────
            maybe_name = extract_name_from_text(user_text)
            if maybe_name and not looks_like_invalid_name(maybe_name):
                user_key, user_profile = rename_current_user(user_key, user_profile, maybe_name)
                reply = generate_introduction_response(client, user_profile["name"])
                print_ts(f"Assistant: {reply}")
                history.append({"role":"user","content":user_text})
                history.append({"role":"assistant","content":reply})
                history = trim_history(history)
                session_log += [
                    {"role":"user","content":user_text,"timestamp":now_ts(),"intent":"name_introduction"},
                    {"role":"assistant","content":reply,"timestamp":now_ts()},
                ]
                continue

            # ── 4. Command detection ──────────────────────────────────────
            command = normalize_command(user_text)
            if command in {"exit","quit"}:
                print_ts("Goodbye.")
                break
            if command == "clear":
                history.clear(); print_ts("History cleared."); continue

            # ── 5. Build per-modality emotion results ─────────────────────
            facial_hint = face_capture.summary_text if face_capture else None

            linguistic_modal = build_linguistic_modal(
                client=client, transcription=transcription, facial_hint=facial_hint)

            # acoustic_modal was computed before wav deletion (above)

            visual_modal = build_visual_modal(face_capture)

            # ── 6. Adaptive Reliability-Aware Late Fusion ─────────────────
            fused = adaptive_reliability_fusion(
                linguistic=linguistic_modal,
                acoustic=acoustic_modal,
                visual=visual_modal,
            )
            emotion_result = fused_to_emotion_result(fused)
            fusion_json    = fused_to_session_json(fused)

            print_ts("Fusion result JSON:")
            print(json.dumps(fusion_json, indent=2))
            print()

            face_emotion_json = face_capture.as_json if face_capture else default_face_emotion_json()

            # ── 7. Generate response ──────────────────────────────────────
            reply = generate_response(
                client=client, user_text=user_text,
                emotion_result=emotion_result, history=history,
                user_profile=user_profile,
                face_emotion_json=face_emotion_json,
                fusion_json=fusion_json,
            )
            print_ts(f"Assistant: {reply}")
            print()

            # ── 8. Log to history and session transcript ──────────────────
            history.append({"role":"user","content":user_text})
            history.append({"role":"assistant","content":reply})
            history = trim_history(history)

            session_log.append({
                "role":           "user",
                "content":        user_text,
                "timestamp":      now_ts(),
                "input_mode":     "silero_vad_faster_whisper_qwen25vl",
                "fusion":         fusion_json,
                "facial_hint":    facial_hint,
                "face_emotion":   face_emotion_json,
            })
            session_log.append({
                "role":      "assistant",
                "content":   reply,
                "timestamp": now_ts(),
            })

    except KeyboardInterrupt:
        print()
        print_ts("Shutting down.")

    finally:
        if session_log:
            session_path = save_session_transcript(user_key, user_profile, session_log)
            update_user_after_session(client, user_key, session_path, session_log)
            print_ts(f"Transcript saved to: {session_path}")
        else:
            print_ts("No messages to save.")


if __name__ == "__main__":
    main()