from __future__ import annotations

import base64
import json
import os
import queue
import re
import sys
import tempfile
import subprocess
import threading
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Tuple

# Linux-only Qt fix. Do not force this on macOS.
if sys.platform.startswith("linux"):
    os.environ.setdefault("QT_QPA_PLATFORM", "xcb")

# Harmless on non-Windows; prevents some OpenCV backend priority issues on Windows.
os.environ.setdefault("OPENCV_VIDEOIO_PRIORITY_MSMF", "0")

import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf
import torch
from faster_whisper import WhisperModel
from ollama import Client
from silero_vad import load_silero_vad, VADIterator
import platform

IS_MAC = platform.system() == "Darwin"
IS_LINUX = platform.system() == "Linux"

# =========================
# Runtime profile
# =========================

# MacBook camera is normally 0.
# ZED 2 on the school Linux PC often exposes stereo video as /dev/video0.
# /dev/video1 may fail depending on permissions/backend, so default to 0 on Linux.
CAMERA_DEVICE: Optional[int] = 0 if IS_LINUX else 0

# ZED gives a side-by-side stereo frame. Use only one eye, otherwise the preview looks duplicated.
USE_ZED_HALF_FRAME_CROP = IS_LINUX
ZED_EYE = "left"  # "left" or "right"

# Higher ZED stereo resolution. 2560x720 means each cropped eye becomes 1280x720.
# Good balance for ZED preview and VLM image input. Use 3840x1080 only if your machine handles it smoothly.
CAMERA_FRAME_WIDTH = 2560 if IS_LINUX else 1280
CAMERA_FRAME_HEIGHT = 720 if IS_LINUX else 720
CAMERA_PREVIEW_ENABLED = True
CAMERA_PREVIEW_WINDOW_NAME = "Camera Preview - press q to close preview"
CAMERA_SAMPLE_EVERY_SECONDS = 0.8
CAMERA_WARMUP_SECONDS = 0.35

# VLM face emotion settings.
VISION_OLLAMA_HOST = os.environ.get("VISION_OLLAMA_HOST", "http://127.0.0.1:11434")
VISION_MODEL_NAME = os.environ.get("VISION_MODEL", "llama3.2-vision:11b")
VISION_IMAGE_JPEG_QUALITY = int(os.environ.get("VISION_IMAGE_JPEG_QUALITY", "85"))
VISION_REQUEST_TIMEOUT_SECONDS = float(os.environ.get("VISION_REQUEST_TIMEOUT_SECONDS", "20"))
VISION_MAX_FRAMES_PER_UTTERANCE = int(os.environ.get("VISION_MAX_FRAMES_PER_UTTERANCE", "1"))

# Reliability filter. VLM emotion scores are percentages.
FACE_MIN_TOP_SCORE = 45.0
FACE_MIN_MARGIN = 15.0

# =========================
# Ollama configuration
# =========================

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434")
MODEL_NAME = os.environ.get("OLLAMA_MODEL", "llama3:8b")

# If your lab uses rrlab-ollama, set this to False to avoid local pulls.
ALLOW_LOCAL_MODEL_PULL = False

# =========================
# Persistent memory / transcript configuration
# =========================

DATA_DIR = "conversation_data"
USERS_FILE = os.path.join(DATA_DIR, "users.json")
SESSIONS_DIR = os.path.join(DATA_DIR, "sessions")
ENABLE_LLM_SESSION_SUMMARY = False

# =========================
# Ameca identity prompt
# =========================

AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information such as passwords, medical data, financial information, or private identity documents.
Treat the conversation as ephemeral in speech, but save only the local JSON transcript for this prototype when the session ends.

USER ADAPTATION
Use clear, simple explanations.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""

# =========================
# faster-whisper configuration
# =========================

FAST_WHISPER_CONFIG = {
    "profile": os.environ.get("AMECA_PROFILE", "school_gpu"),
    "model": os.environ.get("WHISPER_MODEL", "small"),
    "device": os.environ.get("WHISPER_DEVICE", "cuda"),
    "compute_type": os.environ.get("WHISPER_COMPUTE_TYPE", "float16"),
    "language": "en",
    "beam_size": 1,
    "vad_filter": False,
}

# =========================
# Audio / Silero VAD configuration
# =========================

TARGET_SAMPLE_RATE = 16000
INPUT_DEVICE: Optional[int] = None
SILERO_SAMPLE_RATE = 16000
SILERO_CHUNK_SIZE = 512
SILERO_THRESHOLD = 0.55
SILERO_MIN_SILENCE_DURATION_MS = 700
SILERO_SPEECH_PAD_MS = 250
VAD_MAX_UTTERANCE_SECONDS = 15.0
VAD_MIN_UTTERANCE_SECONDS = 0.60
VAD_PRE_ROLL_SECONDS = 0.35
MIN_PEAK_THRESHOLD = 0.01
MIN_RMS_THRESHOLD = 0.003

# =========================
# Emotion / fusion configuration
# =========================

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy": "😊",
    "trust": "🙂",
    "fear": "😨",
    "surprise": "😮",
    "sadness": "😢",
    "disgust": "🤢",
    "anger": "😠",
    "anticipation": "🤔",
}

ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())
TEXT_WEIGHT = 0.65
FACE_WEIGHT = 0.35


@dataclass
class EmotionResult:
    emotion: str
    confidence: float
    reason: str


@dataclass
class FaceEmotionCapture:
    emotion_score_samples: list[dict[str, float]]
    vlm_result_samples: list[dict]
    frame_count: int
    sampled_frame_count: int
    started_at: str
    ended_at: str
    error: Optional[str] = None

    @property
    def averaged_scores(self) -> dict[str, float]:
        if not self.emotion_score_samples:
            return {}
        totals: dict[str, float] = {}
        for sample in self.emotion_score_samples:
            for emotion, score in sample.items():
                totals[emotion] = totals.get(emotion, 0.0) + float(score)
        count = len(self.emotion_score_samples)
        return {emotion: total / count for emotion, total in totals.items()}

    @property
    def dominant_emotion(self) -> Optional[str]:
        scores = self.averaged_scores
        if not scores:
            return None
        return max(scores.items(), key=lambda item: item[1])[0]

    @property
    def mapped_plutchik_emotion(self) -> Optional[str]:
        dominant = self.dominant_emotion
        if not dominant:
            return None
        return dominant if dominant in PLUTCHIK_EMOTIONS else None

    @property
    def confidence(self) -> float:
        scores = self.averaged_scores
        dominant = self.dominant_emotion
        if not scores or not dominant:
            return 0.0
        return max(0.0, min(1.0, float(scores[dominant]) / 100.0))

    @property
    def is_reliable(self) -> bool:
        scores = self.averaged_scores
        if not scores:
            return False
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        top_score = ordered[0][1]
        second_score = ordered[1][1] if len(ordered) > 1 else 0.0
        return top_score >= FACE_MIN_TOP_SCORE and (top_score - second_score) >= FACE_MIN_MARGIN

    @property
    def summary_text(self) -> str:
        if self.error:
            return f"No VLM facial-expression hint available because: {self.error}"
        scores = self.averaged_scores
        if not scores:
            return "No reliable VLM facial-expression hint was captured during speech."
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        if not self.is_reliable:
            top_parts = [f"{emo}={score:.0f}%" for emo, score in ordered[:3]]
            return f"VLM facial-expression hint was weak or mixed; top_signals=({', '.join(top_parts)}); samples={self.sampled_frame_count}"
        parts = [f"{emo}={score:.0f}%" for emo, score in ordered if score >= 5.0]
        return f"dominant={self.dominant_emotion}; mapped_plutchik={self.mapped_plutchik_emotion}; averaged_scores=({', '.join(parts)}); samples={self.sampled_frame_count}"

    @property
    def as_json(self) -> dict:
        scores = self.averaged_scores
        return {
            "available": self.error is None and bool(scores),
            "reliable": self.is_reliable,
            "backend": "Ollama vision model",
            "host": VISION_OLLAMA_HOST,
            "model": VISION_MODEL_NAME,
            "dominant_emotion": self.dominant_emotion,
            "mapped_plutchik_emotion": self.mapped_plutchik_emotion,
            "confidence": self.confidence,
            "averaged_scores": scores,
            "vlm_result_samples": self.vlm_result_samples,
            "frame_count": self.frame_count,
            "sampled_frame_count": self.sampled_frame_count,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "error": self.error,
            "note": "VLM facial-expression analysis is a secondary signal. Fusion combines it with text emotion.",
        }


# =========================
# Timestamp / misc helpers
# =========================

def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")


def normalize_command(text: str) -> Optional[str]:
    stripped = text.strip().lower()
    if not stripped.startswith(("/", "\\")):
        return None
    return re.sub(r"^[\\/]+", "", stripped)


def ensure_data_dirs() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(SESSIONS_DIR, exist_ok=True)


def slugify_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    return name.strip("_") or "unknown_user"


def load_users() -> dict:
    ensure_data_dirs()
    if not os.path.exists(USERS_FILE):
        return {}
    try:
        with open(USERS_FILE, "r", encoding="utf-8") as file:
            return json.load(file)
    except json.JSONDecodeError:
        return {}


def save_users(users: dict) -> None:
    ensure_data_dirs()
    with open(USERS_FILE, "w", encoding="utf-8") as file:
        json.dump(users, file, indent=2, ensure_ascii=False)


def clean_spoken_name(spoken_name: str) -> str:
    spoken_name = spoken_name.strip()
    patterns = [
        r"^my name is\s+", r"^my name's\s+", r"^i am\s+", r"^i'm\s+",
        r"^this is\s+", r"^it is\s+", r"^it's\s+", r"^call me\s+",
    ]
    for pattern in patterns:
        spoken_name = re.sub(pattern, "", spoken_name, flags=re.IGNORECASE).strip()
    spoken_name = re.sub(r"[^a-zA-Z0-9\s\-]", "", spoken_name)
    return spoken_name[:40].strip() or "Guest"


def clean_spelled_name(text: str) -> Optional[str]:
    text = text.upper().strip()
    text = re.sub(r"\bMY NAME IS\b|\bIT IS\b|\bIT'S\b|\bSPELL(?:ED|ING)?\b", "", text)
    text = re.sub(r"[^A-Z\s]", " ", text)
    letters = [part for part in text.split() if len(part) == 1 and part.isalpha()]
    if len(letters) >= 2:
        return "".join(letters).title()
    return None


def extract_name_from_text(text: str) -> Optional[str]:
    text = text.strip()
    patterns = [
        r"\bmy name is\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bmy name's\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bcall me\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            candidate = clean_spoken_name(match.group(1))
            if 1 <= len(candidate.split()) <= 4:
                return candidate
    return None


def looks_like_invalid_name(name: str) -> bool:
    invalid = {"hello", "hi", "hey", "yes", "no", "okay", "ok", "thanks", "thank you", "bye", "goodbye"}
    return name.strip().lower() in invalid


def build_user_memory_context(user_profile: Optional[dict]) -> str:
    if not user_profile:
        return ""
    name = user_profile.get("name", "the user")
    summary = user_profile.get("conversation_summary", "").strip() or "No previous conversation summary is available."
    return f"""
USER MEMORY CONTEXT
The user's name is {name}.
Previous conversation summary:
{summary}
Rules:
- Use the user's name naturally when appropriate.
- Do not claim to remember anything beyond this saved local JSON context.
""".strip()


# =========================
# Ollama setup
# =========================

def check_ollama_available(host: str = OLLAMA_HOST, label: str = "Ollama", max_attempts: int = 10, delay_seconds: float = 1.0) -> None:
    client = Client(host=host)
    for attempt in range(1, max_attempts + 1):
        try:
            client.list()
            print_ts(f"{label} is reachable at {host}.")
            return
        except Exception as exc:
            print_ts(f"{label} not reachable yet, attempt {attempt}/{max_attempts}: {exc}")
            time.sleep(delay_seconds)
    raise RuntimeError(f"Could not connect to {label} at {host} after {max_attempts} attempts.")


def ensure_model_available(model_name: str = MODEL_NAME, host: str = OLLAMA_HOST) -> None:
    if not ALLOW_LOCAL_MODEL_PULL:
        print_ts(f"Using Ollama model '{model_name}' from {host}. Skipping local pull.")
        return
    if not host.startswith("http://127.0.0.1") and not host.startswith("http://localhost"):
        print_ts(f"Remote Ollama host {host}; skipping local CLI pull for {model_name}.")
        return
    result = subprocess.run(["ollama", "list"], capture_output=True, text=True, check=False)
    if model_name not in result.stdout:
        print_ts(f"Model {model_name} not found locally. Pulling it now...")
        subprocess.run(["ollama", "pull", model_name], check=True)


# =========================
# Audio helpers
# =========================

def list_input_devices() -> None:
    print("\nAvailable input devices:")
    try:
        devices = sd.query_devices()
        hostapis = sd.query_hostapis()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return
    found = False
    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            found = True
            hostapi_name = hostapis[device["hostapi"]]["name"]
            print(f"[mic {idx}] {device['name']} | hostapi={hostapi_name} | inputs={device['max_input_channels']} | default_sr={device['default_samplerate']}")
    if not found:
        print("No input devices found.")
    print(f"\nCurrent default audio device: {sd.default.device}\n")


def get_input_samplerate(input_device: Optional[int]) -> int:
    device_info = sd.query_devices(kind="input") if input_device is None else sd.query_devices(input_device)
    default_sr = int(round(device_info["default_samplerate"]))
    return default_sr if default_sr > 0 else TARGET_SAMPLE_RATE


def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32, copy=False)
    if audio.size == 0:
        return audio.astype(np.float32, copy=False)
    duration = len(audio) / original_sr
    target_length = max(1, int(round(duration * target_sr)))
    old_times = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_times = np.linspace(0.0, duration, num=target_length, endpoint=False)
    return np.interp(new_times, old_times, audio).astype(np.float32)


def save_audio_to_temp_wav(audio_16k: np.ndarray) -> Optional[str]:
    if audio_16k.size == 0:
        return None
    peak = float(np.max(np.abs(audio_16k)))
    rms = float(np.sqrt(np.mean(audio_16k ** 2)))
    print_ts(f"Captured utterance audio level: peak={peak:.4f}, rms={rms:.4f}")
    if peak < MIN_PEAK_THRESHOLD or rms < MIN_RMS_THRESHOLD:
        print("Captured audio was too quiet or silent.")
        return None
    audio_16k = np.clip(audio_16k * min(0.9 / max(peak, 1e-6), 10.0), -1.0, 1.0)
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        wav_path = tmp.name
    sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
    return wav_path


def transcribe_audio(wav_path: str, whisper_model: WhisperModel) -> str:
    segments, _info = whisper_model.transcribe(
        wav_path,
        language=FAST_WHISPER_CONFIG.get("language"),
        beam_size=int(FAST_WHISPER_CONFIG.get("beam_size", 1)),
        vad_filter=bool(FAST_WHISPER_CONFIG.get("vad_filter", False)),
        condition_on_previous_text=False,
    )
    text = " ".join(segment.text.strip() for segment in segments).strip()
    text = re.sub(r"\s+", " ", text).strip()
    return "" if len(text.split()) <= 1 and len(text) < 3 else text


# =========================
# Camera / ZED / VLM helpers
# =========================

def get_camera_backend() -> int:
    if sys.platform == "darwin":
        return cv2.CAP_AVFOUNDATION
    if sys.platform.startswith("linux"):
        return cv2.CAP_V4L2
    return cv2.CAP_ANY


def normalize_camera_frame(frame: np.ndarray) -> np.ndarray:
    if USE_ZED_HALF_FRAME_CROP:
        height, width = frame.shape[:2]
        half = width // 2
        if ZED_EYE.lower() == "right":
            frame = frame[:, half:]
        else:
            frame = frame[:, :half]
    return frame


def open_camera(camera_device: Optional[int]) -> cv2.VideoCapture:
    camera_index = 0 if camera_device is None else int(camera_device)
    cap = cv2.VideoCapture(camera_index, get_camera_backend())
    if cap.isOpened():
        # MJPG is usually needed for higher USB camera resolutions through OpenCV/V4L2.
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_FRAME_HEIGHT)
        cap.set(cv2.CAP_PROP_FPS, 30)
        cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
        actual_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        actual_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        print_ts(f"Using camera device /dev/video{camera_index} at {actual_w}x{actual_h}")
    return cap


def list_camera_devices(max_indices: int = 6) -> None:
    print("\nAvailable camera devices:")
    found = False
    for idx in range(max_indices):
        cap = open_camera(idx)
        try:
            if not cap.isOpened():
                continue
            ok, frame = cap.read()
            if ok and frame is not None:
                norm = normalize_camera_frame(frame)
                found = True
                print(f"[cam {idx}] raw={frame.shape[1]}x{frame.shape[0]} | normalized={norm.shape[1]}x{norm.shape[0]}")
        finally:
            cap.release()
    if not found:
        print("No camera devices found.")
    print()


def encode_frame_as_base64_jpeg(frame_bgr: np.ndarray) -> Optional[str]:
    frame_bgr = normalize_camera_frame(frame_bgr)
    encode_params = [int(cv2.IMWRITE_JPEG_QUALITY), int(VISION_IMAGE_JPEG_QUALITY)]
    ok, buffer = cv2.imencode(".jpg", frame_bgr, encode_params)
    if not ok:
        return None
    return base64.b64encode(buffer).decode("utf-8")


def build_vlm_face_emotion_prompt() -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    return f"""
You are a careful facial-expression emotion classifier for a human-robot interaction prototype.

Analyze only the visible human face expression in the image.
Map the expression to exactly one of Plutchik's 8 primary emotions:
{emotions}

Return JSON only in this exact schema:
{{
  "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation",
  "confidence": 0.0,
  "reason": "brief visual evidence from the facial expression",
  "face_visible": true,
  "uncertainty": "brief note about blur, angle, lighting, occlusion, or mixed expression"
}}

Rules:
- Use only the facial expression. Do not use clothing, background, identity, age, gender, race, or attractiveness.
- Do not identify the person.
- If no clear face is visible, set face_visible=false, emotion="trust", confidence=0.0, and explain why.
- confidence must be between 0.0 and 1.0.
- Keep the reason short and cautious.
- Do not add markdown or text outside JSON.
""".strip()


def normalize_vlm_face_emotion_result(raw_data: Optional[dict]) -> Optional[dict]:
    if not raw_data:
        return None
    emotion = str(raw_data.get("emotion", "")).strip().lower()
    if emotion not in PLUTCHIK_EMOTIONS:
        emotion = "trust"
    try:
        confidence = float(raw_data.get("confidence", 0.0))
    except Exception:
        confidence = 0.0
    confidence = max(0.0, min(1.0, confidence))
    face_visible = bool(raw_data.get("face_visible", confidence > 0.0))
    if not face_visible:
        confidence = 0.0
    return {
        "emotion": emotion,
        "confidence": confidence,
        "reason": str(raw_data.get("reason", "")).strip() or "VLM inferred emotion from facial expression.",
        "face_visible": face_visible,
        "uncertainty": str(raw_data.get("uncertainty", "")).strip(),
        "model": VISION_MODEL_NAME,
    }


def vlm_result_to_plutchik_scores(vlm_result: dict) -> dict[str, float]:
    scores = {emotion: 0.0 for emotion in PLUTCHIK_EMOTIONS}
    emotion = vlm_result.get("emotion")
    confidence = float(vlm_result.get("confidence", 0.0))
    if emotion in scores and bool(vlm_result.get("face_visible", True)):
        scores[emotion] = round(confidence * 100.0, 4)
    return scores


def analyze_image_b64_emotion_scores(image_b64: str, client: Client) -> Optional[tuple[dict[str, float], dict]]:
    if not image_b64:
        return None
    try:
        response = client.chat(
            model=VISION_MODEL_NAME,
            format="json",
            messages=[{"role": "user", "content": build_vlm_face_emotion_prompt(), "images": [image_b64]}],
            options={"temperature": 0.0, "num_predict": 120, "num_ctx": 2048},
            stream=False,
        )
        raw = response["message"]["content"]
        vlm_result = normalize_vlm_face_emotion_result(safe_json_extract(raw))
        if not vlm_result:
            return None
        return vlm_result_to_plutchik_scores(vlm_result), vlm_result
    except Exception as exc:
        print_ts(f"VLM face emotion analysis failed: {exc}")
        return None


def analyze_image_b64_emotion_scores_with_timeout(image_b64: str, client: Client, timeout_seconds: float = VISION_REQUEST_TIMEOUT_SECONDS) -> Optional[tuple[dict[str, float], dict]]:
    result_box: dict[str, Optional[tuple[dict[str, float], dict]]] = {"result": None}
    error_box: dict[str, Optional[BaseException]] = {"error": None}

    def worker() -> None:
        try:
            result_box["result"] = analyze_image_b64_emotion_scores(image_b64, client)
        except BaseException as exc:
            error_box["error"] = exc

    thread = threading.Thread(target=worker, daemon=True)
    thread.start()
    thread.join(timeout_seconds)
    if thread.is_alive():
        print_ts(f"VLM face emotion analysis timed out after {timeout_seconds:.1f}s. Skipping this visual sample.")
        return None
    if error_box["error"] is not None:
        print_ts(f"VLM face emotion analysis failed: {error_box['error']}")
        return None
    return result_box["result"]


class FaceEmotionSampler:
    def __init__(self, camera_device: Optional[int], client: Client) -> None:
        self.camera_device = camera_device
        self.client = client
        self.cap: Optional[cv2.VideoCapture] = None
        self.window_created = False
        self.started_at = now_ts()
        self.error: Optional[str] = None
        self.emotion_score_samples: list[dict[str, float]] = []
        self.vlm_result_samples: list[dict] = []
        self.frame_b64_samples: list[str] = []
        self.frame_count = 0
        self.sampled_frame_count = 0
        self.capture_start_time: Optional[float] = None
        self.last_sample_time = 0.0
        self.last_status = "warming up..."

    def start(self) -> None:
        self.started_at = now_ts()
        self.capture_start_time = time.time()
        self.cap = open_camera(self.camera_device)
        if not self.cap.isOpened():
            self.error = "Could not open camera. Try CAMERA_DEVICE=0 for ZED on Linux."
            self.cap.release()
            self.cap = None
            return
        if CAMERA_PREVIEW_ENABLED:
            try:
                cv2.namedWindow(CAMERA_PREVIEW_WINDOW_NAME, cv2.WINDOW_NORMAL)
                self.window_created = True
            except Exception as exc:
                self.error = f"Camera preview could not start: {exc}"

    def sample_if_due(self) -> None:
        if self.cap is None or self.capture_start_time is None:
            return
        ok, frame = self.cap.read()
        if not ok or frame is None:
            return
        self.frame_count += 1
        frame = normalize_camera_frame(frame)
        now = time.time()
        elapsed = now - self.capture_start_time
        if CAMERA_PREVIEW_ENABLED and self.window_created:
            try:
                preview_frame = frame.copy()
                cv2.putText(preview_frame, "Recording speech...", (20, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2, cv2.LINE_AA)
                cv2.putText(preview_frame, f"VLM: {self.last_status}", (20, 70), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)
                preview_frame = cv2.resize(preview_frame, (960, 540))
                cv2.imshow(CAMERA_PREVIEW_WINDOW_NAME, preview_frame)
                key = cv2.waitKey(1) & 0xFF
                if key == ord("q"):
                    cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME)
                    self.window_created = False
            except Exception as exc:
                self.error = f"Camera preview failed: {exc}"
        should_sample = elapsed >= CAMERA_WARMUP_SECONDS and now - self.last_sample_time >= CAMERA_SAMPLE_EVERY_SECONDS
        if not should_sample:
            return
        self.last_sample_time = now
        if len(self.frame_b64_samples) >= VISION_MAX_FRAMES_PER_UTTERANCE:
            self.last_status = "visual sample already captured"
            return
        image_b64 = encode_frame_as_base64_jpeg(frame)
        if image_b64:
            self.frame_b64_samples.append(image_b64)
            self.sampled_frame_count += 1
            self.last_status = "visual sample captured"
        else:
            self.last_status = "could not encode frame"

    def finish(self) -> FaceEmotionCapture:
        if self.cap is not None:
            self.cap.release()
            self.cap = None
        if self.window_created:
            try:
                cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME)
                cv2.waitKey(1)
            except Exception:
                pass
        if self.frame_b64_samples and not self.emotion_score_samples:
            print_ts(f"Analyzing {len(self.frame_b64_samples)} captured face sample(s) with {VISION_MODEL_NAME}...")
            for image_b64 in self.frame_b64_samples:
                analysis = analyze_image_b64_emotion_scores_with_timeout(image_b64, self.client)
                if analysis:
                    scores, vlm_result = analysis
                    self.emotion_score_samples.append(scores)
                    self.vlm_result_samples.append(vlm_result)
        return FaceEmotionCapture(
            emotion_score_samples=self.emotion_score_samples,
            vlm_result_samples=self.vlm_result_samples,
            frame_count=self.frame_count,
            sampled_frame_count=self.sampled_frame_count,
            started_at=self.started_at,
            ended_at=now_ts(),
            error=self.error,
        )


# =========================
# VAD listeners
# =========================

def listen_for_utterance_with_silero_vad(input_device: Optional[int], silero_model, prompt_label: str = "utterance") -> Optional[str]:
    input_sample_rate = get_input_samplerate(input_device)
    input_block_size = max(1, int(input_sample_rate * 0.05))
    audio_queue: queue.Queue[np.ndarray] = queue.Queue()
    vad_iterator = VADIterator(silero_model, threshold=SILERO_THRESHOLD, sampling_rate=SILERO_SAMPLE_RATE, min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS, speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max_chunks = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll_chunks: list[np.ndarray] = []
    recorded_chunks: list[np.ndarray] = []
    is_recording = False
    speech_started_at: Optional[float] = None
    leftover_16k = np.array([], dtype=np.float32)

    def audio_callback(indata, frames, callback_time, status) -> None:
        audio_queue.put(indata[:, 0].copy())

    print_ts(f"Listening automatically for {prompt_label}. Speak when ready. Press Ctrl+C to quit.")
    print_ts(f"Silero VAD settings: threshold={SILERO_THRESHOLD}, min_silence={SILERO_MIN_SILENCE_DURATION_MS}ms, max_utterance={VAD_MAX_UTTERANCE_SECONDS}s")

    try:
        sd.check_input_settings(device=input_device, samplerate=input_sample_rate, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sample_rate, channels=1, dtype="float32", device=input_device, blocksize=input_block_size, callback=audio_callback):
            while True:
                try:
                    block = audio_queue.get(timeout=0.1)
                except queue.Empty:
                    continue
                block_16k = resample_audio(block, input_sample_rate, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover_16k, block_16k]).astype(np.float32, copy=False)
                usable_len = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable_len == 0:
                    leftover_16k = combined
                    continue
                chunks = combined[:usable_len].reshape(-1, SILERO_CHUNK_SIZE)
                leftover_16k = combined[usable_len:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll_chunks.append(chunk.copy())
                        if len(pre_roll_chunks) > pre_roll_max_chunks:
                            pre_roll_chunks.pop(0)
                    else:
                        recorded_chunks.append(chunk.copy())
                    speech_event = vad_iterator(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if speech_event:
                        if "start" in speech_event and not is_recording:
                            is_recording = True
                            speech_started_at = now
                            recorded_chunks = list(pre_roll_chunks)
                            recorded_chunks.append(chunk.copy())
                            pre_roll_chunks.clear()
                            print()
                            print_ts("Speech detected. Recording utterance...")
                        if "end" in speech_event and is_recording:
                            utterance_duration = now - (speech_started_at or now)
                            if utterance_duration >= VAD_MIN_UTTERANCE_SECONDS:
                                print_ts("Speech ended. Processing utterance...")
                                raise StopIteration
                    if is_recording and speech_started_at is not None and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        print_ts("Maximum utterance length reached. Processing utterance...")
                        raise StopIteration
    except StopIteration:
        pass
    except KeyboardInterrupt:
        raise
    except Exception as exc:
        print_ts(f"Silero VAD/audio error: {exc}")
        return None
    finally:
        try:
            vad_iterator.reset_states()
        except Exception:
            pass
    if not recorded_chunks:
        return None
    return save_audio_to_temp_wav(np.concatenate(recorded_chunks).astype(np.float32, copy=False))


def listen_for_utterance_with_silero_vad_and_face_emotion(input_device: Optional[int], silero_model, client: Client, camera_device: Optional[int] = CAMERA_DEVICE, prompt_label: str = "utterance") -> Tuple[Optional[str], Optional[FaceEmotionCapture]]:
    input_sample_rate = get_input_samplerate(input_device)
    input_block_size = max(1, int(input_sample_rate * 0.05))
    audio_queue: queue.Queue[np.ndarray] = queue.Queue()
    vad_iterator = VADIterator(silero_model, threshold=SILERO_THRESHOLD, sampling_rate=SILERO_SAMPLE_RATE, min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS, speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max_chunks = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll_chunks: list[np.ndarray] = []
    recorded_chunks: list[np.ndarray] = []
    is_recording = False
    speech_started_at: Optional[float] = None
    leftover_16k = np.array([], dtype=np.float32)
    face_sampler: Optional[FaceEmotionSampler] = None
    face_capture: Optional[FaceEmotionCapture] = None

    def audio_callback(indata, frames, callback_time, status) -> None:
        audio_queue.put(indata[:, 0].copy())

    print_ts(f"Listening automatically for {prompt_label}. Speak when ready. Press Ctrl+C to quit.")
    print_ts(f"Silero VAD settings: threshold={SILERO_THRESHOLD}, min_silence={SILERO_MIN_SILENCE_DURATION_MS}ms, max_utterance={VAD_MAX_UTTERANCE_SECONDS}s")

    try:
        sd.check_input_settings(device=input_device, samplerate=input_sample_rate, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sample_rate, channels=1, dtype="float32", device=input_device, blocksize=input_block_size, callback=audio_callback):
            while True:
                try:
                    block = audio_queue.get(timeout=0.1)
                except queue.Empty:
                    if face_sampler is not None:
                        face_sampler.sample_if_due()
                    continue
                block_16k = resample_audio(block, input_sample_rate, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover_16k, block_16k]).astype(np.float32, copy=False)
                usable_len = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable_len == 0:
                    leftover_16k = combined
                    continue
                chunks = combined[:usable_len].reshape(-1, SILERO_CHUNK_SIZE)
                leftover_16k = combined[usable_len:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll_chunks.append(chunk.copy())
                        if len(pre_roll_chunks) > pre_roll_max_chunks:
                            pre_roll_chunks.pop(0)
                    else:
                        recorded_chunks.append(chunk.copy())
                        if face_sampler is not None:
                            face_sampler.sample_if_due()
                    speech_event = vad_iterator(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if speech_event:
                        if "start" in speech_event and not is_recording:
                            is_recording = True
                            speech_started_at = now
                            recorded_chunks = list(pre_roll_chunks)
                            recorded_chunks.append(chunk.copy())
                            pre_roll_chunks.clear()
                            print()
                            print_ts("Speech detected. Recording utterance and sampling facial expression...")
                            face_sampler = FaceEmotionSampler(camera_device=camera_device, client=client)
                            face_sampler.start()
                            face_sampler.sample_if_due()
                        if "end" in speech_event and is_recording:
                            utterance_duration = now - (speech_started_at or now)
                            if utterance_duration >= VAD_MIN_UTTERANCE_SECONDS:
                                print_ts("Speech ended. Processing utterance...")
                                raise StopIteration
                    if is_recording and speech_started_at is not None and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        print_ts("Maximum utterance length reached. Processing utterance...")
                        raise StopIteration
    except StopIteration:
        pass
    except KeyboardInterrupt:
        raise
    except Exception as exc:
        print_ts(f"Silero VAD/audio/camera error: {exc}")
        return None, face_capture
    finally:
        if face_sampler is not None:
            face_capture = face_sampler.finish()
        try:
            vad_iterator.reset_states()
        except Exception:
            pass
    if not recorded_chunks:
        return None, face_capture
    return save_audio_to_temp_wav(np.concatenate(recorded_chunks).astype(np.float32, copy=False)), face_capture


# =========================
# LLM / JSON helpers
# =========================

def safe_json_extract(text: str) -> Optional[dict]:
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE | re.DOTALL).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def build_emotion_prompt(transcribed_text: str, facial_emotion_hint: Optional[str] = None) -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    facial_section = f"Facial-expression hint captured during speech: {facial_emotion_hint}\n" if facial_emotion_hint else "No facial-expression hint was available.\n"
    return f"""
You are an emotion classification system for a human-robot interaction chat system.
Classify the user's emotional state from the text below.
Map the emotion to exactly one of Plutchik's 8 primary emotions: {emotions}

Use the user's words as the primary signal. Use the facial-expression hint only as weak supporting context.
Return JSON only in this exact schema:
{{
  "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation",
  "confidence": 0.0,
  "reason": "short explanation"
}}

Rules:
- confidence must be between 0.0 and 1.0
- choose one best emotion
- greetings usually map to trust
- farewells usually map to trust

User text:
{transcribed_text}

{facial_section}
""".strip()


def simple_emotion_fallback(transcribed_text: str) -> Optional[EmotionResult]:
    text = transcribed_text.strip().lower()
    greetings = {"hello", "hi", "hey", "good morning", "good afternoon", "good evening"}
    farewells = {"bye", "goodbye", "see you", "see you later", "talk later", "have a good day", "have a nice day"}
    if text.rstrip(".!?") in greetings:
        return EmotionResult("trust", 0.6, "The user is opening a friendly social interaction.")
    if any(phrase in text for phrase in farewells):
        return EmotionResult("trust", 0.7, "The user is closing the conversation politely.")
    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return EmotionResult("anticipation", 0.5, "The user is asking for current date information.")
    return None


def detect_text_emotion(client: Client, transcribed_text: str, facial_emotion_hint: Optional[str] = None) -> EmotionResult:
    fallback = simple_emotion_fallback(transcribed_text)
    if fallback:
        return fallback
    response = client.chat(
        model=MODEL_NAME,
        format="json",
        messages=[
            {"role": "system", "content": "You return valid JSON only."},
            {"role": "user", "content": build_emotion_prompt(transcribed_text, facial_emotion_hint)},
        ],
        stream=False,
        options={"temperature": 0.1, "num_predict": 120, "num_ctx": 2048},
    )
    data = safe_json_extract(response["message"]["content"])
    if not data:
        return EmotionResult("trust", 0.3, "Could not parse model output, so a neutral-social fallback was used.")
    emotion = str(data.get("emotion", "")).strip().lower()
    reason = str(data.get("reason", "")).strip()
    try:
        confidence = float(data.get("confidence", 0.0))
    except Exception:
        confidence = 0.0
    confidence = max(0.0, min(1.0, confidence))
    if emotion not in PLUTCHIK_EMOTIONS:
        return EmotionResult("trust", min(confidence, 0.3), "Invalid emotion returned, so fallback emotion was used.")
    return EmotionResult(emotion, confidence, reason or "Emotion inferred from the transcribed message.")


def default_face_emotion_json() -> dict:
    return {
        "available": False,
        "reliable": False,
        "backend": "Ollama vision model",
        "host": VISION_OLLAMA_HOST,
        "model": VISION_MODEL_NAME,
        "dominant_emotion": None,
        "mapped_plutchik_emotion": None,
        "confidence": 0.0,
        "averaged_scores": {},
        "vlm_result_samples": [],
        "frame_count": 0,
        "sampled_frame_count": 0,
        "started_at": None,
        "ended_at": None,
        "error": "No face emotion capture was provided.",
    }


def fuse_text_and_face_emotion(text_emotion: EmotionResult, face_json: dict) -> dict:
    face_available = bool(face_json.get("available"))
    face_reliable = bool(face_json.get("reliable"))
    face_emotion = face_json.get("mapped_plutchik_emotion")
    face_confidence = float(face_json.get("confidence") or 0.0)

    text_json = {
        "emotion": text_emotion.emotion,
        "confidence": round(text_emotion.confidence, 4),
        "reason": text_emotion.reason,
    }

    if not face_available or not face_emotion:
        return {
            "emotion": text_emotion.emotion,
            "confidence": round(text_emotion.confidence, 4),
            "reason": f"Text emotion used because no reliable facial-expression signal was available. Text reason: {text_emotion.reason}",
            "text_emotion": text_json,
            "face_emotion": face_json,
            "agreement": False,
            "fusion_strategy": "text_only_no_face_signal",
        }

    agreement = text_emotion.emotion == face_emotion

    if agreement:
        fused_conf = TEXT_WEIGHT * text_emotion.confidence + FACE_WEIGHT * face_confidence
        return {
            "emotion": text_emotion.emotion,
            "confidence": round(max(text_emotion.confidence, fused_conf), 4),
            "reason": f"Text and facial expression agree on {text_emotion.emotion}.",
            "text_emotion": text_json,
            "face_emotion": face_json,
            "agreement": True,
            "fusion_strategy": "agreement_weighted_boost",
        }

    # Conflict handling: explicit/confident text wins, especially when the user says how they feel.
    if text_emotion.confidence >= 0.75:
        fused_conf = max(0.45, text_emotion.confidence - (0.10 if face_reliable else 0.05))
        return {
            "emotion": text_emotion.emotion,
            "confidence": round(fused_conf, 4),
            "reason": f"Text emotion is confident and conflicts with the face signal, so text is prioritized. Face suggested {face_emotion}.",
            "text_emotion": text_json,
            "face_emotion": face_json,
            "agreement": False,
            "fusion_strategy": "conflict_text_priority",
        }

    # If the text is weak or ambiguous and face is strong, let face guide the response.
    if face_reliable and face_confidence >= 0.70 and text_emotion.confidence < 0.60:
        return {
            "emotion": face_emotion,
            "confidence": round(face_confidence * 0.85, 4),
            "reason": f"Text was ambiguous, while facial expression strongly suggested {face_emotion}.",
            "text_emotion": text_json,
            "face_emotion": face_json,
            "agreement": False,
            "fusion_strategy": "ambiguous_text_face_priority",
        }

    # Mixed/uncertain case: keep text but reduce confidence.
    return {
        "emotion": text_emotion.emotion,
        "confidence": round(max(0.35, text_emotion.confidence * 0.75), 4),
        "reason": f"Text and face signals were mixed. Text is retained cautiously; face suggested {face_emotion}.",
        "text_emotion": text_json,
        "face_emotion": face_json,
        "agreement": False,
        "fusion_strategy": "mixed_cautious_text_priority",
    }


# =========================
# Response generation
# =========================

def remove_all_emojis_except_allowed_faces(text: str) -> str:
    result = []
    for char in text:
        if char in ALLOWED_FACE_EMOJIS:
            result.append(char)
            continue
        code = ord(char)
        is_emoji_or_symbol = 0x1F300 <= code <= 0x1FAFF or 0x2600 <= code <= 0x27BF or code in {0x200D, 0xFE0F}
        if not is_emoji_or_symbol:
            result.append(char)
    return "".join(result)


def remove_allowed_face_emojis(text: str) -> str:
    return "".join(char for char in text if char not in ALLOWED_FACE_EMOJIS)


def normalize_reply(raw_reply: str, emotion: str) -> str:
    required_emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")
    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = remove_allowed_face_emojis(cleaned)
    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)
    if not cleaned:
        cleaned = "I’m here with you."
    return f"{cleaned} {required_emoji}"


def runtime_context() -> str:
    return f"Current local date and time: {now_ts()}. Use this when the user asks about today, now, date, or time."


def deterministic_reply_if_applicable(user_text: str, emotion: str) -> Optional[str]:
    text = user_text.strip().lower()
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")
    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"
    if "what is the time" in text or "what time is it" in text or "current time" in text:
        return f"The current time is {datetime.now().strftime('%H:%M')}. {emoji}"
    farewell_words = {"bye", "goodbye", "see you", "see you later", "talk later", "have a nice day", "have a good day"}
    if any(phrase in text for phrase in farewell_words):
        return "Thank you, and take care. 🙂"
    return None


def build_response_system_prompt(fused_emotion_json: dict, user_profile: Optional[dict] = None) -> str:
    memory_context = build_user_memory_context(user_profile)
    return f"""
{AMECA_SYSTEM_PROMPT}

RUNTIME CONTEXT
{runtime_context()}

{memory_context}

You are generating Ameca's next conversational response.

PRIVATE FUSED EMOTION CONTEXT
Use this fused emotion JSON as the main emotional context for response generation.
Do not mention it directly.

Fused multimodal emotion JSON:
{json.dumps(fused_emotion_json, indent=2)}

Interpretation rules:
- The fused emotion already combines transcribed-text emotion and facial-expression emotion.
- Use it only to adapt empathy, warmth, and emoji.
- Do not mention camera, vision model, facial-expression analysis, detected emotion, or private emotion context to the user.
- Never say "you look sad", "your face shows", or "I detected".

Return JSON only in this exact shape:
{{
  "reply": "assistant response without emoji",
  "emoji": "one facial emoji",
  "tone": "short tone label"
}}

Conversation behavior rules:
- Respond directly to what the user said.
- Do not greet repeatedly.
- Do not reintroduce yourself unless asked.
- Use the user's name occasionally, not in every response.
- Keep the response to 1-2 short sentences.
- Maximum response length: 30 words unless the user asks for detail.
- If the user only shares a feeling, validate briefly; do not immediately give a list of advice.
- If the user asks for advice, give practical help.
- If speech recognition seems wrong, gently ask for clarification.

Emoji rules:
- Use exactly one final facial emoji.
- Use only one of these emojis: 🙂 😊 😌 😔 😟 🤔 😮 😢 😠 🤢
""".strip()


def trim_history(history: list[dict]) -> list[dict]:
    return history[-MAX_HISTORY_MESSAGES:]


def prompt_ready_history(history: list[dict]) -> list[dict]:
    return [{"role": item["role"], "content": item["content"]} for item in history]


def generate_response(client: Client, user_text: str, fused_emotion_json: dict, history: list[dict], user_profile: Optional[dict] = None) -> str:
    emotion = str(fused_emotion_json.get("emotion", "trust"))
    deterministic = deterministic_reply_if_applicable(user_text, emotion)
    if deterministic:
        return deterministic
    messages = [
        {"role": "system", "content": build_response_system_prompt(fused_emotion_json, user_profile)[:6500]},
        *prompt_ready_history(trim_history(history[-6:])),
        {"role": "user", "content": user_text[:1500]},
    ]
    response = client.chat(
        model=MODEL_NAME,
        messages=messages,
        options={"temperature": 0.4, "num_predict": 120, "repeat_penalty": 1.25, "num_ctx": 2048},
        stream=False,
    )
    raw_reply = response["message"]["content"]
    data = safe_json_extract(raw_reply)
    if data and isinstance(data, dict):
        reply_text = str(data.get("reply", "")).strip()
        emoji = str(data.get("emoji", "")).strip()
        if emoji in {":)", ":-)", ""}:
            emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")
        if reply_text:
            return normalize_reply(f"{reply_text} {emoji}", emotion)
    return normalize_reply(raw_reply, emotion)


# =========================
# User name / transcript helpers
# =========================

def ask_user_to_spell_name(whisper_model: WhisperModel, silero_model, input_device: Optional[int] = INPUT_DEVICE) -> Optional[str]:
    print()
    print_ts("Please spell your name letter by letter. For example: L E T I C I A.")
    print()
    wav_path = listen_for_utterance_with_silero_vad(input_device, silero_model, "spelled name")
    if not wav_path:
        return None
    try:
        transcript = transcribe_audio(wav_path, whisper_model)
    finally:
        try:
            os.remove(wav_path)
        except OSError:
            pass
    print_ts(f"Raw spelling transcript: {transcript}")
    return clean_spelled_name(transcript)


def generate_introduction_response(client: Client, user_name: str) -> str:
    try:
        response = client.chat(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "You are Ameca, a humanoid social robot. Greet the user warmly in 1 sentence and end with 🙂."},
                {"role": "user", "content": f"My name is {user_name}"},
            ],
            options={"temperature": 0.5, "num_predict": 60, "num_ctx": 1024},
            stream=False,
        )
        return normalize_reply(response["message"]["content"], "trust")
    except Exception:
        return f"Hello {user_name}. I am Ameca. It is nice to meet you. 🙂"


def prompt_for_user_name(client: Client, whisper_model: WhisperModel, silero_model, input_device: Optional[int] = INPUT_DEVICE) -> tuple[str, dict, str]:
    users = load_users()
    spoken_name = ""
    for _attempt in range(2):
        print()
        print_ts("Please say your name. For example: 'My name is Leticia'.")
        print()
        wav_path = listen_for_utterance_with_silero_vad(input_device, silero_model, "name")
        if wav_path:
            try:
                spoken_name = transcribe_audio(wav_path, whisper_model).strip()
            finally:
                try:
                    os.remove(wav_path)
                except OSError:
                    pass
        print_ts(f"Raw name transcript: {spoken_name or '(empty)'}")
        extracted_name = extract_name_from_text(spoken_name)
        spoken_name = extracted_name or clean_spoken_name(spoken_name)
        if spoken_name and not looks_like_invalid_name(spoken_name):
            break
        print_ts(f"I heard '{spoken_name or 'nothing'}', but that does not sound like a name.")
    if not spoken_name or looks_like_invalid_name(spoken_name):
        spoken_name = "Guest"
    spelled_name = ask_user_to_spell_name(whisper_model, silero_model, input_device)
    if spelled_name:
        spoken_name = spelled_name
        print_ts(f"Using spelled name: {spoken_name}")
    else:
        print_ts(f"Using spoken name: {spoken_name}")
    print_ts(f"Detected name: {spoken_name}")
    user_key = slugify_name(spoken_name)
    is_new_user = user_key not in users
    if is_new_user:
        users[user_key] = {"name": spoken_name, "created_at": now_ts(), "last_seen": now_ts(), "session_files": [], "conversation_summary": ""}
    else:
        users[user_key]["last_seen"] = now_ts()
    save_users(users)
    print_ts(f"{'Nice to meet you' if is_new_user else 'Welcome back'}, {users[user_key]['name']}.")
    intro = generate_introduction_response(client, users[user_key]["name"])
    print_ts(f"Assistant: {intro}")
    print()
    return user_key, users[user_key], intro


def save_session_transcript(user_key: str, user_profile: dict, session_log: list[dict]) -> str:
    ensure_data_dirs()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(SESSIONS_DIR, f"{user_key}_{timestamp}.json")
    transcript_data = {
        "user": {"key": user_key, "name": user_profile.get("name", "Guest")},
        "session": {
            "started_at": session_log[0]["timestamp"] if session_log else now_ts(),
            "ended_at": now_ts(),
            "model": MODEL_NAME,
            "ollama_host": OLLAMA_HOST,
            "asr": {"backend": "faster-whisper", **FAST_WHISPER_CONFIG},
            "camera": {
                "backend": "OpenCV/V4L2 or AVFoundation",
                "camera_device": CAMERA_DEVICE,
                "raw_frame_width": CAMERA_FRAME_WIDTH,
                "raw_frame_height": CAMERA_FRAME_HEIGHT,
                "use_zed_half_frame_crop": USE_ZED_HALF_FRAME_CROP,
                "zed_eye": ZED_EYE,
                "preview_enabled": CAMERA_PREVIEW_ENABLED,
            },
            "face_emotion": {"backend": "Ollama vision model", "vision_host": VISION_OLLAMA_HOST, "vision_model": VISION_MODEL_NAME, "max_frames_per_utterance": VISION_MAX_FRAMES_PER_UTTERANCE, "request_timeout_seconds": VISION_REQUEST_TIMEOUT_SECONDS},
            "fusion": {"text_weight": TEXT_WEIGHT, "face_weight": FACE_WEIGHT, "plutchik_emotions": list(PLUTCHIK_EMOTIONS)},
        },
        "messages": session_log,
    }
    with open(path, "w", encoding="utf-8") as file:
        json.dump(transcript_data, file, indent=2, ensure_ascii=False)
    return path


def update_user_after_session(user_key: str, session_path: str) -> None:
    users = load_users()
    if user_key not in users:
        return
    users[user_key]["last_seen"] = now_ts()
    users[user_key].setdefault("session_files", []).append(session_path)
    save_users(users)


def rename_current_user(old_user_key: str, user_profile: dict, new_name: str) -> tuple[str, dict]:
    users = load_users()
    new_name = clean_spoken_name(new_name)
    new_key = slugify_name(new_name)
    if not new_name or looks_like_invalid_name(new_name):
        return old_user_key, user_profile
    if new_key in users:
        users[new_key]["last_seen"] = now_ts()
        save_users(users)
        return new_key, users[new_key]
    old_profile = users.pop(old_user_key, user_profile)
    old_profile["name"] = new_name
    old_profile["last_seen"] = now_ts()
    users[new_key] = old_profile
    save_users(users)
    print_ts(f"Updated user name to: {new_name}")
    return new_key, users[new_key]


# =========================
# Main loop
# =========================

def main() -> None:
    print_ts("Starting Silero VAD + faster-whisper multimodal Plutchik fusion chat prototype.")
    print_ts(f"Python: {sys.version.split()[0]}")
    print_ts(f"Ollama host: {OLLAMA_HOST}")
    print_ts(f"Ollama model: {MODEL_NAME}")
    print_ts(f"Vision Ollama host: {VISION_OLLAMA_HOST}")
    print_ts(f"Vision model: {VISION_MODEL_NAME}")
    print_ts(f"Camera device: {CAMERA_DEVICE}; ZED half-frame crop: {USE_ZED_HALF_FRAME_CROP}; eye={ZED_EYE}")
    print()

    ensure_data_dirs()
    check_ollama_available(host=OLLAMA_HOST, label="chat Ollama")
    check_ollama_available(host=VISION_OLLAMA_HOST, label="vision Ollama")
    ensure_model_available(MODEL_NAME, host=OLLAMA_HOST)
    ensure_model_available(VISION_MODEL_NAME, host=VISION_OLLAMA_HOST)
    client = Client(host=OLLAMA_HOST)
    vision_client = Client(host=VISION_OLLAMA_HOST, timeout=VISION_REQUEST_TIMEOUT_SECONDS + 2.0)

    list_input_devices()
    list_camera_devices()

    print_ts("Loading Silero VAD...")
    silero_model = load_silero_vad()
    print_ts("Silero VAD ready.")

    print_ts("Loading faster-whisper...")
    whisper_model = WhisperModel(FAST_WHISPER_CONFIG["model"], device=FAST_WHISPER_CONFIG["device"], compute_type=FAST_WHISPER_CONFIG["compute_type"])
    print_ts("faster-whisper ready.")

    user_key, user_profile, intro_reply = prompt_for_user_name(client, whisper_model, silero_model, INPUT_DEVICE)

    print("Automatic listening mode is active.")
    print("Speak naturally. Silero VAD will detect speech, llama3.2-vision:11b will analyze facial emotion, text+face will be fused, and Ameca will respond.")
    print("Say '/exit' or press Ctrl+C to save the transcript and quit.\n")

    history: list[dict] = [{"role": "assistant", "content": intro_reply}]
    session_log: list[dict] = [{"role": "assistant", "content": intro_reply, "timestamp": now_ts(), "intent": "self_introduction"}]

    try:
        while True:
            wav_path, face_capture = listen_for_utterance_with_silero_vad_and_face_emotion(INPUT_DEVICE, silero_model, vision_client, CAMERA_DEVICE, "utterance")

            if face_capture:
                if face_capture.error:
                    print_ts(f"Face emotion capture error: {face_capture.error}")
                else:
                    print_ts(f"Face emotion summary: {face_capture.summary_text}")

            if not wav_path:
                continue
            try:
                user_text = transcribe_audio(wav_path, whisper_model)
            finally:
                try:
                    os.remove(wav_path)
                except OSError:
                    pass

            if not user_text:
                print_ts("No speech detected after transcription.")
                continue

            print_ts(f"faster-whisper transcript: {user_text}")

            maybe_name = extract_name_from_text(user_text)
            if maybe_name and not looks_like_invalid_name(maybe_name):
                user_key, user_profile = rename_current_user(user_key, user_profile, maybe_name)
                reply = generate_introduction_response(client, user_profile["name"])
                print_ts(f"Assistant: {reply}\n")
                history.extend([{"role": "user", "content": user_text}, {"role": "assistant", "content": reply}])
                history = trim_history(history)
                session_log.append({"role": "user", "content": user_text, "timestamp": now_ts(), "intent": "name_introduction"})
                session_log.append({"role": "assistant", "content": reply, "timestamp": now_ts()})
                continue

            command = normalize_command(user_text)
            if command in {"exit", "quit"}:
                print_ts("Goodbye.")
                break
            if command == "clear":
                history.clear()
                print_ts("Conversation history cleared.")
                continue

            facial_hint = face_capture.summary_text if face_capture else None
            face_json = face_capture.as_json if face_capture else default_face_emotion_json()
            text_emotion = detect_text_emotion(client, user_text, facial_hint)
            fused_emotion_json = fuse_text_and_face_emotion(text_emotion, face_json)

            print_ts("Text emotion JSON:")
            print(json.dumps(fused_emotion_json["text_emotion"], indent=2))
            print()
            print_ts("Face emotion JSON:")
            print(json.dumps(face_json, indent=2))
            print()
            print_ts("Fused emotion JSON:")
            print(json.dumps(fused_emotion_json, indent=2))
            print()

            reply = generate_response(client, user_text, fused_emotion_json, history, user_profile)
            print_ts(f"Assistant: {reply}\n")

            user_message = {
                "role": "user",
                "content": user_text,
                "timestamp": now_ts(),
                "text_emotion": fused_emotion_json["text_emotion"],
                "face_emotion": face_json,
                "fused_emotion": fused_emotion_json,
                "facial_emotion_hint": facial_hint,
                "input_mode": "silero_vad_faster_whisper_vlm_multimodal_fusion",
            }
            assistant_message = {"role": "assistant", "content": reply, "timestamp": now_ts()}
            history.extend([{"role": "user", "content": user_text}, {"role": "assistant", "content": reply}])
            history = trim_history(history)
            session_log.extend([user_message, assistant_message])

    except KeyboardInterrupt:
        print()
        print_ts("Goodbye.")
    finally:
        if session_log:
            session_path = save_session_transcript(user_key, user_profile, session_log)
            update_user_after_session(user_key, session_path)
            print_ts(f"Conversation transcript saved to: {session_path}")
        else:
            print_ts("No conversation messages to save.")


if __name__ == "__main__":
    main()
