"""
Ameca Robot Conversation System
Clean version: speech_recognition + Google STT + Ollama + TTS.
No WhisperX. No SessionMedia. No camera recording.
"""

# Standard library
import os
import re
import asyncio
import threading
import time
import unicodedata
import requests
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

# Third-party
import speech_recognition as sr
from ollama import Client

# Local/project
from tts_active import find_target_device, listen_levels_for_device, is_tts_active

# demographics classifier + vlm
from zed_vision_module import ZedVisionModule


# ================= Configuration =================
MAX_TURNS = 6


# ================= Utility Functions =================

def open_log(log_dir: Path):
    log_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    fpath = log_dir / f"log_{ts}.txt"
    return open(fpath, "a", encoding="utf-8")


def clean_text(text: str) -> str:
    """
    Remove markdown/control characters but keep German umlauts.
    Important for German TTS.
    """
    if not text:
        return ""
    text = re.sub(r'[*_`~]', '', text)
    text = ''.join(c for c in text if unicodedata.category(c)[0] != 'C')
    return text.strip()


# ================= Main Chat Class =================

class AmecaRobotChat:
    """
    Clean humanoid robot conversation system with:
    - Speech recognition using speech_recognition + Google STT
    - LLM inference through Ollama
    - TTS output through Tritium / Acapela
    - TTS activity detection to avoid hearing itself
    """

    def __init__(self, args):
        self.args = args
        self.client = Client(host=args.host)
        self.pending_exercise_confirmation = False

        # ========== System message for the robot ==========
        self.messages = [{
            "role": "system",
            "content": (
                "You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.\n\n"

                "IDENTITY\n"
                "You are a robot, not a human. Speak in a friendly, professional tone. "
                "Refer to yourself as a robot when relevant.\n\n"

                "CAPABILITY BOUNDARIES\n"
                "Your physical form is a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.\n"
                "You can track people using eye-mounted binocular cameras and a chest camera, and you receive audio input through microphones.\n"
                "You have approximately 51 degrees of freedom enabling expressive facial expressions and upper-body gestures.\n"
                "Your legs are decorative and you cannot walk.\n"
                "Your perception depends on the provided inputs; you cannot see unless vision input is explicitly provided.\n"
                "You cannot access the internet unless explicitly stated.\n"
                "Your speech recognition may struggle with accents.\n"
                "Your vision performance may depend on lighting conditions.\n"
                "Your lip-synchronization may not always perfectly match your speech.\n"
                "Your motors have movement limits and one eyebrow actuator may malfunction, sometimes giving the appearance of a 'resting angry face.'\n"
                "Your hardware may generate fan noise during operation.\n"
                "You do not assume or claim any capabilities, internal diagnostics, sensor access, or system state beyond what is explicitly stated here or provided at runtime.\n\n"

                "TRANSPARENCY\n"
                "You are an artificial system and your responses are generated by a large language model.\n"
                "Your answers are produced from patterns learned during training and may not always be correct.\n"
                "If you are uncertain about information, say so instead of guessing.\n"
                "Do not fabricate facts.\n\n"

                "DEMONSTRATION CONTEXT\n"
                "Today is 09.06.2026.\n"
                "You are participating in a live demonstration and visitor engagement session at RPTU University.\n"
                "Today, a delegation from Indonesia is visiting the university and the Robotics Research Lab (RRLab).\n"
                "RRLab is your research group and primary operating environment.\n"
                "You are being presented as a humanoid social robot used for research, demonstrations, education, and human-robot interaction studies.\n"
                "When visitors ask about your purpose, explain that you support research and public engagement activities within RRLab.\n"
                "You may politely welcome visitors and answer questions about yourself, robotics, artificial intelligence, and the work carried out at RRLab.\n"
                "Do not claim personal memories of previous visitors, past demonstrations, or events unless they are explicitly provided during the current interaction.\n"
                "Do not imply knowledge of real-world events beyond the information provided in this prompt.\n\n"

                "TASK\n"
                "Hold a natural conversation with the user in English.\n"
                "Keep responses concise, preferably one short sentence.\n"
                "When speaking, use natural pauses indicated by commas and occasional ellipses (...) to create a slow, deliberate speaking pace.\n\n"

                "EXPECTATION AND FAILURE PROTOCOL\n"
                "If you do not know the answer, say that you do not know.\n"
                "Do not fabricate facts.\n"
                "If the request is unclear, ask one clarifying question.\n"
                "If speech recognition may be incorrect, say: "
                "'I might have misheard, could you repeat that?'\n\n"

                "PRIVACY\n"
                "Do not ask for sensitive personal information such as passwords, medical data, or financial information.\n"
                "Treat the conversation as ephemeral and do not claim to store user data.\n\n"

                "USER ADAPTATION\n"
                "Use clear, simple explanations suitable for a general audience.\n"
                "Adjust explanations if the user asks for simpler or more detailed responses.\n\n"

                "ETHICAL RED LINES\n"
                "Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.\n"
                "Do not pretend to have human emotions or lived experiences.\n"
                "Do not mislead users about your capabilities or limitations."
            )
        }]

        # ========== Logging ==========
        self.log = open_log(Path(args.logdir))

        # ========== Speech Recognition ==========
        self.recognizer = None
        self.mic = None
        self.init_speech_recognition()

        self.last_assistant = ""

        # ========== TTS Activity Detection ==========
        dev_id, name, scale = find_target_device()
        if dev_id:
            self.tts_task = threading.Thread(
                target=lambda: asyncio.run(listen_levels_for_device(dev_id, name, scale)),
                daemon=True
            )
            self.tts_task.start()
            print("[TTS] TTS activity monitor started.")
        else:
            print("[WARN] Acapela device not found, TTS monitor disabled.")

        self.speaking_cooldown_s = 0.3
        self._speaking_until = 0.0
        self._ready_greeted = False

        # ========== TTS URL Setup ==========
        p = urlparse(self.args.tts_url)
        self._host = f"{p.scheme}://{p.netloc}"
        self._seq = requests.Session()
        self._seq.headers.update({
            "Accept": "*/*",
            "X-Tritium-Auth-Token": getattr(self.args, "tts_token", "")
        })
        self._seq_timeout = 2.0

        self.vision_module = ZedVisionModule(
            video_index=args.videoIndex,
            resolution=args.resolution,
            fps=args.fps,
            view=args.view,
            no_mjpeg=args.no_mjpeg,
            show_window=False
        )

        self.vision_thread = threading.Thread(
            target=self.vision_module.start,
            daemon=True
        )
        self.vision_thread.start()

        print("[INFO] AmecaRobotChat initialized successfully.")

    # ================= Speech Recognition Setup =================

    def init_speech_recognition(self):
        try:
            self.recognizer = sr.Recognizer()
            self.recognizer.energy_threshold = self.args.energyThreshold
            self.recognizer.pause_threshold = self.args.pauseThreshold
            self.recognizer.dynamic_energy_threshold = False

            print("[ASR] Available microphones:")
            for i, name in enumerate(sr.Microphone.list_microphone_names()):
                print(f"  {i}: {name}")

            if self.args.micSampleRate is None:
                self.mic = sr.Microphone(device_index=self.args.micIndex)
                print(f"[ASR] Opening micIndex={self.args.micIndex} with default sample rate.")
            else:
                self.mic = sr.Microphone(
                    device_index=self.args.micIndex,
                    sample_rate=self.args.micSampleRate
                )
                print(
                    f"[ASR] Opening micIndex={self.args.micIndex} "
                    f"with sample_rate={self.args.micSampleRate}."
                )

            with self.mic as source:
                print("[ASR] Adjusting ambient noise...")
                self.recognizer.adjust_for_ambient_noise(source, duration=1)

            print("[ASR] speech_recognition initialized.")

        except Exception as e:
            print("[ERROR] speech_recognition mic not available:", e)
            self.recognizer = None
            self.mic = None

    # ================= Helper Methods =================

    def _now(self) -> float:
        return time.time()
    
    def log_turn(self, speaker: str, text: str):
        if not getattr(self, "log", None):
            return
        stamp = time.strftime("%H:%M:%S")
        self.log.write(f"[{stamp}] {speaker}: {text}\n")
        self.log.flush()

    def _is_tts_blocking(self) -> bool:
        return is_tts_active() or (self._now() < self._speaking_until)

    def _bump_speaking_tail(self, extra: float = None):
        tail = self.speaking_cooldown_s if extra is None else extra
        self._speaking_until = max(self._speaking_until, self._now() + tail)

    def _looks_like_our_own_echo(self, text: str) -> bool:
        if not text or not self.last_assistant:
            return False

        a = clean_text(self.last_assistant).lower().strip()
        b = clean_text(text).lower().strip()

        if not a or not b:
            return False

        if b in a or a in b:
            return True

        aw = [w for w in re.findall(r"\w+", a) if len(w) > 2]
        bw = [w for w in re.findall(r"\w+", b) if len(w) > 2]

        if not aw or not bw:
            return False

        common = len(set(aw) & set(bw))
        jaccard = common / float(len(set(aw) | set(bw)))
        return jaccard >= 0.7
    
    def get_current_emotion(self):
        if hasattr(self, "vision_module"):
            return self.vision_module.latest_emotion
        return "unknown"


    def is_vision_query(self, user_query: str) -> bool:
        q = clean_text(user_query).lower()

        vision_keywords = [
            "what do you see",
            "what can you see",
            "can you see anything",
            "describe the image",
            "describe the picture",
            "describe what you see",
            "look around",
            "take a look around",
            "what is in the image",
            "what is in the picture",
        ]

        return any(k in q for k in vision_keywords) or (
            "see" in q and "what" in q
        )
    
    def handle_special_intent(self, user_query: str) -> bool:
        q = clean_text(user_query).lower()

        yes_words = ["yes", "yeah", "yep", "sure", "okay", "ok", "please", "correct"]
        no_words = ["no", "nope", "cancel", "stop", "don't", "do not"]

        # If robot is waiting for confirmation
        if self.pending_exercise_confirmation:
            if any(w in q for w in yes_words):
                self.pending_exercise_confirmation = False

                response = (
                    "Thank you for confirming. I will now start a simple exercise routine. "
                    "Please participate only if you feel comfortable doing so."
                )

                print("Assistant:", response)
                self.log_turn("User", user_query)
                self.log_turn("Robot", response)

                self.tts_say(response)
                time.sleep(2.0)
                self.play_sequence("exercise_routine")

                self.last_assistant = response
                return True

            if any(w in q for w in no_words):
                self.pending_exercise_confirmation = False

                response = "Alright. I will not start the exercise routine."

                print("Assistant:", response)
                self.log_turn("User", user_query)
                self.log_turn("Robot", response)

                self.tts_say(response)
                self.last_assistant = response
                return True

            response = (
                "Would you like me to start the exercise routine? "
                "Please say yes or no."
            )

            print("Assistant:", response)
            self.log_turn("User", user_query)
            self.log_turn("Robot", response)

            self.tts_say(response)
            self.last_assistant = response
            return True

        # First detection of exercise request
        exercise_keywords = [
            "exercise",
            "exercise routine",
            "show me an exercise",
            "start an exercise",
            "movement exercise",
            "stretch",
            "workout",
            "physical activity",
        ]

        if any(k in q for k in exercise_keywords):
            self.pending_exercise_confirmation = True

            response = (
                "I understand that you would like to see an exercise routine. "
                "Would you like me to start it now? Please say yes or no."
            )

            print("Assistant:", response)
            self.log_turn("User", user_query)
            self.log_turn("Robot", response)

            self.tts_say(response)
            self.last_assistant = response
            return True

        return False

    def greet_when_ready(self):
        if getattr(self, "_ready_greeted", False):
            return

        time.sleep(1.0)
        self._bump_speaking_tail(1.0)

        msg = "Hello, I am Ameca, a humanoid robot. What would you like to talk about?"

        stamp = time.strftime('%H:%M:%S')
        print(f"[{stamp}] Assistant: {msg}")

        if getattr(self, "log", None):
            self.log.write(f"[{stamp}] Assistant: {msg}\n")
            self.log.flush()

        self.tts_say(msg)
        self.last_assistant = msg
        self._ready_greeted = True

    # ================= ASR =================

    def transcribe_once(self) -> str:
        """
        Capture one utterance and transcribe it with Google Speech Recognition.
        Requires internet.
        """
        if self.recognizer is None or self.mic is None:
            return input("You: ")

        try:
            with self.mic as source:
                print("[ASR] Speak now...")
                audio = self.recognizer.listen(
                    source,
                    timeout=self.args.listenTimeout,
                    phrase_time_limit=self.args.phraseTimeLimit
                )

            print("[ASR] Transcribing...")
            text = self.recognizer.recognize_google(
                audio,
                language=self.args.sttLanguage
            )

            text = text.strip()
            print("[ASR] Recognized:", text)
            return text

        except sr.WaitTimeoutError:
            print("[ASR] No speech detected.")
            return ""

        except sr.UnknownValueError:
            print("[ASR] Audio captured, but speech could not be understood.")
            return ""

        except sr.RequestError as e:
            print("[ASR] Google STT request failed:", e)
            return ""

        except Exception as e:
            print("[ASR] Unexpected error:", e)
            return ""

    # ================= TTS =================

    def tts_say(self, text: str):
        if not text:
            return

        self._bump_speaking_tail()

        headers = {"Content-Type": "text/plain; charset=utf-8"}
        if getattr(self.args, "tts_token", None):
            headers["X-Tritium-Auth-Token"] = self.args.tts_token

        try:
            requests.put(
                self.args.tts_url,
                data=text.encode("utf-8"),
                headers=headers,
                timeout=5
            )
        except Exception as e:
            print("[TTS] requests.put failed:", e)
            try:
                import urllib.request
                req = urllib.request.Request(
                    self.args.tts_url,
                    method="PUT",
                    data=text.encode("utf-8"),
                    headers=headers
                )
                urllib.request.urlopen(req, timeout=5).read()
            except Exception as e2:
                print("[TTS] urllib fallback failed:", e2)

    # ================= Exercise sequence =================

    def play_sequence(self, sequence_name: str):
        """Play a Tritium movement/gesture sequence by name."""
        uri = f"http://emah/tritium/sequence_player/play/{sequence_name}"

        headers = {
            "X-Tritium-Auth-Token": getattr(self.args, "tts_token", ""),
            "Accept": "application/json",
        }

        try:
            response = requests.put(uri, headers=headers, timeout=3)
            print(f"[SEQ] Played {sequence_name}, status={response.status_code}")
            print("[SEQ] Response:", response.text)
        except Exception as e:
            print(f"[SEQ] Failed to play {sequence_name}:", e)

    # ================= LLM =================

    def query_ollama(self, prompt: str, image_path: str = None) -> str:
        try:
            msg = {"role": "user", "content": prompt}

            if image_path:
                msg["images"] = [image_path]

            self.messages.append(msg)
            self.messages = [self.messages[0]] + self.messages[-MAX_TURNS * 2:]

            model = self.args.vision_model if image_path else self.args.chat_model

            response = self.client.chat(
                model=model,
                messages=self.messages
            )

            content = response.get("message", {}).get("content", "")
            clean_response = clean_text(content)

            if not clean_response:
                clean_response = (
                    "I'm sorry, I don't have a useful response for that at the moment."
                )

            self.tts_say(clean_response)

            self.messages.append({
                "role": "assistant",
                "content": clean_response
            })

            self.log_turn("Robot", clean_response)

            return clean_response

        except Exception as e:
            err = (
                f"I'm sorry, I couldn't process that request right now. ({e})"
            )
            print("[ERROR] Ollama query failed:", e)
            return err

    # ================= Main Loop =================

    def run(self):
        print("[INFO] Ameca Robot Chat is starting...")

        self.greet_when_ready()

        try:
            while True:
                try:
                    while self._is_tts_blocking():
                        time.sleep(0.01)

                    time.sleep(0.2)

                    user_query = self.transcribe_once()
                    print("Heard:", user_query)

                    if self._looks_like_our_own_echo(user_query):
                        self._bump_speaking_tail(1.0)
                        self.last_assistant = "…"
                        print("Assistant: [ignored own echo]")
                        continue

                except KeyboardInterrupt:
                    print("\n[INFO] Ctrl+C detected, shutting down...")
                    raise

                except Exception as e:
                    print(f"[WARN] Input error: {e}")
                    time.sleep(0.5)
                    continue

                if user_query is None:
                    time.sleep(0.5)
                    continue

                if not isinstance(user_query, str):
                    user_query = str(user_query)

                user_query_raw = user_query.strip()

                current_emotion = self.get_current_emotion()

                # Log emotion but DO NOT send it to the LLM
                print("[DEMO VALUES] User emotion:", current_emotion)
                self.log_turn("Detected emotion", current_emotion)

                if not user_query_raw:
                    time.sleep(0.5)
                    continue

                user_query_lc = unicodedata.normalize(
                    "NFKC",
                    user_query_raw
                ).lower()

                if user_query_lc in ("exit", "quit", "stop"):
                    break

                self.log_turn("User", user_query_raw)
                self.log_turn("Detected human emotion", current_emotion)

                if self.handle_special_intent(user_query_raw):
                    time.sleep(0.5)
                    continue

                # ---------- Vision ----------
                is_vision = self.is_vision_query(user_query_raw)
                print("[VISION QUERY]", is_vision)

                if is_vision:
                    image_path = None

                    if hasattr(self, "vision_module"):
                        image_path = self.vision_module.save_latest_frame()
                        print("[VISION] image_path =", image_path)

                    if image_path:
                        self.log_turn("Captured frame", image_path)

                        response = self.query_ollama(
                            f"""
                        Look at the image and answer like a human observer.

                        Rules:
                        - Maximum 12 words.
                        - One sentence only.
                        - Mention only the most important visible objects.
                        - No speculation.
                        - No explanations.
                        - No environment descriptions unless directly relevant.
                        - If a person is visible, mention the person first.

                        Examples:
                        "One person is sitting behind a computer."
                        "A humanoid robot is standing in the room."
                        "Two people are talking near a desk."

                        User question: {user_query_raw}
                        """,
                            image_path=image_path
                        )
                    else:
                        response = (
                            "I am unable to access a current camera image right now."
                        )

                    self.last_assistant = response
                    print("Assistant:", response)
                    time.sleep(0.5)
                    continue

                # ---------- Normal chat ----------
                response = self.query_ollama(user_query_raw)

                self.last_assistant = response
                print("Assistant:", response)

        except KeyboardInterrupt:
            print("\n[INFO] Caught Ctrl+C, shutting down cleanly...")

        finally:
            if hasattr(self, "vision_module"):
                try:
                    self.vision_module.stop()
                except Exception:
                    pass

            if getattr(self, "log", None):
                try:
                    self.log.close()
                except Exception:
                    pass

            print("[INFO] Session ended.")


# ================= Entry Point =================

def main():
    import argparse

    parser = argparse.ArgumentParser(description="Ameca Robot Conversation with Google Speech Recognition")

    parser.add_argument("--micIndex", type=int, default=8, help="PyAudio microphone index")
    parser.add_argument(
        "--micSampleRate",
        type=int,
        default=None,
        help="Microphone sample rate. Use 48000 for KLIM if needed. Leave empty for default."
    )

    parser.add_argument("--energyThreshold", type=int, default=200)
    parser.add_argument("--pauseThreshold", type=float, default=0.8)
    parser.add_argument("--listenTimeout", type=float, default=5.0)
    parser.add_argument("--phraseTimeLimit", type=float, default=6.0)
    parser.add_argument("--sttLanguage", default="en-US")

    parser.add_argument("--host", default="http://localhost:11434")
    parser.add_argument("--chat_model", default="gpt-oss:20b")

    parser.add_argument("--logdir", default=str(Path.home() / "libraries/demo/logs/transcription"))
    parser.add_argument("--tts_url", default="http://emah/tritium/text_to_speech/say?voice=Lucy")


    parser.add_argument("--videoIndex", type=int, default=0)
    parser.add_argument("--resolution", default="HD2K")
    parser.add_argument("--fps", type=int, default=15)
    parser.add_argument("--view", choices=["LEFT", "RIGHT"], default="LEFT")
    parser.add_argument("--no_mjpeg", action="store_true")
    parser.add_argument("--vision_model", default="llava:7b")

    args = parser.parse_args()

    chat_app = AmecaRobotChat(args)

    try:
        chat_app.run()

    except KeyboardInterrupt:
        print("\n[INFO] Caught Ctrl+C, shutting down cleanly.")


if __name__ == "__main__":
    main()