from __future__ import annotations

import base64
import json
import os
import queue
import random
import re
import sys
import tempfile
import subprocess
import threading
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Tuple

# Linux-only Qt fix. Do not force this on macOS.
if sys.platform.startswith("linux"):
    os.environ["QT_QPA_PLATFORM"] = "xcb"

# Harmless on non-Windows; prevents some OpenCV backend priority issues on Windows.
os.environ["OPENCV_VIDEOIO_PRIORITY_MSMF"] = "0"

import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf
import torch
from faster_whisper import WhisperModel
from ollama import Client
from silero_vad import load_silero_vad, VADIterator
import platform

IS_MAC = platform.system() == "Darwin"
IS_LINUX = platform.system() == "Linux"

CAMERA_DEVICE = 0 if IS_MAC else 1
USE_ZED_HALF_FRAME_CROP = IS_LINUX

# =========================
# Local Ollama configuration
# =========================

OLLAMA_HOST = "http://127.0.0.1:11434"
# OLLAMA_HOST = "https://sunday-spread-colony-gnome.trycloudflare.com"

MODEL_NAME = "llama3:8b"
# MODEL_NAME = "mistral:7b"


# =========================
# Persistent memory / transcript configuration
# =========================

DATA_DIR = "conversation_data"
USERS_FILE = os.path.join(DATA_DIR, "users.json")
SESSIONS_DIR = os.path.join(DATA_DIR, "sessions")

# Keep this False for fast, clean shutdown.
# If True, the app will call Ollama at shutdown to summarize the session.
ENABLE_LLM_SESSION_SUMMARY = False


# =========================
# Ameca identity prompt
# =========================

AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information such as passwords, medical data, financial information, or private identity documents.
Treat the conversation as ephemeral in speech, but save only the local JSON transcript for this prototype when the session ends.

USER ADAPTATION
Use clear, simple explanations.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""


# =========================
# faster-whisper configuration
# =========================

FAST_WHISPER_CONFIG = {
    # Safer default for the lab GPU: large-v3 + VLM inference can exhaust CUDA memory.
    # You can override with environment variables, for example:
    #   AMECA_WHISPER_MODEL=large-v3 AMECA_WHISPER_DEVICE=cuda python deep3.py
    "profile": "safe_gpu_with_cpu_fallback",
    "model": os.environ.get("AMECA_WHISPER_MODEL", "small"),
    "device": os.environ.get("AMECA_WHISPER_DEVICE", "cuda" if torch.cuda.is_available() else "cpu"),
    "compute_type": os.environ.get("AMECA_WHISPER_COMPUTE", "float16" if torch.cuda.is_available() else "int8"),
    "language": "en",
    "beam_size": 1,
    "vad_filter": False,
}

# If CUDA runs out of memory during transcription, switch to CPU/int8 instead of crashing.
ENABLE_WHISPER_CPU_FALLBACK_ON_OOM = True
WHISPER_CPU_FALLBACK_MODEL = os.environ.get("AMECA_WHISPER_CPU_FALLBACK_MODEL", "small")

# SCHOOL / GPU CONFIG
# FAST_WHISPER_CONFIG = {
#     "profile": "school_gpu",
#     "model": "small",
#     "device": "cuda",
#     "compute_type": "float16",
#     "language": "en",
#     "beam_size": 1,
#     "vad_filter": False,
# }


# =========================
# Audio / Silero VAD configuration
# =========================

TARGET_SAMPLE_RATE = 16000
INPUT_DEVICE: Optional[int] = None

# Silero VAD works best with 16kHz audio and 512-sample chunks.
SILERO_SAMPLE_RATE = 16000
SILERO_CHUNK_SIZE = 512

# Sensitivity threshold. Lower = more sensitive. Higher = less false triggering.
SILERO_THRESHOLD = 0.55

# Silero internal timing. These are in milliseconds.
SILERO_MIN_SILENCE_DURATION_MS = 1200
SILERO_SPEECH_PAD_MS = 250

# Extra utterance controls.
VAD_MAX_UTTERANCE_SECONDS = 30.0
VAD_MIN_UTTERANCE_SECONDS = 0.60
VAD_PRE_ROLL_SECONDS = 0.35

MIN_PEAK_THRESHOLD = 0.01
MIN_RMS_THRESHOLD = 0.003


# =========================
# Camera / VLM face-emotion configuration
# =========================

# =========================
# Camera / VLM face-emotion configuration
# =========================

CAMERA_DEVICE: Optional[int] = 0 if IS_LINUX else 0

# ZED stereo frame is side-by-side.
# 2560x720 means each eye becomes 1280x720 after cropping.
ZED_STEREO_WIDTH = 2560
ZED_STEREO_HEIGHT = 720

CAMERA_FRAME_WIDTH = ZED_STEREO_WIDTH if IS_LINUX else 1280
CAMERA_FRAME_HEIGHT = ZED_STEREO_HEIGHT if IS_LINUX else 720

CAMERA_PREVIEW_WIDTH = 960
CAMERA_PREVIEW_HEIGHT = 540

CAMERA_PREVIEW_ENABLED = True
CAMERA_PREVIEW_WINDOW_NAME = "Camera Preview - press q to close preview"

USE_ZED_HALF_FRAME_CROP = IS_LINUX

# VLM frames are sampled during the detected speech window, not while waiting for speech.
# Keep this lower frequency than DeepFace because a VLM call is heavier.
CAMERA_SAMPLE_EVERY_SECONDS = float(os.environ.get("AMECA_VLM_SAMPLE_EVERY_SECONDS", "0.8"))
CAMERA_WARMUP_SECONDS = 0.4

# Ollama VLM used for non-blocking facial-expression inference.
VLM_FACE_MODEL_NAME = os.environ.get("AMECA_VLM_FACE_MODEL", "qwen2.5vl:7b")
VLM_FACE_QUEUE_SIZE = 1
VLM_RESULT_QUEUE_SIZE = 4
VLM_IMAGE_MAX_WIDTH = int(os.environ.get("AMECA_VLM_IMAGE_MAX_WIDTH", "640"))
VLM_JPEG_QUALITY = int(os.environ.get("AMECA_VLM_JPEG_QUALITY", "75"))

# Reliability filter. VLM confidence is normalized from 0.0 to 1.0.
FACE_MIN_TOP_SCORE = 0.65
FACE_MIN_MARGIN = 0.20

VLM_FACE_WORKER: Optional["VLMFaceEmotionWorker"] = None


# =========================
# Chat configuration
# =========================

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy": "😊",
    "trust": "🙂",
    "fear": "😨",
    "surprise": "😮",
    "sadness": "😢",
    "disgust": "🤢",
    "anger": "😠",
    "anticipation": "🤔",
    "neutral": "🙂",
}

ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())


# =========================
# Conversation turn-taking feedback
# =========================

class ConversationState:
    IDLE = "idle"
    LISTENING = "listening"
    RECORDING = "recording"
    PROCESSING = "processing"
    SPEAKING = "speaking"


CURRENT_CONVERSATION_STATE = ConversationState.IDLE


def set_conversation_state(state: str, message: Optional[str] = None) -> None:
    """
    Update the visible conversation state.

    This is intentionally simple because the prototype uses terminal output
    and an OpenCV preview window rather than a full robot behavior controller.
    """
    global CURRENT_CONVERSATION_STATE
    CURRENT_CONVERSATION_STATE = state

    if message:
        print_ts(message)


def hand_turn_back_to_user() -> None:
    """Give a non-spoken terminal cue that the user may speak.

    In normal conversation, Ameca should not repeatedly say things like
    "I am listening", "I am processing", or "Your turn". The spoken
    response itself hands the turn back. This function only prints a simple
    terminal prompt for the operator/user.
    """
    set_conversation_state(ConversationState.LISTENING)
    print()
    print("You:")

def state_display_text() -> str:
    labels = {
        ConversationState.IDLE: "State: Waiting",
        ConversationState.LISTENING: "State: Listening - you may speak",
        ConversationState.RECORDING: "State: Recording speech",
        ConversationState.PROCESSING: "State: Processing",
        ConversationState.SPEAKING: "State: Speaking",
    }
    return labels.get(CURRENT_CONVERSATION_STATE, f"State: {CURRENT_CONVERSATION_STATE}")


@dataclass
class EmotionResult:
    emotion: str
    confidence: float
    reason: str


@dataclass
class FaceEmotionCapture:
    vlm_results: list[dict]
    frame_count: int
    submitted_frame_count: int
    started_at: str
    ended_at: str
    error: Optional[str] = None

    @property
    def latest_result(self) -> Optional[dict]:
        if not self.vlm_results:
            return None
        return self.vlm_results[-1]

    @property
    def dominant_emotion(self) -> Optional[str]:
        result = self.latest_result
        if not result:
            return None
        emotion = str(result.get("emotion", "")).strip().lower()
        return emotion if emotion in PLUTCHIK_EMOTIONS else None

    @property
    def confidence(self) -> float:
        result = self.latest_result
        if not result:
            return 0.0
        try:
            return max(0.0, min(1.0, float(result.get("confidence", 0.0))))
        except Exception:
            return 0.0

    @property
    def is_reliable(self) -> bool:
        return self.dominant_emotion is not None and self.confidence >= FACE_MIN_TOP_SCORE

    @property
    def summary_text(self) -> str:
        if self.error:
            return f"No facial-expression hint available because: {self.error}"

        result = self.latest_result
        if not result:
            return "No reliable facial-expression hint was captured during speech."

        emotion = self.dominant_emotion or "neutral"
        reason = str(result.get("reason", "")).strip()
        if not self.is_reliable:
            return (
                "Facial-expression hint from VLM was weak or uncertain; "
                f"top_signal={emotion}; confidence={self.confidence:.2f}; "
                f"reason={reason}; samples={self.submitted_frame_count}"
            )

        return (
            f"dominant={emotion}; confidence={self.confidence:.2f}; "
            f"reason={reason}; samples={self.submitted_frame_count}"
        )

    @property
    def as_json(self) -> dict:
        result = self.latest_result or {}
        return {
            "available": self.error is None and bool(result),
            "reliable": self.is_reliable,
            "backend": "ollama_vlm",
            "model": VLM_FACE_MODEL_NAME,
            "dominant_emotion": self.dominant_emotion,
            "confidence": self.confidence,
            "reason": result.get("reason"),
            "raw_result": result,
            "frame_count": self.frame_count,
            "submitted_frame_count": self.submitted_frame_count,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "error": self.error,
            "note": (
                "Facial expression analysis is a weak supporting signal only. "
                "Text-based emotion should remain the primary signal."
            ),
        }


# =========================
# Timestamp helpers
# =========================

def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")


def normalize_command(text: str) -> Optional[str]:
    stripped = text.strip().lower()
    if not stripped.startswith(("/", "\\")):
        return None
    return re.sub(r"^[\\/]+", "", stripped)


def default_face_emotion_json() -> dict:
    return {
        "available": False,
        "reliable": False,
        "backend": "ollama_vlm",
        "model": VLM_FACE_MODEL_NAME,
        "dominant_emotion": None,
        "confidence": 0.0,
        "reason": None,
        "raw_result": {},
        "frame_count": 0,
        "submitted_frame_count": 0,
        "started_at": None,
        "ended_at": None,
        "error": "No face emotion capture was provided.",
    }


# =========================
# Persistent memory helpers
# =========================

def ensure_data_dirs() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(SESSIONS_DIR, exist_ok=True)


def slugify_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    return name.strip("_") or "unknown_user"


def load_users() -> dict:
    ensure_data_dirs()

    if not os.path.exists(USERS_FILE):
        return {}

    try:
        with open(USERS_FILE, "r", encoding="utf-8") as file:
            return json.load(file)
    except json.JSONDecodeError:
        return {}


def save_users(users: dict) -> None:
    ensure_data_dirs()

    with open(USERS_FILE, "w", encoding="utf-8") as file:
        json.dump(users, file, indent=2, ensure_ascii=False)


def clean_spoken_name(spoken_name: str) -> str:
    spoken_name = spoken_name.strip()

    patterns = [
        r"^my name is\s+",
        r"^my name's\s+",
        r"^i am\s+",
        r"^i'm\s+",
        r"^this is\s+",
        r"^it is\s+",
        r"^it's\s+",
        r"^call me\s+",
    ]

    for pattern in patterns:
        spoken_name = re.sub(pattern, "", spoken_name, flags=re.IGNORECASE).strip()

    spoken_name = re.sub(r"[^a-zA-Z0-9\s\-]", "", spoken_name)
    spoken_name = spoken_name[:40].strip()

    return spoken_name or "Guest"


def clean_spelled_name(text: str) -> Optional[str]:
    """
    Convert a spelling transcript like:
      "L E T I C I A"
    into:
      "Leticia"

    faster-whisper may output punctuation or words around the spelling;
    this function keeps only standalone letters.
    """
    text = text.upper().strip()

    text = re.sub(r"\bMY NAME IS\b", "", text)
    text = re.sub(r"\bIT IS\b", "", text)
    text = re.sub(r"\bIT'S\b", "", text)
    text = re.sub(r"\bSPELL(?:ED|ING)?\b", "", text)
    text = re.sub(r"[^A-Z\s]", " ", text)

    parts = text.split()

    letters = []
    for part in parts:
        if len(part) == 1 and part.isalpha():
            letters.append(part)

    if len(letters) >= 2:
        return "".join(letters).title()

    return None


def normalized_name_similarity(left: str, right: str) -> float:
    """Return a simple similarity score between two names, without extra dependencies."""
    left = re.sub(r"[^a-z]", "", left.lower())
    right = re.sub(r"[^a-z]", "", right.lower())

    if not left or not right:
        return 0.0

    # Dynamic-programming Levenshtein distance.
    previous = list(range(len(right) + 1))
    for i, c1 in enumerate(left, start=1):
        current = [i]
        for j, c2 in enumerate(right, start=1):
            insert_cost = current[j - 1] + 1
            delete_cost = previous[j] + 1
            replace_cost = previous[j - 1] + (c1 != c2)
            current.append(min(insert_cost, delete_cost, replace_cost))
        previous = current

    distance = previous[-1]
    longest = max(len(left), len(right))
    return 1.0 - (distance / longest)


def choose_best_name(spoken_name: str, spelled_name: Optional[str]) -> str:
    """
    Pick a stable display name after the introduction phase.

    Why:
    - Whisper can mishear a clearly spoken name as "Let it show".
    - It can also mishear one letter during spelling, e.g. "L E T I C I E" -> "Leticie".
    - If the spoken introduction was explicit and the spelled result is close, prefer the spoken name.
    - If the spoken result looks invalid, prefer the spelled name.
    """
    spoken_name = clean_spoken_name(spoken_name or "")

    if not spelled_name:
        return spoken_name if spoken_name and not looks_like_invalid_name(spoken_name) else "Guest"

    if not spoken_name or looks_like_invalid_name(spoken_name):
        return spelled_name

    similarity = normalized_name_similarity(spoken_name, spelled_name)

    # If both are almost the same, prefer the normal spoken form.
    # Example: spoken="Leticia", spelled="Leticie" -> choose "Leticia".
    if similarity >= 0.75:
        print_ts(
            f"Spoken name '{spoken_name}' and spelled name '{spelled_name}' are close; "
            f"using spoken name '{spoken_name}'."
        )
        return spoken_name

    # If they are very different, the spoken ASR was probably wrong.
    print_ts(
        f"Spoken name '{spoken_name}' and spelled name '{spelled_name}' differ; "
        f"using spelled name '{spelled_name}'."
    )
    return spelled_name


def extract_name_from_text(text: str) -> Optional[str]:
    """
    Extract names only from explicit name-introduction phrases.

    Important:
    We intentionally do NOT support "I am ..." or "I'm ..." here because
    normal phrases like "I'm happy" could be incorrectly treated as a name.
    """
    text = text.strip()

    patterns = [
        r"\bmy name is\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bmy name's\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
        r"\bcall me\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
    ]

    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            candidate = clean_spoken_name(match.group(1))

            words = candidate.split()
            if 1 <= len(words) <= 4:
                return candidate

    return None


def looks_like_invalid_name(name: str) -> bool:
    invalid = {
        "hello",
        "hi",
        "hey",
        "good morning",
        "good afternoon",
        "good evening",
        "yes",
        "no",
        "okay",
        "ok",
        "thanks",
        "thank you",
        "bye",
        "goodbye",
    }

    return name.strip().lower() in invalid


def rename_current_user(
    old_user_key: str,
    user_profile: dict,
    new_name: str,
) -> tuple[str, dict]:
    users = load_users()

    new_name = clean_spoken_name(new_name)
    new_key = slugify_name(new_name)

    if not new_name or looks_like_invalid_name(new_name):
        return old_user_key, user_profile

    existing_profile = users.get(new_key)

    if existing_profile:
        existing_profile["last_seen"] = now_ts()
        print_ts(f"Switched to existing user profile: {existing_profile['name']}")
        save_users(users)
        return new_key, existing_profile

    old_profile = users.pop(old_user_key, user_profile)

    old_profile["name"] = new_name
    old_profile["last_seen"] = now_ts()
    users[new_key] = old_profile

    save_users(users)

    print_ts(f"Updated user name to: {new_name}")
    return new_key, users[new_key]


def build_user_memory_context(user_profile: Optional[dict]) -> str:
    if not user_profile:
        return ""

    name = user_profile.get("name", "the user")
    summary = user_profile.get("conversation_summary", "").strip()

    if not summary:
        summary = "No previous conversation summary is available."

    return f"""
        USER MEMORY CONTEXT
        The user's name is {name}.

        Previous conversation summary:
        {summary}

        Rules:
        - Use the user's name naturally when appropriate.
        - Do not claim to remember anything beyond this saved local JSON context.
        - Do not reveal the raw JSON file unless the user asks.
        """.strip()


def save_session_transcript(
    user_key: str,
    user_profile: dict,
    session_log: list[dict],
) -> str:
    ensure_data_dirs()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{user_key}_{timestamp}.json"
    path = os.path.join(SESSIONS_DIR, filename)

    transcript_data = {
        "user": {
            "key": user_key,
            "name": user_profile.get("name", "Guest"),
        },
        "session": {
            "started_at": session_log[0]["timestamp"] if session_log else now_ts(),
            "ended_at": now_ts(),
            "model": MODEL_NAME,
            "ollama_host": OLLAMA_HOST,
            "asr": {
                "backend": "faster-whisper",
                **FAST_WHISPER_CONFIG,
            },
            "face_emotion": {
                "backend": "ollama_vlm",
                "model": VLM_FACE_MODEL_NAME,
                "camera_device": CAMERA_DEVICE,
                "camera_frame_width": CAMERA_FRAME_WIDTH,
                "camera_frame_height": CAMERA_FRAME_HEIGHT,
                "preview_enabled": CAMERA_PREVIEW_ENABLED,
                "sample_every_seconds": CAMERA_SAMPLE_EVERY_SECONDS,
                "warmup_seconds": CAMERA_WARMUP_SECONDS,
                "image_max_width": VLM_IMAGE_MAX_WIDTH,
                "jpeg_quality": VLM_JPEG_QUALITY,
                "min_confidence": FACE_MIN_TOP_SCORE,
            },
            "vad": {
                "backend": "Silero VAD",
                "sample_rate": SILERO_SAMPLE_RATE,
                "chunk_size": SILERO_CHUNK_SIZE,
                "threshold": SILERO_THRESHOLD,
                "min_silence_duration_ms": SILERO_MIN_SILENCE_DURATION_MS,
                "speech_pad_ms": SILERO_SPEECH_PAD_MS,
                "max_utterance_seconds": VAD_MAX_UTTERANCE_SECONDS,
                "min_utterance_seconds": VAD_MIN_UTTERANCE_SECONDS,
                "pre_roll_seconds": VAD_PRE_ROLL_SECONDS,
            },
        },
        "messages": session_log,
    }

    with open(path, "w", encoding="utf-8") as file:
        json.dump(transcript_data, file, indent=2, ensure_ascii=False)

    return path


def summarize_session_with_llm(
    client: Client,
    session_log: list[dict],
    previous_summary: str = "",
) -> str:
    if not session_log:
        return previous_summary

    compact_messages = []

    for item in session_log[-20:]:
        role = item.get("role", "")
        content = item.get("content", "")
        compact_messages.append(f"{role}: {content}")

    prompt = f"""
Summarize this human-robot conversation for future continuity.

Previous saved summary:
{previous_summary or "None"}

Recent session:
{chr(10).join(compact_messages)}

Return a concise memory summary in 3-6 bullet points.

Include only:
- user's name if known
- main topics discussed
- useful preferences or ongoing tasks
- emotional context if relevant

Do not invent facts.
""".strip()

    try:
        response = client.chat(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "system",
                    "content": "You summarize conversations accurately and concisely.",
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
            options={
                "temperature": 0.2,
                "num_predict": 180,
                "num_ctx": 2048,
            },
            stream=False,
        )

        return response["message"]["content"].strip()

    except KeyboardInterrupt:
        print_ts("Summary generation interrupted. Transcript was still saved.")
        return previous_summary

    except Exception as exc:
        print_ts(f"Could not summarize session: {exc}")
        return previous_summary


def update_user_after_session(
    client: Client,
    user_key: str,
    session_path: str,
    session_log: list[dict],
) -> None:
    users = load_users()

    if user_key not in users:
        return

    users[user_key]["last_seen"] = now_ts()
    users[user_key].setdefault("session_files", []).append(session_path)

    if ENABLE_LLM_SESSION_SUMMARY:
        previous_summary = users[user_key].get("conversation_summary", "")
        users[user_key]["conversation_summary"] = summarize_session_with_llm(
            client=client,
            session_log=session_log,
            previous_summary=previous_summary,
        )
    else:
        print_ts("Skipping LLM session summary for faster shutdown.")

    save_users(users)


# =========================
# Ollama setup helpers
# =========================

def check_ollama_available(max_attempts: int = 10, delay_seconds: float = 1.0) -> None:
    client = Client(host=OLLAMA_HOST)

    for attempt in range(1, max_attempts + 1):
        try:
            client.list()
            print_ts(f"Ollama is reachable at {OLLAMA_HOST}.")
            return
        except Exception as exc:
            print_ts(f"Ollama not reachable yet, attempt {attempt}/{max_attempts}: {exc}")
            time.sleep(delay_seconds)

    raise RuntimeError(
        f"Could not connect to Ollama at {OLLAMA_HOST} after {max_attempts} attempts."
    )


def ensure_model_available(model_name: str = MODEL_NAME) -> None:
    print_ts(f"Using Ollama model '{model_name}' from {OLLAMA_HOST}. Skipping local pull.")


# =========================
# Audio helpers
# =========================

def list_input_devices() -> None:
    print("\nAvailable input devices:")

    try:
        devices = sd.query_devices()
        hostapis = sd.query_hostapis()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return

    found = False

    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            found = True
            hostapi_name = hostapis[device["hostapi"]]["name"]
            print(
                f"[mic {idx}] {device['name']} | "
                f"hostapi={hostapi_name} | "
                f"inputs={device['max_input_channels']} | "
                f"default_sr={device['default_samplerate']}"
            )

    if not found:
        print("No input devices found.")

    print()
    print(f"Current default audio device: {sd.default.device}")
    print()


def get_input_samplerate(input_device: Optional[int]) -> int:
    if input_device is None:
        device_info = sd.query_devices(kind="input")
    else:
        device_info = sd.query_devices(input_device)

    default_sr = int(round(device_info["default_samplerate"]))
    if default_sr <= 0:
        return TARGET_SAMPLE_RATE

    return default_sr


def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32, copy=False)

    if audio.size == 0:
        return audio.astype(np.float32, copy=False)

    duration = len(audio) / original_sr
    target_length = max(1, int(round(duration * target_sr)))

    old_times = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_times = np.linspace(0.0, duration, num=target_length, endpoint=False)

    return np.interp(new_times, old_times, audio).astype(np.float32)


def save_audio_to_temp_wav(audio_16k: np.ndarray) -> Optional[str]:
    if audio_16k.size == 0:
        return None

    peak = float(np.max(np.abs(audio_16k)))
    rms = float(np.sqrt(np.mean(audio_16k ** 2)))

    print_ts(f"Captured utterance audio level: peak={peak:.4f}, rms={rms:.4f}")

    if peak < MIN_PEAK_THRESHOLD or rms < MIN_RMS_THRESHOLD:
        print("Captured audio was too quiet or silent.")
        return None

    audio_16k = np.clip(audio_16k * min(0.9 / max(peak, 1e-6), 10.0), -1.0, 1.0)

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        wav_path = tmp.name

    sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
    return wav_path


class SafeWhisperTranscriber:
    """
    Small wrapper around faster-whisper.
    - VLM inference and faster-whisper can compete for CUDA memory.
    - If CUDA runs out of memory, the old script crashed and saved the session early.
    - This wrapper catches CUDA OOM, releases CUDA cache, loads a CPU/int8 model,
      and continues the conversation.
    """

    def __init__(self, config: dict) -> None:
        self.config = dict(config)
        self.model: Optional[WhisperModel] = None
        self.load_model(self.config)

    def load_model(self, config: dict) -> None:
        self.config = dict(config)
        print_ts(
            "Loading faster-whisper model "
            f"{self.config['model']} on {self.config['device']} "
            f"with compute_type={self.config['compute_type']}..."
        )
        self.model = WhisperModel(
            self.config["model"],
            device=self.config["device"],
            compute_type=self.config["compute_type"],
        )
        print_ts(
            "faster-whisper ready: "
            f"model={self.config['model']}, "
            f"device={self.config['device']}, "
            f"compute_type={self.config['compute_type']}"
        )

    def switch_to_cpu_fallback(self) -> None:
        if not ENABLE_WHISPER_CPU_FALLBACK_ON_OOM:
            raise RuntimeError("Whisper CUDA OOM and CPU fallback is disabled.")

        print_ts(
            "Whisper CUDA ran out of memory. "
            "Switching faster-whisper to CPU/int8 so the conversation can continue."
        )

        try:
            self.model = None
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                torch.cuda.ipc_collect()
        except Exception:
            pass

        fallback_config = dict(self.config)
        fallback_config["model"] = WHISPER_CPU_FALLBACK_MODEL
        fallback_config["device"] = "cpu"
        fallback_config["compute_type"] = "int8"
        self.load_model(fallback_config)

    def transcribe_text(self, wav_path: str) -> str:
        if self.model is None:
            self.load_model(self.config)

        try:
            segments, info = self.model.transcribe(
                wav_path,
                language=self.config.get("language"),
                beam_size=int(self.config.get("beam_size", 1)),
                vad_filter=bool(self.config.get("vad_filter", False)),
                condition_on_previous_text=False,
            )
            text = " ".join(segment.text.strip() for segment in segments).strip()

        except RuntimeError as exc:
            message = str(exc).lower()
            is_cuda_oom = "cuda" in message and ("out of memory" in message or "memory" in message)
            if not is_cuda_oom or self.config.get("device") == "cpu":
                raise
            self.switch_to_cpu_fallback()
            return self.transcribe_text(wav_path)

        text = re.sub(r"\s+", " ", text).strip()

        if len(text.split()) <= 1 and len(text) < 3:
            return ""

        return text


def transcribe_with_faster_whisper(wav_path: str, whisper_model) -> str:
    """Transcribe one utterance using SafeWhisperTranscriber or raw WhisperModel."""
    if hasattr(whisper_model, "transcribe_text"):
        return whisper_model.transcribe_text(wav_path)

    segments, info = whisper_model.transcribe(
        wav_path,
        language=FAST_WHISPER_CONFIG.get("language"),
        beam_size=int(FAST_WHISPER_CONFIG.get("beam_size", 1)),
        vad_filter=bool(FAST_WHISPER_CONFIG.get("vad_filter", False)),
        condition_on_previous_text=False,
    )

    text = " ".join(segment.text.strip() for segment in segments).strip()
    text = re.sub(r"\s+", " ", text).strip()

    if len(text.split()) <= 1 and len(text) < 3:
        return ""

    return text

# Backwards-compatible alias so the rest of the script stays readable.
transcribe_audio = transcribe_with_faster_whisper


# =========================
# Camera / VLM face-emotion helpers
# =========================

def normalize_camera_frame(frame: np.ndarray) -> np.ndarray:
    if USE_ZED_HALF_FRAME_CROP:
        height, width = frame.shape[:2]

        # ZED gives left + right images side by side.
        # Keep only the left camera image.
        frame = frame[:, : width // 2]

    return frame


def get_camera_backend() -> int:
    if sys.platform == "darwin":
        return cv2.CAP_AVFOUNDATION

    if sys.platform.startswith("linux"):
        return cv2.CAP_V4L2

    return cv2.CAP_ANY


def open_camera(camera_device: Optional[int]) -> cv2.VideoCapture:
    candidates = []

    if camera_device is not None:
        candidates.append(camera_device)

    candidates.extend([0, 1, 2, 3])

    seen = set()

    for camera_index in candidates:
        if camera_index in seen:
            continue

        seen.add(camera_index)

        cap = cv2.VideoCapture(camera_index, get_camera_backend())

        if not cap.isOpened():
            cap.release()
            continue

        # MJPG is important for high-resolution ZED over USB.
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_FRAME_HEIGHT)
        cap.set(cv2.CAP_PROP_FPS, 30)

        time.sleep(0.2)

        ok, frame = cap.read()

        if ok and frame is not None:
            actual_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            actual_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            print_ts(
                f"Using camera device /dev/video{camera_index} "
                f"at {actual_width}x{actual_height}"
            )
            return cap

        cap.release()

    return cv2.VideoCapture(-1)


def list_camera_devices(max_indices: int = 6) -> None:
    print("\nAvailable camera devices:")
    found = False

    for idx in range(max_indices):
        cap = open_camera(idx)
        try:
            if not cap.isOpened():
                continue

            ok, frame = cap.read()
            if ok and frame is not None:
                frame = normalize_camera_frame(frame)

            found = True
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            print(f"[cam {idx}] available | resolution={width}x{height}")
        finally:
            cap.release()

    if not found:
        print("No camera devices found.")

    print()


def resize_frame_for_vlm(frame_bgr: np.ndarray) -> np.ndarray:
    height, width = frame_bgr.shape[:2]
    if width <= VLM_IMAGE_MAX_WIDTH:
        return frame_bgr

    scale = VLM_IMAGE_MAX_WIDTH / float(width)
    new_size = (VLM_IMAGE_MAX_WIDTH, max(1, int(height * scale)))
    return cv2.resize(frame_bgr, new_size, interpolation=cv2.INTER_AREA)


def encode_frame_as_jpeg_base64(frame_bgr: np.ndarray) -> Optional[str]:
    frame_bgr = resize_frame_for_vlm(frame_bgr)
    ok, encoded = cv2.imencode(
        ".jpg",
        frame_bgr,
        [int(cv2.IMWRITE_JPEG_QUALITY), VLM_JPEG_QUALITY],
    )
    if not ok:
        return None
    return base64.b64encode(encoded.tobytes()).decode("utf-8")


def build_vlm_face_emotion_prompt() -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    return f"""
You are a cautious facial-expression observer for a human-robot interaction system.

Look at the image and estimate the user's visible facial expression only.
Use one closest label from this set: {emotions}.

Important rules:
- Return neutral if the face is unclear, not visible, occluded, or emotionally mild.
- Do not infer identity, age, gender, ethnicity, health, personality, or private traits.
- Do not overstate certainty. Facial expression is only a weak hint.
- Return JSON only.

Required JSON schema:
{{
  "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation | neutral",
  "confidence": 0.0,
  "reason": "brief visible-expression reason"
}}
""".strip()


class VLMFaceEmotionWorker:
    """Background Ollama VLM worker.

    The audio/VAD loop calls submit_frame() and never waits for Qwen2.5-VL.
    The worker keeps only the newest frame, so slow VLM inference cannot build a
    latency backlog. The final turn uses the latest completed VLM result, if one
    is available; otherwise it safely falls back to no facial-expression hint.
    """

    def __init__(self, host: str, model_name: str) -> None:
        self.host = host
        self.model_name = model_name
        self.input_queue: queue.Queue[Optional[np.ndarray]] = queue.Queue(maxsize=VLM_FACE_QUEUE_SIZE)
        self.result_queue: queue.Queue[dict] = queue.Queue(maxsize=VLM_RESULT_QUEUE_SIZE)
        self.stop_event = threading.Event()
        self.thread = threading.Thread(target=self._run, name="vlm-face-emotion-worker", daemon=True)

    def start(self) -> None:
        if not self.thread.is_alive():
            self.thread.start()
            print_ts(f"Started non-blocking VLM face-emotion worker with {self.model_name}.")

    def stop(self) -> None:
        self.stop_event.set()
        self._replace_pending_frame(None)
        self.thread.join(timeout=2.0)

    def submit_frame(self, frame_bgr: np.ndarray) -> None:
        # Copy now because OpenCV may reuse frame memory later.
        self._replace_pending_frame(frame_bgr.copy())

    def get_latest_result(self) -> Optional[dict]:
        latest = None
        while True:
            try:
                latest = self.result_queue.get_nowait()
            except queue.Empty:
                break
        return latest

    def _replace_pending_frame(self, frame: Optional[np.ndarray]) -> None:
        try:
            while True:
                self.input_queue.get_nowait()
        except queue.Empty:
            pass

        try:
            self.input_queue.put_nowait(frame)
        except queue.Full:
            pass

    def _put_result(self, result: dict) -> None:
        try:
            if self.result_queue.full():
                self.result_queue.get_nowait()
            self.result_queue.put_nowait(result)
        except queue.Empty:
            pass

    def _run(self) -> None:
        client = Client(host=self.host)
        prompt = build_vlm_face_emotion_prompt()

        while not self.stop_event.is_set():
            try:
                frame = self.input_queue.get(timeout=0.1)
            except queue.Empty:
                continue

            if frame is None:
                continue

            started = now_ts()
            try:
                image_b64 = encode_frame_as_jpeg_base64(frame)
                if not image_b64:
                    continue

                response = client.chat(
                    model=self.model_name,
                    format="json",
                    messages=[
                        {
                            "role": "user",
                            "content": prompt,
                            "images": [image_b64],
                        }
                    ],
                    stream=False,
                    options={
                        "temperature": 0.0,
                        "num_predict": 80,
                        "num_ctx": 1024,
                    },
                )

                raw = response["message"]["content"]
                data = safe_json_extract(raw) or {}
                emotion = str(data.get("emotion", "neutral")).strip().lower()
                if emotion not in PLUTCHIK_EMOTIONS:
                    emotion = "neutral"

                try:
                    confidence = max(0.0, min(1.0, float(data.get("confidence", 0.0))))
                except Exception:
                    confidence = 0.0

                self._put_result({
                    "emotion": emotion,
                    "confidence": confidence,
                    "reason": str(data.get("reason", "")).strip(),
                    "started_at": started,
                    "ended_at": now_ts(),
                    "backend": "ollama_vlm",
                    "model": self.model_name,
                })

            except Exception as exc:
                self._put_result({
                    "emotion": "neutral",
                    "confidence": 0.0,
                    "reason": f"VLM face-emotion inference failed: {exc}",
                    "started_at": started,
                    "ended_at": now_ts(),
                    "backend": "ollama_vlm",
                    "model": self.model_name,
                    "error": str(exc),
                })


class FaceEmotionSampler:
    def __init__(self, camera_device: Optional[int], vlm_worker: Optional[VLMFaceEmotionWorker]) -> None:
        self.camera_device = camera_device
        self.vlm_worker = vlm_worker
        self.cap: Optional[cv2.VideoCapture] = None
        self.window_created = False
        self.started_at = now_ts()
        self.error: Optional[str] = None
        self.vlm_results: list[dict] = []
        self.frame_count = 0
        self.submitted_frame_count = 0
        self.capture_start_time: Optional[float] = None
        self.last_sample_time = 0.0
        self.last_status = "warming up..."

    def start(self) -> None:
        self.started_at = now_ts()
        self.capture_start_time = time.time()

        if self.vlm_worker is None:
            self.error = "VLM face-emotion worker is not available."
            return

        self.cap = open_camera(self.camera_device)

        if not self.cap.isOpened():
            self.error = "Could not open camera."
            self.cap.release()
            self.cap = None
            return

        if CAMERA_PREVIEW_ENABLED:
            try:
                cv2.namedWindow(CAMERA_PREVIEW_WINDOW_NAME, cv2.WINDOW_NORMAL)
                self.window_created = True
            except Exception as exc:
                self.error = f"Camera preview could not start: {exc}"

    def sample_if_due(self) -> None:
        if self.vlm_worker is not None:
            latest = self.vlm_worker.get_latest_result()
            if latest:
                self.vlm_results.append(latest)
                emotion = latest.get("emotion", "neutral")
                confidence = float(latest.get("confidence", 0.0) or 0.0)
                self.last_status = f"{emotion}: {confidence:.2f}"

        if self.cap is None or self.capture_start_time is None:
            return

        ok, frame = self.cap.read()
        if not ok or frame is None:
            return

        frame = normalize_camera_frame(frame)

        self.frame_count += 1
        now = time.time()
        elapsed = now - self.capture_start_time

        if CAMERA_PREVIEW_ENABLED and self.window_created:
            try:
                preview_frame = frame.copy()
                cv2.putText(
                    preview_frame,
                    "Recording speech...",
                    (20, 35),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.8,
                    (0, 255, 0),
                    2,
                    cv2.LINE_AA,
                )
                cv2.putText(
                    preview_frame,
                    f"VLM emotion: {self.last_status}",
                    (20, 70),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.7,
                    (255, 255, 255),
                    2,
                    cv2.LINE_AA,
                )
                cv2.putText(
                    preview_frame,
                    state_display_text(),
                    (20, 105),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.7,
                    (255, 255, 255),
                    2,
                    cv2.LINE_AA,
                )
                preview_frame = cv2.resize(
                    preview_frame,
                    (CAMERA_PREVIEW_WIDTH, CAMERA_PREVIEW_HEIGHT),
                )
                cv2.imshow(CAMERA_PREVIEW_WINDOW_NAME, preview_frame)
                cv2.waitKey(1)
            except Exception as exc:
                self.error = f"Camera preview failed: {exc}"

        should_sample = (
            elapsed >= CAMERA_WARMUP_SECONDS
            and now - self.last_sample_time >= CAMERA_SAMPLE_EVERY_SECONDS
        )

        if not should_sample:
            return

        self.last_sample_time = now
        self.submitted_frame_count += 1

        # Non-blocking: submit and immediately return to audio/VAD processing.
        self.vlm_worker.submit_frame(frame)
        self.last_status = "submitted frame to VLM"

    def finish(self) -> FaceEmotionCapture:
        if self.vlm_worker is not None:
            latest = self.vlm_worker.get_latest_result()
            if latest:
                self.vlm_results.append(latest)

        if self.cap is not None:
            self.cap.release()
            self.cap = None

        if self.window_created:
            try:
                cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME)
                cv2.waitKey(1)
            except Exception:
                pass

        return FaceEmotionCapture(
            vlm_results=self.vlm_results,
            frame_count=self.frame_count,
            submitted_frame_count=self.submitted_frame_count,
            started_at=self.started_at,
            ended_at=now_ts(),
            error=self.error,
        )


# =========================
# Silero VAD listener
# =========================

def listen_for_utterance_with_silero_vad(
    input_device: Optional[int],
    silero_model,
    prompt_label: str = "utterance",
    announce_feedback: bool = False,
) -> Optional[str]:
    input_sample_rate = get_input_samplerate(input_device)
    input_block_size = max(1, int(input_sample_rate * 0.05))
    audio_queue: queue.Queue[np.ndarray] = queue.Queue()

    vad_iterator = VADIterator(
        silero_model,
        threshold=SILERO_THRESHOLD,
        sampling_rate=SILERO_SAMPLE_RATE,
        min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
        speech_pad_ms=SILERO_SPEECH_PAD_MS,
    )

    pre_roll_max_chunks = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll_chunks: list[np.ndarray] = []
    recorded_chunks: list[np.ndarray] = []

    is_recording = False
    speech_started_at: Optional[float] = None
    leftover_16k = np.array([], dtype=np.float32)

    def audio_callback(indata, frames, callback_time, status) -> None:
        audio_queue.put(indata[:, 0].copy())

    if announce_feedback:
        set_conversation_state(ConversationState.LISTENING, f"Ameca: I am listening for {prompt_label}. Speak when you are ready. Press Ctrl+C to quit.")
    else:
        set_conversation_state(ConversationState.LISTENING)
    #print_ts(
    #    f"Silero VAD settings: threshold={SILERO_THRESHOLD}, "
    #    f"min_silence={SILERO_MIN_SILENCE_DURATION_MS}ms, "
    #    f"max_utterance={VAD_MAX_UTTERANCE_SECONDS}s"
    #)

    try:
        sd.check_input_settings(
            device=input_device,
            samplerate=input_sample_rate,
            channels=1,
            dtype="float32",
        )

        with sd.InputStream(
            samplerate=input_sample_rate,
            channels=1,
            dtype="float32",
            device=input_device,
            blocksize=input_block_size,
            callback=audio_callback,
        ):
            while True:
                try:
                    block = audio_queue.get(timeout=0.1)
                except queue.Empty:
                    continue

                block_16k = resample_audio(block, input_sample_rate, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover_16k, block_16k]).astype(np.float32, copy=False)

                usable_len = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable_len == 0:
                    leftover_16k = combined
                    continue

                chunks = combined[:usable_len].reshape(-1, SILERO_CHUNK_SIZE)
                leftover_16k = combined[usable_len:]

                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)

                    if not is_recording:
                        pre_roll_chunks.append(chunk.copy())
                        if len(pre_roll_chunks) > pre_roll_max_chunks:
                            pre_roll_chunks.pop(0)
                    else:
                        recorded_chunks.append(chunk.copy())

                    speech_event = vad_iterator(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()

                    if speech_event:
                        if "start" in speech_event and not is_recording:
                            is_recording = True
                            speech_started_at = now
                            recorded_chunks = list(pre_roll_chunks)
                            recorded_chunks.append(chunk.copy())
                            pre_roll_chunks.clear()

                            print()
                            if announce_feedback:
                                set_conversation_state(ConversationState.RECORDING, "Ameca: I hear you. Recording your speech...")
                            else:
                                set_conversation_state(ConversationState.RECORDING)

                        if "end" in speech_event and is_recording:
                            utterance_duration = now - (speech_started_at or now)

                            if utterance_duration >= VAD_MIN_UTTERANCE_SECONDS:
                                if announce_feedback:
                                    set_conversation_state(ConversationState.PROCESSING, "Ameca: Thanks. I am processing what you said...")
                                else:
                                    set_conversation_state(ConversationState.PROCESSING)
                                raise StopIteration

                    if is_recording and speech_started_at is not None:
                        if now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                            if announce_feedback:
                                set_conversation_state(ConversationState.PROCESSING, "Ameca: I reached the maximum speaking time, so I am processing what I heard...")
                            else:
                                set_conversation_state(ConversationState.PROCESSING)
                            raise StopIteration

    except StopIteration:
        pass
    except KeyboardInterrupt:
        raise
    except Exception as exc:
        print_ts(f"Silero VAD/audio error: {exc}")
        return None
    finally:
        try:
            vad_iterator.reset_states()
        except Exception:
            pass

    if not recorded_chunks:
        return None

    audio_16k = np.concatenate(recorded_chunks).astype(np.float32, copy=False)
    return save_audio_to_temp_wav(audio_16k)


def listen_for_utterance_with_silero_vad_and_face_emotion(
    input_device: Optional[int],
    silero_model,
    camera_device: Optional[int] = CAMERA_DEVICE,
    vlm_worker: Optional[VLMFaceEmotionWorker] = None,
    prompt_label: str = "utterance",
    announce_feedback: bool = False,
) -> Tuple[Optional[str], Optional[FaceEmotionCapture]]:
    input_sample_rate = get_input_samplerate(input_device)
    input_block_size = max(1, int(input_sample_rate * 0.05))
    audio_queue: queue.Queue[np.ndarray] = queue.Queue()

    vad_iterator = VADIterator(
        silero_model,
        threshold=SILERO_THRESHOLD,
        sampling_rate=SILERO_SAMPLE_RATE,
        min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
        speech_pad_ms=SILERO_SPEECH_PAD_MS,
    )

    pre_roll_max_chunks = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll_chunks: list[np.ndarray] = []
    recorded_chunks: list[np.ndarray] = []

    is_recording = False
    speech_started_at: Optional[float] = None
    leftover_16k = np.array([], dtype=np.float32)
    face_sampler: Optional[FaceEmotionSampler] = None
    face_capture: Optional[FaceEmotionCapture] = None

    def audio_callback(indata, frames, callback_time, status) -> None:
        audio_queue.put(indata[:, 0].copy())

    if announce_feedback:
        set_conversation_state(ConversationState.LISTENING, f"Ameca: I am listening for {prompt_label}. Speak when you are ready. Press Ctrl+C to quit.")
        print_ts(
            f"Silero VAD settings: threshold={SILERO_THRESHOLD}, "
            f"min_silence={SILERO_MIN_SILENCE_DURATION_MS}ms, "
            f"max_utterance={VAD_MAX_UTTERANCE_SECONDS}s"
        )
    else:
        set_conversation_state(ConversationState.LISTENING)

    try:
        sd.check_input_settings(
            device=input_device,
            samplerate=input_sample_rate,
            channels=1,
            dtype="float32",
        )

        with sd.InputStream(
            samplerate=input_sample_rate,
            channels=1,
            dtype="float32",
            device=input_device,
            blocksize=input_block_size,
            callback=audio_callback,
        ):
            while True:
                try:
                    block = audio_queue.get(timeout=0.1)
                except queue.Empty:
                    if face_sampler is not None:
                        face_sampler.sample_if_due()
                    continue

                block_16k = resample_audio(block, input_sample_rate, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover_16k, block_16k]).astype(np.float32, copy=False)

                usable_len = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable_len == 0:
                    leftover_16k = combined
                    continue

                chunks = combined[:usable_len].reshape(-1, SILERO_CHUNK_SIZE)
                leftover_16k = combined[usable_len:]

                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)

                    if not is_recording:
                        pre_roll_chunks.append(chunk.copy())
                        if len(pre_roll_chunks) > pre_roll_max_chunks:
                            pre_roll_chunks.pop(0)
                    else:
                        recorded_chunks.append(chunk.copy())
                        if face_sampler is not None:
                            face_sampler.sample_if_due()

                    speech_event = vad_iterator(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()

                    if speech_event:
                        if "start" in speech_event and not is_recording:
                            is_recording = True
                            speech_started_at = now
                            recorded_chunks = list(pre_roll_chunks)
                            recorded_chunks.append(chunk.copy())
                            pre_roll_chunks.clear()

                            print()
                            if announce_feedback:
                                set_conversation_state(ConversationState.RECORDING, "Ameca: I hear you. Recording your speech and watching the conversation cues...")
                            else:
                                set_conversation_state(ConversationState.RECORDING)

                            face_sampler = FaceEmotionSampler(camera_device=camera_device, vlm_worker=vlm_worker)
                            face_sampler.start()
                            face_sampler.sample_if_due()

                        if "end" in speech_event and is_recording:
                            utterance_duration = now - (speech_started_at or now)

                            if utterance_duration >= VAD_MIN_UTTERANCE_SECONDS:
                                if announce_feedback:
                                    set_conversation_state(ConversationState.PROCESSING, "Ameca: Thanks. I am processing what you said...")
                                else:
                                    set_conversation_state(ConversationState.PROCESSING)
                                raise StopIteration

                    if is_recording and speech_started_at is not None:
                        if now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                            if announce_feedback:
                                set_conversation_state(ConversationState.PROCESSING, "Ameca: I reached the maximum speaking time, so I am processing what I heard...")
                            else:
                                set_conversation_state(ConversationState.PROCESSING)
                            raise StopIteration

    except StopIteration:
        pass
    except KeyboardInterrupt:
        raise
    except Exception as exc:
        print_ts(f"Silero VAD/audio/camera error: {exc}")
        return None, face_capture
    finally:
        if face_sampler is not None:
            face_capture = face_sampler.finish()

        try:
            vad_iterator.reset_states()
        except Exception:
            pass

    if not recorded_chunks:
        return None, face_capture

    audio_16k = np.concatenate(recorded_chunks).astype(np.float32, copy=False)
    return save_audio_to_temp_wav(audio_16k), face_capture


def ask_user_to_spell_name(
    whisper_model: WhisperModel,
    silero_model,
    input_device: Optional[int] = INPUT_DEVICE,
) -> Optional[str]:
    print()
    print_ts("Please spell your name letter by letter. For example: L E T I C I A.")
    print()

    wav_path = listen_for_utterance_with_silero_vad(
        input_device=input_device,
        silero_model=silero_model,
        prompt_label="spelled name",
    )

    if not wav_path:
        return None

    try:
        transcript = transcribe_audio(wav_path, whisper_model)
    finally:
        try:
            os.remove(wav_path)
        except OSError:
            pass

    print_ts(f"Raw spelling transcript: {transcript}")

    return clean_spelled_name(transcript)


def generate_introduction_response(
    client: Client,
    user_name: str,
) -> str:
    """
    Let the LLM introduce Ameca dynamically after the user gives their name.
    """
    system_prompt = f"""
        You are Ameca, a humanoid social robot in a university laboratory.

        A new user has just introduced themselves.

        Your task:
        - greet the user naturally
        - acknowledge the user's name naturally
        - do not introduce yourself again
        - keep it warm and concise
        - keep the response to 1 short sentence
        - mention the user's name
        - end with exactly one friendly facial emoji
        - only use this emoji: 🙂

        Do not:
        - sound robotic
        - repeat the user's exact words
        - mention prompts or instructions
        """.strip()

    try:
        response = client.chat(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": f"My name is {user_name}",
                },
            ],
            options={
                "temperature": 0.5,
                "num_predict": 60,
                "num_ctx": 1024,
            },
            stream=False,
        )

        raw_reply = response["message"]["content"]
        return normalize_reply(raw_reply, "trust")

    except Exception as exc:
        print_ts(f"Could not generate introduction with LLM: {exc}")
        return f"Thank you, {user_name}. It is nice to meet you. 🙂"


def prompt_for_user_name(
    client: Client,
    whisper_model: WhisperModel,
    silero_model,
    input_device: Optional[int] = INPUT_DEVICE,
) -> tuple[str, dict, str]:
    users = load_users()

    initial_intro_reply = (
        "Hello, I am Ameca, a humanoid social robot in this university laboratory. "
        "Before we begin, I would like to know your name. 🙂"
    )
    set_conversation_state(ConversationState.SPEAKING)
    print_ts(f"Ameca: {initial_intro_reply}")
    print()

    spoken_name = ""

    for attempt in range(2):
        print()
        print_ts("Please say your name")
        print()

        wav_path = listen_for_utterance_with_silero_vad(
            input_device=input_device,
            silero_model=silero_model,
            prompt_label="name",
            announce_feedback=True,
        )

        if not wav_path:
            spoken_name = ""
        else:
            try:
                spoken_name = transcribe_audio(
                    wav_path,
                    whisper_model,
                ).strip()
            finally:
                try:
                    os.remove(wav_path)
                except OSError:
                    pass

        print_ts(f"Raw name transcript: {spoken_name or '(empty)'}")

        extracted_name = extract_name_from_text(spoken_name)
        spoken_name = extracted_name or clean_spoken_name(spoken_name)

        if spoken_name and not looks_like_invalid_name(spoken_name):
            break

        print_ts(f"I heard '{spoken_name or 'nothing'}', but that does not sound like a name.")

    if not spoken_name or looks_like_invalid_name(spoken_name):
        spoken_name = "Guest"

    spelled_name = ask_user_to_spell_name(
        whisper_model=whisper_model,
        silero_model=silero_model,
        input_device=input_device,
    )

    chosen_name = choose_best_name(spoken_name, spelled_name)

    if spelled_name:
        print_ts(f"Spoken name candidate: {spoken_name}")
        print_ts(f"Spelled name candidate: {spelled_name}")
    else:
        print_ts(f"Using spoken name candidate: {spoken_name}")

    spoken_name = chosen_name
    print_ts(f"Detected name: {spoken_name}")

    user_key = slugify_name(spoken_name)

    is_new_user = user_key not in users

    if is_new_user:
        users[user_key] = {
            "name": spoken_name,
            "created_at": now_ts(),
            "last_seen": now_ts(),
            "session_files": [],
            "conversation_summary": "",
        }
    else:
        users[user_key]["last_seen"] = now_ts()

    save_users(users)

    if is_new_user:
        print_ts(f"Nice to meet you, {spoken_name}.")
    else:
        print_ts(f"Welcome back, {users[user_key]['name']}.")

    introduction_reply = generate_introduction_response(
        client=client,
        user_name=users[user_key]["name"],
    )

    set_conversation_state(ConversationState.SPEAKING)
    print_ts(f"Ameca: {introduction_reply}")
    hand_turn_back_to_user()
    print()

    return user_key, users[user_key], introduction_reply


# =========================
# JSON helpers
# =========================

def safe_json_extract(text: str) -> Optional[dict]:
    text = text.strip()

    text = re.sub(
        r"^```(?:json)?\s*|\s*```$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    ).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)

    if not match:
        return None

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


# =========================
# Emotion detection
# =========================

def build_emotion_prompt(
    transcribed_text: str,
    facial_emotion_hint: Optional[str] = None,
) -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    facial_section = (
        f"Facial-expression hint captured during speech: {facial_emotion_hint}\n"
        if facial_emotion_hint
        else "No facial-expression hint was available.\n"
    )

    return f"""
        You are an emotion classification system for a human-robot interaction chat system.

        Classify the user's emotional state from the text below.

        Map the emotion to the closest conversational label. Use neutral when the message is factual, unclear, short, or emotionally mild:

        {emotions}

        Use the user's words as the primary signal.
        Use the facial-expression hint only as a weak supporting signal.
        If the words and facial-expression hint conflict, trust the words more.
        Do not make strong claims from facial-expression analysis alone.

        Return JSON only.

        Required JSON schema:
        {{
        "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation | neutral",
        "confidence": 0.0,
        "reason": "short explanation"
        }}

        Rules:
        - confidence must be a number between 0.0 and 1.0
        - choose neutral for factual statements, short acknowledgements, unclear transcripts, fillers, corrections, and emotionally mild messages
        - do not infer anger, sadness, or disgust from hesitation alone
        - do not let facial expression override neutral or positive words unless the words clearly support it
        - do not add markdown
        - do not add extra text outside JSON
        - For greetings such as "hello", "hi", or "good morning", return:
        {{"emotion": "trust", "confidence": 0.6, "reason": "The user is opening a friendly social interaction."}}
        - For farewells such as "bye", "goodbye", "take care", or "talk later", return:
        {{"emotion": "trust", "confidence": 0.7, "reason": "The user is closing the conversation politely."}}

        User text:
        {transcribed_text}

        {facial_section}
        """.strip()


def simple_emotion_fallback(transcribed_text: str) -> Optional[EmotionResult]:
    text = transcribed_text.strip().lower()

    greetings = {"hello", "hi", "hey", "good morning", "good afternoon", "good evening"}
    farewells = {"bye", "goodbye", "see you", "see you later", "talk later", "have a good day", "have a nice day"}

    if text.rstrip(".!?") in greetings:
        return EmotionResult(
            emotion="trust",
            confidence=0.6,
            reason="The user is opening a friendly social interaction.",
        )

    if any(phrase in text for phrase in farewells):
        return EmotionResult(
            emotion="trust",
            confidence=0.7,
            reason="The user is closing the conversation politely.",
        )

    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return EmotionResult(
            emotion="anticipation",
            confidence=0.5,
            reason="The user is asking for current date information.",
        )

    neutral_patterns = [
        r"^(um+|uh+|mm+|mm-hmm|okay|ok|yeah|yes|no|sure)[.!?]*$",
        r"^just a quick chat[.!?]*$",
        r"^nothing( currently)?( on my mind)?( anyways?)?[.!?]*$",
        r"^i said .+",
        r"^.+ is okay[.!?]*$",
    ]
    if any(re.match(pattern, text) for pattern in neutral_patterns):
        return EmotionResult(
            emotion="neutral",
            confidence=0.75,
            reason="The message is short, corrective, factual, or emotionally mild.",
        )

    return None


def detect_emotion(
    client: Client,
    transcribed_text: str,
    facial_emotion_hint: Optional[str] = None,
) -> EmotionResult:
    fallback = simple_emotion_fallback(transcribed_text)
    if fallback:
        return fallback

    response = client.chat(
        model=MODEL_NAME,
        format="json",
        messages=[
            {
                "role": "system",
                "content": "You return valid JSON only.",
            },
            {
                "role": "user",
                "content": build_emotion_prompt(
                    transcribed_text=transcribed_text,
                    facial_emotion_hint=facial_emotion_hint,
                ),
            },
        ],
        stream=False,
        options={
            "temperature": 0.1,
            "num_predict": 120,
            "num_ctx": 2048,
        },
    )

    raw = response["message"]["content"]
    data = safe_json_extract(raw)

    if not data:
        return EmotionResult(
            emotion="neutral",
            confidence=0.3,
            reason="Could not parse model output, so a neutral fallback was used.",
        )

    emotion = str(data.get("emotion", "")).strip().lower()
    reason = str(data.get("reason", "")).strip()

    try:
        confidence = float(data.get("confidence", 0.0))
    except Exception:
        confidence = 0.0

    confidence = max(0.0, min(1.0, confidence))

    if emotion not in PLUTCHIK_EMOTIONS:
        emotion = "neutral"
        confidence = min(confidence, 0.3)
        reason = "Invalid emotion returned, so neutral fallback emotion was used."

    return EmotionResult(
        emotion=emotion,
        confidence=confidence,
        reason=reason or "Emotion inferred from the transcribed message.",
    )


# =========================
# Emoji enforcement
# =========================

def remove_all_emojis_except_allowed_faces(text: str) -> str:
    result = []

    for char in text:
        if char in ALLOWED_FACE_EMOJIS:
            result.append(char)
            continue

        code = ord(char)

        is_emoji_or_symbol = (
            0x1F300 <= code <= 0x1FAFF
            or 0x2600 <= code <= 0x27BF
            or code in {0x200D, 0xFE0F}
        )

        if is_emoji_or_symbol:
            continue

        result.append(char)

    return "".join(result)


def remove_allowed_face_emojis(text: str) -> str:
    return "".join(char for char in text if char not in ALLOWED_FACE_EMOJIS)


def normalize_reply(raw_reply: str, emotion: str) -> str:
    required_emoji = PLUTCHIK_EMOTIONS[emotion]

    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = remove_allowed_face_emojis(cleaned)

    # Keep the visible character as one speaker: Ameca.
    # The model sometimes says "As Ameca" or "As a robot" despite instructions.
    cleaned = re.sub(r"\bAs Ameca,?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bAs a humanoid social robot,?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bAs a robot,?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bAs an AI,?\s*", "", cleaned, flags=re.IGNORECASE)

    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)

    if not cleaned:
        cleaned = "I’m here with you."

    return f"{cleaned} {required_emoji}"


# =========================
# Date / time helpers
# =========================

def runtime_context() -> str:
    return f"""
        RUNTIME CONTEXT
        Current local date and time: {now_ts()}.
        Use this date/time when the user asks about today, now, or the current date.
        """.strip()


def deterministic_reply_if_applicable(user_text: str, emotion: str) -> Optional[str]:
    text = user_text.strip().lower()
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")

    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"

    if "what is the time" in text or "what time is it" in text or "current time" in text:
        return f"The current time is {datetime.now().strftime('%H:%M')}. {emoji}"

    farewell_words = {"bye", "goodbye", "see you", "see you later", "talk later", "have a nice day", "have a good day"}
    if any(phrase in text for phrase in farewell_words):
        return "Thank you, and take care. 🙂"

    return None


# =========================
# Response generation
# =========================

def build_response_system_prompt(
    emotion_result: EmotionResult,
    user_profile: Optional[dict] = None,
    face_emotion_json: Optional[dict] = None,
) -> str:
    emoji = PLUTCHIK_EMOTIONS[emotion_result.emotion]
    memory_context = build_user_memory_context(user_profile)

    if face_emotion_json is None:
        face_emotion_json = default_face_emotion_json()

    text_emotion_json = {
        "emotion": emotion_result.emotion,
        "confidence": emotion_result.confidence,
        "reason": emotion_result.reason,
    }

    return f"""
        {AMECA_SYSTEM_PROMPT}

        {runtime_context()}

        {memory_context}
        You are generating Ameca's next conversational response.

        PRIVATE EMOTION CONTEXT
        Use this context only for tone control only. Do not mention it directly.

        Text/LLM emotion JSON:
        {json.dumps(text_emotion_json, indent=2)}

        Face/VLM emotion JSON:
        {json.dumps(face_emotion_json, indent=2)}

        Interpretation rules:
        - Treat the Text/LLM emotion JSON as the primary emotional signal.
        - Treat the Face/VLM emotion JSON as a secondary weak supporting signal.
        - If both signals agree, you may gently adapt tone more confidently.
        - If both signals conflict, trust the text emotion more.
        - Do not mention camera, VLM, facial analysis, detected emotion, or private emotion context to the user.
        - Do not say things like "you look sad", "your face shows", or "I detected".

        Return JSON only in this exact shape:
        {{
        "reply": "assistant response without emoji",
        "emoji": "one facial emoji",
        "tone": "short tone label"
        }}

        Speech recognition note:
        - If the user says their name, update the profile silently and greet them by the corrected name.

        Conversation behavior rules:
        - Always ensure your response is context appropriate.
        - Always respond like a helpful assistant
        - Use the private emotion context only to adjust tone.
        - Use the recent conversation history to understand context and avoid repeating yourself.
        - Do not greet repeatedly. After the first greeting, respond directly to what the user said.
        - Do not say phrases like "your detected emotion", "you seem sad", "trust is present", or "you are anticipating".
        - Do not reintroduce yourself unless the user asks who you are.
        - Never say "As Ameca", "As a robot", "As an AI", "As a humanoid robot", or similar phrases. Speak naturally because you already are Ameca.
        - Do not invent current movies, news, people, dates, directors, or live facts. If live information is unavailable, say that you do not currently have access to live information.
        - If the user's meaning is unclear, ask one short clarification question instead of inventing context.
        - Use the user's name occasionally, not in every response.
        - Do not immediately give a list of advice unless the user asks for advice.
        - Speak directly and naturally.
        - Do not mention emotion labels unless the user explicitly asks.
        - Do not use markdown, bullets, numbered lists, or long advice unless the user asks for detail.
        - Do not repeat advice already given in the recent conversation.
        - Keep the response to 1-2 short sentences.
        - Avoid numbered lists unless the user explicitly asks for a list.
        - Ask at most one follow-up question.
        - Do not list any steps unless the user asks for detailed guidance.
        - If the user asks who can help, suggest concrete people: supervisor, co-supervisor, lab colleagues, thesis coordinator, or university writing center.

        Emoji rules:
        - Always end sentences with exactly one context appriopriate facial emoji.
        - Use gentle emojis for negative emotions.
        - Do not use emoji symbols
        - Do not overreact emotionally.
        - Use only one of these emojis: 🙂 😊 😌 😔 😟 🤔 😮 😢 😠 🤢
        - Emoji must appear only at the end of the sentences.

        Tone examples:
        - User: "I'm so tired and exhausted." -> reply should validate softly; emoji could be 😔 or 😌.
        - User: "I am very happy today." -> reply should celebrate the positive mood; emoji could be 😊.
        - User: "Well, I don't know." -> reply should stay with the uncertainty and ask gently; emoji could be 😟 or 🙂.
        """.strip()


def limit_text_length(text: str, max_chars: int = 1500) -> str:
    return text[:max_chars]


def limit_system_prompt(prompt: str, max_chars: int = 6000) -> str:
    return prompt[:max_chars]


def trim_history(history: list[dict]) -> list[dict]:
    return history[-MAX_HISTORY_MESSAGES:]


def prompt_ready_history(history: list[dict]) -> list[dict]:
    converted = []
    for item in history:
        role = item["role"]
        # The user-facing identity is Ameca, but Ollama chat expects
        # the assistant role internally.
        if role == "ameca":
            role = "assistant"
        converted.append({"role": role, "content": item["content"]})
    return converted


def maybe_clarification_for_transcript(user_text: str) -> Optional[str]:
    """Return a short clarification response for common ASR mistakes.

    This avoids Ameca inventing a topic from a likely Whisper error.
    Add more project-specific corrections here as you observe them.
    """
    text = user_text.strip().lower()
    corrections = {
        "let it show": "I may have misunderstood. Did you say your name is Leticia?",
        "three last knives": "I may have misunderstood. Did you say three layers?",
    }
    for wrong, clarification in corrections.items():
        if wrong in text:
            return clarification + " 🙂"

    # Very short or odd transcripts with high-risk words should be clarified.
    if len(text.split()) <= 4 and any(word in text for word in ["knives", "weapon", "blood"]):
        return "I may have misunderstood that. Could you say it again? 🙂"

    return None

def generate_response(
    client: Client,
    user_text: str,
    emotion_result: EmotionResult,
    history: list[dict],
    user_profile: Optional[dict] = None,
    face_emotion_json: Optional[dict] = None,
) -> str:
    deterministic = deterministic_reply_if_applicable(
        user_text=user_text,
        emotion=emotion_result.emotion,
    )

    if deterministic:
        return deterministic

    #clarification = maybe_clarification_for_transcript(user_text)
    #if clarification:
    #    return clarification

    safe_user_text = limit_text_length(user_text)
    system_prompt = limit_system_prompt(
        build_response_system_prompt(
            emotion_result=emotion_result,
            user_profile=user_profile,
            face_emotion_json=face_emotion_json,
        )
    )

    messages = [
        {
            "role": "system",
            "content": system_prompt,
        },
        *prompt_ready_history(trim_history(history[-6:])),
        {
            "role": "user",
            "content": safe_user_text,
        },
    ]

    response = client.chat(
        model=MODEL_NAME,
        messages=messages,
        options={
            "temperature": 0.4,
            "num_predict": 120,
            "repeat_penalty": 1.25,
            "num_ctx": 2048,
        },
        stream=False,
    )

    raw_reply = response["message"]["content"]
    # return normalize_reply(raw_reply, emotion_result.emotion)
    # return raw_reply
    raw_reply = response["message"]["content"]
    data = safe_json_extract(raw_reply)

    if data and isinstance(data, dict):
        reply_text = str(data.get("reply", "")).strip()
        emoji = str(data.get("emoji", "")).strip()

        if emoji in {":)", ":-)", ""}:
            emoji = PLUTCHIK_EMOTIONS.get(emotion_result.emotion, "🙂")

        return normalize_reply(f"{reply_text} {emoji}", emotion_result.emotion)

    return normalize_reply(raw_reply, emotion_result.emotion)


# =========================
# Main loop
# =========================

def main() -> None:
    print_ts("Starting Silero VAD + faster-whisper Plutchik chat prototype with local memory.")
    print_ts(f"Python: {sys.version.split()[0]}")
    print_ts(f"Ollama host: {OLLAMA_HOST}")
    print_ts(f"Ollama response model: {MODEL_NAME}")
    print_ts(f"Ollama VLM face model: {VLM_FACE_MODEL_NAME}")
    print()

    ensure_data_dirs()

    check_ollama_available()
    ensure_model_available(MODEL_NAME)
    ensure_model_available(VLM_FACE_MODEL_NAME)

    client = Client(host=OLLAMA_HOST)

    global VLM_FACE_WORKER
    VLM_FACE_WORKER = VLMFaceEmotionWorker(host=OLLAMA_HOST, model_name=VLM_FACE_MODEL_NAME)
    VLM_FACE_WORKER.start()

    list_input_devices()

    print_ts("Loading Silero VAD...")
    try:
        silero_model = load_silero_vad()
        print_ts("Silero VAD ready.")
    except Exception as exc:
        raise RuntimeError(
            "Failed to load Silero VAD. Install it with:\n"
            "pip install silero-vad torch\n\n"
            f"Original error: {exc}"
        )

    print_ts("Loading faster-whisper...")
    try:
        whisper_model = SafeWhisperTranscriber(FAST_WHISPER_CONFIG)

    except Exception as exc:
        # If CUDA model loading itself fails, try CPU/int8 before giving up.
        if FAST_WHISPER_CONFIG.get("device") != "cpu" and ENABLE_WHISPER_CPU_FALLBACK_ON_OOM:
            print_ts(f"Could not load faster-whisper on CUDA: {exc}")
            print_ts("Trying CPU/int8 fallback for faster-whisper...")
            fallback_config = dict(FAST_WHISPER_CONFIG)
            fallback_config["model"] = WHISPER_CPU_FALLBACK_MODEL
            fallback_config["device"] = "cpu"
            fallback_config["compute_type"] = "int8"
            whisper_model = SafeWhisperTranscriber(fallback_config)
        else:
            raise RuntimeError(
                f"Failed to load faster-whisper with active config:\n"
                f"{json.dumps(FAST_WHISPER_CONFIG, indent=2)}\n\n"
                "Install it with:\n"
                "pip install faster-whisper\n\n"
                f"Original error: {exc}"
            )

    user_key, user_profile, intro_reply = prompt_for_user_name(
        client=client,
        whisper_model=whisper_model,
        silero_model=silero_model,
        input_device=INPUT_DEVICE,
    )

    print()

    if user_profile.get("conversation_summary"):
        print_ts("Loaded previous conversation memory.")
        print()

    print("Conversation mode is active.")
    print("After Ameca replies, speak when the terminal shows 'You:'.")
    print("Say '/exit' or press Ctrl+C to save the transcript and quit.")
    print()
    hand_turn_back_to_user()
    print()

    history: list[dict] = []
    session_log: list[dict] = []

    # Store the generated introduction in the transcript so the session is complete.
    session_log.append({
        "role": "ameca",
        "content": intro_reply,
        "timestamp": now_ts(),
        "intent": "self_introduction",
    })
    history.append({"role": "ameca", "content": intro_reply})

    try:
        while True:
            wav_path, face_capture = listen_for_utterance_with_silero_vad_and_face_emotion(
                input_device=INPUT_DEVICE,
                silero_model=silero_model,
                camera_device=CAMERA_DEVICE,
                vlm_worker=VLM_FACE_WORKER,
                prompt_label="utterance",
                announce_feedback=False,
            )

            if face_capture:
                if face_capture.error:
                    print_ts(f"Face emotion capture error: {face_capture.error}")
                else:
                    print_ts(f"Face emotion summary: {face_capture.summary_text}")

            if not wav_path:
                continue

            try:
                user_text = transcribe_audio(wav_path, whisper_model)
            except RuntimeError as exc:
                print_ts(f"Transcription failed but the session will continue: {exc}")
                user_text = ""
            finally:
                try:
                    os.remove(wav_path)
                except OSError:
                    pass

            if not user_text:
                print_ts("No speech detected after transcription.")
                print()
                print("You:")
                print()
                continue

            print_ts(f"faster-whisper transcript: {user_text}")

            maybe_name = extract_name_from_text(user_text)
            if maybe_name and not looks_like_invalid_name(maybe_name):
                user_key, user_profile = rename_current_user(
                    old_user_key=user_key,
                    user_profile=user_profile,
                    new_name=maybe_name,
                )

                reply = generate_introduction_response(
                    client=client,
                    user_name=user_profile["name"],
                )

                set_conversation_state(ConversationState.SPEAKING)
                print_ts(f"Ameca: {reply}")
                hand_turn_back_to_user()
                print()

                history.append({"role": "user", "content": user_text})
                history.append({"role": "ameca", "content": reply})
                history = trim_history(history)

                session_log.append({
                    "role": "user",
                    "content": user_text,
                    "timestamp": now_ts(),
                    "input_mode": "silero_vad_faster_whisper",
                    "intent": "name_introduction",
                })
                session_log.append({
                    "role": "ameca",
                    "content": reply,
                    "timestamp": now_ts(),
                })

                continue

            command = normalize_command(user_text)

            if command in {"exit", "quit"}:
                print_ts("Goodbye.")
                break

            if command == "clear":
                history.clear()
                print_ts("Conversation history cleared.")
                continue

            facial_hint = face_capture.summary_text if face_capture else None
            face_emotion_json = face_capture.as_json if face_capture else default_face_emotion_json()

            emotion_result = detect_emotion(
                client=client,
                transcribed_text=user_text,
                facial_emotion_hint=facial_hint,
            )

            emotion_json = {
                "emotion": emotion_result.emotion,
                "confidence": emotion_result.confidence,
                "reason": emotion_result.reason,
            }

            print_ts("Detected emotion JSON:")
            print(json.dumps(emotion_json, indent=2))
            print()

            print_ts("Face emotion JSON:")
            print(json.dumps(face_emotion_json, indent=2))
            print()

            reply = generate_response(
                client=client,
                user_text=user_text,
                emotion_result=emotion_result,
                history=history,
                user_profile=user_profile,
                face_emotion_json=face_emotion_json,
            )

            set_conversation_state(ConversationState.SPEAKING)
            print_ts(f"Ameca: {reply}")
            hand_turn_back_to_user()
            print()

            user_message = {
                "role": "user",
                "content": user_text,
                "timestamp": now_ts(),
                "emotion": emotion_json,
                "facial_emotion_hint": facial_hint,
                "face_emotion": face_emotion_json,
                "input_mode": "silero_vad_faster_whisper_ollama_vlm",
            }

            assistant_message = {
                "role": "ameca",
                "content": reply,
                "timestamp": now_ts(),
            }

            history.append({"role": "user", "content": user_text})
            history.append({"role": "ameca", "content": reply})
            history = trim_history(history)

            session_log.append(user_message)
            session_log.append(assistant_message)

    except KeyboardInterrupt:
        print()
        print_ts("Goodbye.")

    finally:
        if VLM_FACE_WORKER is not None:
            VLM_FACE_WORKER.stop()

        if session_log:
            session_path = save_session_transcript(
                user_key=user_key,
                user_profile=user_profile,
                session_log=session_log,
            )

            update_user_after_session(
                client=client,
                user_key=user_key,
                session_path=session_path,
                session_log=session_log,
            )

            print_ts(f"Conversation transcript saved to: {session_path}")
        else:
            print_ts("No conversation messages to save.")


if __name__ == "__main__":
    main()
