from __future__ import annotations

import json
import os
import re
import sys
import tempfile
import subprocess
import threading
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Tuple

# Linux-only Qt fix. Do not force this on macOS.
if sys.platform.startswith("linux"):
    os.environ["QT_QPA_PLATFORM"] = "xcb"

# Harmless on non-Windows; prevents some OpenCV backend priority issues on Windows.
os.environ["OPENCV_VIDEOIO_PRIORITY_MSMF"] = "0"

import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf
from deepface import DeepFace
from faster_whisper import WhisperModel
from ollama import Client


# =========================
# Local Ollama configuration
# =========================

# OLLAMA_HOST = "http://127.0.0.1:11434"
OLLAMA_HOST = "https://sunday-spread-colony-gnome.trycloudflare.com"

# MODEL_NAME = "llama3:8b"
MODEL_NAME = "mistral:7b"


"""
Setup before running:

1. Start Ollama server:
   ollama serve

2. Pull model:
   ollama pull llama3:8b

3. Install Python dependencies:
   pip install ollama sounddevice soundfile numpy faster-whisper opencv-python deepface

Notes:
- For cv2.imshow camera preview, use opencv-python, not opencv-python-headless.
- On macOS, give Terminal/iTerm camera and microphone permission:
  System Settings -> Privacy & Security -> Camera / Microphone.
"""


AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information.

USER ADAPTATION
Use clear, simple explanations.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""


# =========================
# Faster-Whisper configuration
# =========================

# HOME / MACBOOK CPU CONFIG
FASTER_WHISPER_CONFIG = {
    "profile": "home_macbook_cpu",
    "model": "small",
    "device": "cpu",
    "compute_type": "int8",
    "language": "en",
}

# SCHOOL / GPU CONFIG
# FASTER_WHISPER_CONFIG = {
#     "profile": "school_gpu",
#     "model": "small",
#     "device": "cuda",
#     "compute_type": "int8",
#     "language": "en",
# }


# =========================
# Audio configuration
# =========================

TARGET_SAMPLE_RATE = 16000
MAX_RECORD_SECONDS = 10
INPUT_DEVICE: Optional[int] = None

MIN_PEAK_THRESHOLD = 0.01
MIN_RMS_THRESHOLD = 0.003


# =========================
# Camera / DeepFace configuration
# =========================

CAMERA_DEVICE: Optional[int] = None
CAMERA_FRAME_WIDTH = 320
CAMERA_FRAME_HEIGHT = 240
CAMERA_PREVIEW_ENABLED = True
CAMERA_PREVIEW_WINDOW_NAME = "Camera Preview - press q to close preview"

CAMERA_SAMPLE_EVERY_SECONDS = 1.0
CAMERA_WARMUP_SECONDS = 1.5

DEEPFACE_DETECTOR_BACKEND = "opencv"
DEEPFACE_ACTIONS = ["emotion"]
DEEPFACE_ALIGN = True

FACE_MIN_TOP_SCORE = 45.0
FACE_MIN_MARGIN = 15.0


# =========================
# Chat configuration
# =========================

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy": "😊",
    "trust": "🙂",
    "fear": "😨",
    "surprise": "😮",
    "sadness": "😢",
    "disgust": "🤢",
    "anger": "😠",
    "anticipation": "🤔",
}

ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())


# =========================
# Data models
# =========================

@dataclass
class EmotionResult:
    emotion: str
    confidence: float
    reason: str


@dataclass
class FaceEmotionCapture:
    emotion_score_samples: list[dict[str, float]]
    frame_count: int
    sampled_frame_count: int
    started_at: str
    ended_at: str
    error: Optional[str] = None

    @property
    def averaged_scores(self) -> dict[str, float]:
        if not self.emotion_score_samples:
            return {}

        totals: dict[str, float] = {}

        for sample in self.emotion_score_samples:
            for emotion, score in sample.items():
                totals[emotion] = totals.get(emotion, 0.0) + score

        count = len(self.emotion_score_samples)
        return {emotion: total / count for emotion, total in totals.items()}

    @property
    def dominant_emotion(self) -> Optional[str]:
        scores = self.averaged_scores
        if not scores:
            return None
        return max(scores.items(), key=lambda item: item[1])[0]

    @property
    def is_reliable(self) -> bool:
        scores = self.averaged_scores
        if not scores:
            return False

        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        top_score = ordered[0][1]
        second_score = ordered[1][1] if len(ordered) > 1 else 0.0

        return top_score >= FACE_MIN_TOP_SCORE and (top_score - second_score) >= FACE_MIN_MARGIN

    @property
    def summary_text(self) -> str:
        if self.error:
            return f"No facial-expression hint available because: {self.error}"

        scores = self.averaged_scores
        if not scores:
            return "No reliable facial-expression hint was captured during speech."

        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)

        if not self.is_reliable:
            top_parts = [f"{emo}={score:.0f}%" for emo, score in ordered[:3]]
            return (
                "Facial-expression hint was weak or mixed; "
                f"top_signals=({', '.join(top_parts)}); "
                f"samples={self.sampled_frame_count}"
            )

        parts = [f"{emo}={score:.0f}%" for emo, score in ordered if score >= 5.0]
        return (
            f"dominant={self.dominant_emotion}; "
            f"averaged_scores=({', '.join(parts)}); "
            f"samples={self.sampled_frame_count}"
        )

    @property
    def as_json(self) -> dict:
        scores = self.averaged_scores

        return {
            "available": self.error is None and bool(scores),
            "reliable": self.is_reliable,
            "dominant_emotion": self.dominant_emotion,
            "averaged_scores": scores,
            "frame_count": self.frame_count,
            "sampled_frame_count": self.sampled_frame_count,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "error": self.error,
            "note": (
                "Facial expression analysis is a weak supporting signal only. "
                "Text-based emotion should remain the primary signal."
            ),
        }


# =========================
# Utility helpers
# =========================

def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")


def normalize_command(text: str) -> Optional[str]:
    stripped = text.strip().lower()
    if not stripped.startswith(("/", "\\")):
        return None
    return re.sub(r"^[\\/]+", "", stripped)


def default_face_emotion_json() -> dict:
    return {
        "available": False,
        "reliable": False,
        "dominant_emotion": None,
        "averaged_scores": {},
        "frame_count": 0,
        "sampled_frame_count": 0,
        "started_at": None,
        "ended_at": None,
        "error": "No face emotion capture was provided.",
        "note": (
            "Facial expression analysis is unavailable. "
            "Use only text-based emotion context."
        ),
    }


# =========================
# Ollama setup helpers
# =========================

def check_ollama_available() -> None:
    try:
        client = Client(host=OLLAMA_HOST)
        client.list()
    except Exception as exc:
        raise RuntimeError(
            "Could not connect to Ollama.\n"
            "Make sure the server is running with: ollama serve"
        ) from exc


def ensure_model_available(model_name: str = MODEL_NAME) -> None:
    if not OLLAMA_HOST.startswith("http://127.0.0.1") and not OLLAMA_HOST.startswith("http://localhost"):
        print(f"Skipping local Ollama CLI check for remote host. Using model: {model_name}")
        return

    try:
        result = subprocess.run(
            ["ollama", "list"],
            capture_output=True,
            text=True,
            check=False,
        )

        if model_name not in result.stdout:
            print_ts(f"Model {model_name} not found locally. Pulling it now...")
            subprocess.run(["ollama", "pull", model_name], check=True)

    except FileNotFoundError:
        raise RuntimeError("Ollama CLI was not found. Install Ollama first.")


# =========================
# Audio helpers
# =========================

def list_input_devices() -> None:
    print("\nAvailable input devices:")

    try:
        devices = sd.query_devices()
        hostapis = sd.query_hostapis()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return

    found = False

    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            found = True
            hostapi_name = hostapis[device["hostapi"]]["name"]
            print(
                f"[mic {idx}] {device['name']} | "
                f"hostapi={hostapi_name} | "
                f"inputs={device['max_input_channels']} | "
                f"default_sr={device['default_samplerate']}"
            )

    if not found:
        print("No input devices found.")

    print()
    print(f"Current default audio device: {sd.default.device}")
    print()


def choose_input_device(current_device: Optional[int]) -> Optional[int]:
    list_input_devices()
    choice = input("Enter microphone device index, or blank for default: ").strip()

    if not choice:
        return current_device

    try:
        device_index = int(choice)
        device_info = sd.query_devices(device_index)

        if device_info["max_input_channels"] <= 0:
            print("Selected device does not support input.")
            return current_device

        print_ts(f"Using microphone: [{device_index}] {device_info['name']}")
        return device_index

    except Exception as exc:
        print(f"Invalid device: {exc}")
        return current_device


def get_input_samplerate(input_device: Optional[int]) -> int:
    if input_device is None:
        device_info = sd.query_devices(kind="input")
    else:
        device_info = sd.query_devices(input_device)

    default_sr = int(round(device_info["default_samplerate"]))
    if default_sr <= 0:
        return TARGET_SAMPLE_RATE

    return default_sr


def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32, copy=False)

    if audio.size == 0:
        return audio.astype(np.float32, copy=False)

    duration = len(audio) / original_sr
    target_length = max(1, int(round(duration * target_sr)))

    old_times = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_times = np.linspace(0.0, duration, num=target_length, endpoint=False)

    return np.interp(new_times, old_times, audio).astype(np.float32)


def record_audio_to_wav(
    max_seconds: int = MAX_RECORD_SECONDS,
    input_device: Optional[int] = INPUT_DEVICE,
) -> Optional[str]:

    try:
        sample_rate = get_input_samplerate(input_device)

        sd.check_input_settings(
            device=input_device,
            samplerate=sample_rate,
            channels=1,
            dtype="float32",
        )

        print()
        print_ts(f"Recording microphone... speak now ({max_seconds} seconds max).")
        print_ts(f"Using sample rate {sample_rate} Hz for input.")
        print()

        audio = sd.rec(
            frames=int(max_seconds * sample_rate),
            samplerate=sample_rate,
            channels=1,
            dtype="float32",
            device=input_device,
        )
        sd.wait()

        audio = np.squeeze(audio)

        if audio.size == 0:
            print("Audio recording failed: empty audio buffer.")
            return None

        peak = float(np.max(np.abs(audio)))
        rms = float(np.sqrt(np.mean(audio ** 2)))

        print_ts(f"Recorded audio level: peak={peak:.4f}, rms={rms:.4f}")

        if peak < MIN_PEAK_THRESHOLD or rms < MIN_RMS_THRESHOLD:
            print("Audio too quiet or silent.")
            print("Try a different microphone, check mute/input volume, or use /devices.")
            return None

        audio = np.clip(audio * min(0.9 / max(peak, 1e-6), 10.0), -1.0, 1.0)
        audio_16k = resample_audio(audio, sample_rate, TARGET_SAMPLE_RATE)

        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
            wav_path = tmp.name

        sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
        return wav_path

    except Exception as exc:
        print(f"Recording error: {exc}")
        return None


def transcribe_with_faster_whisper(
    wav_path: str,
    whisper_model: WhisperModel,
) -> str:
    segments, info = whisper_model.transcribe(
        wav_path,
        language=FASTER_WHISPER_CONFIG["language"],
        beam_size=5,
        vad_filter=True,
    )

    transcript_parts = []

    for segment in segments:
        text = segment.text.strip()
        if text:
            transcript_parts.append(text)

    return " ".join(transcript_parts).strip()


# =========================
# Camera / DeepFace helpers
# =========================

def get_camera_backend() -> int:
    if sys.platform == "darwin":
        return cv2.CAP_AVFOUNDATION

    if sys.platform.startswith("linux"):
        return cv2.CAP_V4L2

    return cv2.CAP_ANY


def open_camera(camera_device: Optional[int]) -> cv2.VideoCapture:
    camera_index = 0 if camera_device is None else camera_device
    cap = cv2.VideoCapture(camera_index, get_camera_backend())

    if cap.isOpened():
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_FRAME_HEIGHT)

    return cap


def list_camera_devices(max_indices: int = 6) -> None:
    print("\nAvailable camera devices:")
    found = False

    for idx in range(max_indices):
        cap = open_camera(idx)
        try:
            if not cap.isOpened():
                continue

            ok, frame = cap.read()
            if not ok or frame is None:
                continue

            found = True
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            print(f"[cam {idx}] available | resolution={width}x{height}")
        finally:
            cap.release()

    if not found:
        print("No camera devices found.")

    print()


def choose_camera_device(current_camera_device: Optional[int]) -> Optional[int]:
    list_camera_devices()
    choice = input("Enter camera device index, or blank for default: ").strip()

    if not choice:
        return current_camera_device

    try:
        camera_index = int(choice)
        cap = open_camera(camera_index)

        try:
            if not cap.isOpened():
                print("That camera could not be opened.")
                return current_camera_device

            ok, frame = cap.read()
            if not ok or frame is None:
                print("That camera opened but did not return a frame.")
                return current_camera_device

            print_ts(f"Using camera device [{camera_index}]")
            return camera_index

        finally:
            cap.release()

    except Exception as exc:
        print(f"Invalid camera device: {exc}")
        return current_camera_device


def analyze_frame_emotion_scores(frame_bgr: np.ndarray) -> Optional[dict[str, float]]:
    try:
        result = DeepFace.analyze(
            img_path=frame_bgr,
            actions=DEEPFACE_ACTIONS,
            enforce_detection=False,
            detector_backend=DEEPFACE_DETECTOR_BACKEND,
            align=DEEPFACE_ALIGN,
            silent=True,
        )

        if isinstance(result, list):
            if not result:
                return None
            result = result[0]

        scores = result.get("emotion")
        if not isinstance(scores, dict):
            return None

        return {emotion: float(score) for emotion, score in scores.items()}

    except Exception:
        return None


def capture_face_emotion_during_recording(
    duration_seconds: int,
    camera_device: Optional[int],
    sample_every_seconds: float = CAMERA_SAMPLE_EVERY_SECONDS,
    stop_event: Optional[threading.Event] = None,
) -> FaceEmotionCapture:
    started_at = now_ts()
    emotion_score_samples: list[dict[str, float]] = []
    frame_count = 0
    sampled_frame_count = 0
    last_status = "warming up..."

    cap = open_camera(camera_device)

    if not cap.isOpened():
        return FaceEmotionCapture(
            emotion_score_samples=[],
            frame_count=0,
            sampled_frame_count=0,
            started_at=started_at,
            ended_at=now_ts(),
            error="Could not open camera.",
        )

    window_created = False

    try:
        end_time = time.time() + duration_seconds
        capture_start_time = time.time()
        last_sample_time = 0.0

        print_ts("Camera emotion capture and preview are active during voice recording.")

        if CAMERA_PREVIEW_ENABLED:
            cv2.namedWindow(CAMERA_PREVIEW_WINDOW_NAME, cv2.WINDOW_NORMAL)
            window_created = True

        while time.time() < end_time:
            if stop_event is not None and stop_event.is_set():
                break

            ok, frame = cap.read()
            if not ok or frame is None:
                time.sleep(0.05)
                continue

            frame_count += 1
            now = time.time()
            elapsed = now - capture_start_time
            remaining = max(0.0, end_time - now)

            if CAMERA_PREVIEW_ENABLED:
                preview_frame = frame.copy()

                cv2.putText(
                    preview_frame,
                    f"Recording... {remaining:.1f}s left",
                    (20, 35),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.8,
                    (0, 255, 0),
                    2,
                    cv2.LINE_AA,
                )

                cv2.putText(
                    preview_frame,
                    f"Emotion: {last_status}",
                    (20, 70),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.7,
                    (255, 255, 255),
                    2,
                    cv2.LINE_AA,
                )

                preview_frame = cv2.resize(preview_frame, (640, 480))
                cv2.imshow(CAMERA_PREVIEW_WINDOW_NAME, preview_frame)

                key = cv2.waitKey(1) & 0xFF
                if key == ord("q"):
                    if stop_event is not None:
                        stop_event.set()
                    break

            should_sample = (
                elapsed >= CAMERA_WARMUP_SECONDS
                and now - last_sample_time >= sample_every_seconds
            )

            if should_sample:
                last_sample_time = now
                sampled_frame_count += 1

                scores = analyze_frame_emotion_scores(frame)
                if scores:
                    emotion_score_samples.append(scores)
                    top_emotion, top_score = max(scores.items(), key=lambda item: item[1])
                    last_status = f"{top_emotion}: {top_score:.0f}%"
                else:
                    last_status = "no face/emotion detected"

            time.sleep(0.02)

    except Exception as exc:
        return FaceEmotionCapture(
            emotion_score_samples=emotion_score_samples,
            frame_count=frame_count,
            sampled_frame_count=sampled_frame_count,
            started_at=started_at,
            ended_at=now_ts(),
            error=f"Camera preview/capture failed: {exc}",
        )

    finally:
        cap.release()

        if window_created:
            try:
                cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME)
                cv2.waitKey(1)
            except Exception:
                pass

    return FaceEmotionCapture(
        emotion_score_samples=emotion_score_samples,
        frame_count=frame_count,
        sampled_frame_count=sampled_frame_count,
        started_at=started_at,
        ended_at=now_ts(),
        error=None,
    )


def record_audio_and_capture_face_emotion(
    max_seconds: int = MAX_RECORD_SECONDS,
    input_device: Optional[int] = INPUT_DEVICE,
    camera_device: Optional[int] = CAMERA_DEVICE,
) -> Tuple[Optional[str], Optional[FaceEmotionCapture]]:
    """
    Record audio in a background thread.
    Run camera preview/emotion capture on the main thread.

    This is important on macOS because cv2.namedWindow/cv2.imshow
    can crash when called from a worker thread.
    """
    audio_result: dict[str, Optional[str]] = {"wav_path": None}
    stop_event = threading.Event()

    def audio_worker() -> None:
        try:
            audio_result["wav_path"] = record_audio_to_wav(
                max_seconds=max_seconds,
                input_device=input_device,
            )
        finally:
            stop_event.set()

    audio_thread = threading.Thread(target=audio_worker, daemon=False)
    audio_thread.start()

    face_capture = capture_face_emotion_during_recording(
        duration_seconds=max_seconds,
        camera_device=camera_device,
        sample_every_seconds=CAMERA_SAMPLE_EVERY_SECONDS,
        stop_event=stop_event,
    )

    stop_event.set()
    audio_thread.join()

    return audio_result.get("wav_path"), face_capture


# =========================
# JSON helpers
# =========================

def safe_json_extract(text: str) -> Optional[dict]:
    text = text.strip()

    text = re.sub(
        r"^```(?:json)?\s*|\s*```$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    ).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)
    if not match:
        return None

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


# =========================
# Emotion detection
# =========================

def build_emotion_prompt(
    transcribed_text: str,
    facial_emotion_hint: Optional[str] = None,
) -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())

    facial_section = (
        f"Facial-expression hint captured during speech: {facial_emotion_hint}\n"
        if facial_emotion_hint
        else "No facial-expression hint was available.\n"
    )

    return f"""
You are an emotion classification system for a human-robot interaction chat system.

Classify the user's emotional state from the text below.

You must map the emotion to exactly one of Plutchik's 8 primary emotions:

{emotions}

Use the user's words as the primary signal.
Use the facial-expression hint only as a weak supporting signal.
If the words and facial-expression hint conflict, trust the words more.
Do not make strong claims from facial-expression analysis alone.

Return JSON only.

Required JSON schema:
{{
  "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation",
  "confidence": 0.0,
  "reason": "short explanation"
}}

Rules:
- confidence must be a number between 0.0 and 1.0
- choose the best single emotion, even if the message is mixed
- do not add markdown
- do not add extra text outside JSON
- For greetings such as "hello", "hi", or "good morning", return:
  {{"emotion": "trust", "confidence": 0.6, "reason": "The user is opening a friendly social interaction."}}
- For farewells such as "bye", "goodbye", "take care", or "talk later", return:
  {{"emotion": "trust", "confidence": 0.7, "reason": "The user is closing the conversation politely."}}

User text:
{transcribed_text}

{facial_section}
""".strip()


def detect_emotion(
    client: Client,
    transcribed_text: str,
    facial_emotion_hint: Optional[str] = None,
) -> EmotionResult:
    response = client.chat(
        model=MODEL_NAME,
        format="json",
        messages=[
            {
                "role": "system",
                "content": "You return valid JSON only.",
            },
            {
                "role": "user",
                "content": build_emotion_prompt(
                    transcribed_text=transcribed_text,
                    facial_emotion_hint=facial_emotion_hint,
                ),
            },
        ],
        stream=False,
    )

    raw = response["message"]["content"]
    data = safe_json_extract(raw)

    if not data:
        return EmotionResult(
            emotion="trust",
            confidence=0.3,
            reason="Could not parse model output, so a neutral-social fallback was used.",
        )

    emotion = str(data.get("emotion", "")).strip().lower()
    reason = str(data.get("reason", "")).strip()

    try:
        confidence = float(data.get("confidence", 0.0))
    except Exception:
        confidence = 0.0

    confidence = max(0.0, min(1.0, confidence))

    if emotion not in PLUTCHIK_EMOTIONS:
        emotion = "trust"
        confidence = min(confidence, 0.3)
        reason = "Invalid emotion returned, so fallback emotion was used."

    return EmotionResult(
        emotion=emotion,
        confidence=confidence,
        reason=reason or "Emotion inferred from the transcribed message.",
    )


# =========================
# Emoji enforcement
# =========================

def remove_all_emojis_except_allowed_faces(text: str) -> str:
    result = []

    for char in text:
        if char in ALLOWED_FACE_EMOJIS:
            result.append(char)
            continue

        code = ord(char)

        is_emoji_or_symbol = (
            0x1F300 <= code <= 0x1FAFF
            or 0x2600 <= code <= 0x27BF
            or code in {0x200D, 0xFE0F}
        )

        if is_emoji_or_symbol:
            continue

        result.append(char)

    return "".join(result)


def remove_allowed_face_emojis(text: str) -> str:
    return "".join(char for char in text if char not in ALLOWED_FACE_EMOJIS)


def normalize_reply(raw_reply: str, emotion: str) -> str:
    required_emoji = PLUTCHIK_EMOTIONS[emotion]

    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = remove_allowed_face_emojis(cleaned)

    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)

    if not cleaned:
        cleaned = "I’m here with you."

    return f"{cleaned} {required_emoji}"


# =========================
# Date/time
# =========================

def runtime_context() -> str:
    return f"""
RUNTIME CONTEXT
Current local date and time: {now_ts()}.
Use this date/time when the user asks about today, now, or the current date.
""".strip()


def deterministic_reply_if_applicable(user_text: str, emotion: str) -> Optional[str]:
    text = user_text.strip().lower().rstrip(".!?")
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")

    if text in {"what is today's date", "what is todays date", "today's date", "todays date"}:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"

    if text in {"bye", "goodbye", "see you", "see you later", "talk later"}:
        return "Goodbye, and take care. 🙂"

    if text in {"have a good day", "have a nice day", "take care", "alright take care", "alright, take care"}:
        return "Thank you, and take care too. 🙂"

    return None


# =========================
# Response generation
# =========================

def build_response_system_prompt(
    emotion_result: EmotionResult,
    face_emotion_json: Optional[dict] = None,
) -> str:
    emoji = PLUTCHIK_EMOTIONS[emotion_result.emotion]

    if face_emotion_json is None:
        face_emotion_json = default_face_emotion_json()

    text_emotion_json = {
        "emotion": emotion_result.emotion,
        "confidence": emotion_result.confidence,
        "reason": emotion_result.reason,
    }

    return f"""
{AMECA_SYSTEM_PROMPT}
{runtime_context()}

PRIVATE EMOTION CONTEXT
This context is for tone control only. Do not mention it directly.

Text/LLM emotion JSON:
{json.dumps(text_emotion_json, indent=2)}

Face/DeepFace emotion JSON:
{json.dumps(face_emotion_json, indent=2)}

Interpretation rules:
- Treat the Text/LLM emotion JSON as the primary emotional signal.
- Treat the Face/DeepFace emotion JSON as a secondary weak supporting signal.
- If both signals agree, you may gently adapt tone more confidently.
- If both signals conflict, trust the text emotion more.
- Do not mention camera, DeepFace, facial analysis, detected emotion, or private emotion context to the user.
- Do not say things like "you look sad", "your face shows", or "I detected".

RESPONSE RULES
- Respond as Ameca, a humanoid social robot.
- Use the private emotion context only to adjust tone.
- Do not say phrases like "your detected emotion", "you seem sad", "trust is present", or "you are anticipating".
- Do not reintroduce yourself unless the user asks who you are.
- Do not mention emotion labels unless the user explicitly asks.
- Do not repeat advice already given in the recent conversation.
- Keep the response to 1-2 short sentences.
- If the user asks who can help, suggest concrete people: supervisor, co-supervisor, lab colleagues, thesis coordinator, or university writing center.
- End with exactly one facial emoji.
- The only emoji you may use is: {emoji}
- Do not use any other emoji.
- Do not use non-facial emoji.
- Emoji must appear only at the end.
""".strip()


def trim_history(history: list[dict], max_messages: int = MAX_HISTORY_MESSAGES) -> list[dict]:
    return history[-max_messages:]


def prompt_ready_history(history: list[dict]) -> list[dict]:
    return [{"role": item["role"], "content": item["content"]} for item in history]


def generate_response(
    client: Client,
    user_text: str,
    emotion_result: EmotionResult,
    history: list[dict],
    face_emotion_json: Optional[dict] = None,
) -> str:
    deterministic = deterministic_reply_if_applicable(user_text, emotion_result.emotion)
    if deterministic:
        return deterministic

    messages = [
        {
            "role": "system",
            "content": build_response_system_prompt(
                emotion_result=emotion_result,
                face_emotion_json=face_emotion_json,
            ),
        },
        *prompt_ready_history(trim_history(history, 4)),
        {
            "role": "user",
            "content": user_text,
        },
    ]

    response = client.chat(
        model=MODEL_NAME,
        messages=messages,
        options={
            "temperature": 0.4,
            "num_predict": 80,
            "repeat_penalty": 1.25,
        },
        stream=False,
    )

    raw_reply = response["message"]["content"]
    return normalize_reply(raw_reply, emotion_result.emotion)


# =========================
# Input handling
# =========================

def get_user_input(
    whisper_model,
    current_input_device: Optional[int],
    current_camera_device: Optional[int],
) -> tuple[Optional[str], Optional[int], Optional[int], Optional[FaceEmotionCapture]]:

    try:
        user_input = input("You: ").strip()
    except (EOFError, KeyboardInterrupt):
        return None, current_input_device, current_camera_device, None

    if not user_input:
        return "", current_input_device, current_camera_device, None

    command = normalize_command(user_input)

    if command == "devices":
        list_input_devices()
        return "", current_input_device, current_camera_device, None

    if command == "mic":
        return "", choose_input_device(current_input_device), current_camera_device, None

    if command == "cams":
        list_camera_devices()
        return "", current_input_device, current_camera_device, None

    if command == "cam":
        return "", current_input_device, choose_camera_device(current_camera_device), None

    if command == "speak":
        if whisper_model is None:
            print("Voice input is unavailable because Faster-Whisper failed to load.")
            return "", current_input_device, current_camera_device, None

        wav_path, face_capture = record_audio_and_capture_face_emotion(
            max_seconds=MAX_RECORD_SECONDS,
            input_device=current_input_device,
            camera_device=current_camera_device,
        )

        if not wav_path:
            if face_capture:
                if face_capture.error:
                    print_ts(f"Face emotion capture error: {face_capture.error}")
                else:
                    print_ts(f"Face emotion summary: {face_capture.summary_text}")

            return "", current_input_device, current_camera_device, face_capture

        try:
            transcript = transcribe_with_faster_whisper(wav_path, whisper_model)
        finally:
            try:
                os.remove(wav_path)
            except OSError:
                pass

        if transcript:
            print_ts(f"Faster-Whisper transcript: {transcript}")

            if face_capture:
                if face_capture.error:
                    print_ts(f"Face emotion capture error: {face_capture.error}")
                else:
                    print_ts(f"Face emotion summary: {face_capture.summary_text}")

            return transcript, current_input_device, current_camera_device, face_capture

        print("No speech detected.")
        return "", current_input_device, current_camera_device, face_capture

    return user_input, current_input_device, current_camera_device, None


# =========================
# Main loop
# =========================

def main() -> None:
    print_ts("Starting multimodal Plutchik + DeepFace Ameca chat prototype.")
    print_ts(f"Python: {sys.version.split()[0]}")
    print_ts(f"Platform: {sys.platform}")
    print_ts(f"Ollama host: {OLLAMA_HOST}")
    print_ts(f"Ollama model: {MODEL_NAME}")
    print()

    check_ollama_available()
    ensure_model_available(MODEL_NAME)

    client = Client(host=OLLAMA_HOST)

    print_ts(
        f"Loading Faster-Whisper profile={FASTER_WHISPER_CONFIG['profile']}, "
        f"model={FASTER_WHISPER_CONFIG['model']}, "
        f"device={FASTER_WHISPER_CONFIG['device']}, "
        f"compute_type={FASTER_WHISPER_CONFIG['compute_type']}..."
    )

    try:
        whisper_model = WhisperModel(
            FASTER_WHISPER_CONFIG["model"],
            device=FASTER_WHISPER_CONFIG["device"],
            compute_type=FASTER_WHISPER_CONFIG["compute_type"],
        )

        print_ts("Faster-Whisper ready.")

    except Exception as exc:
        raise RuntimeError(
            f"Failed to load Faster-Whisper with active config:\n"
            f"{json.dumps(FASTER_WHISPER_CONFIG, indent=2)}\n\n"
            f"Original error: {exc}"
        )

    print()

    print("Commands:")
    print("  /speak   record microphone input, camera preview, and DeepFace emotion hint")
    print("  /devices list available microphones")
    print("  /mic     choose microphone")
    print("  /cams    list available cameras")
    print("  /cam     choose camera")
    print("  /clear   clear conversation history")
    print("  /exit    quit")
    print()

    history: list[dict] = []
    current_input_device = INPUT_DEVICE
    current_camera_device = CAMERA_DEVICE

    while True:
        user_text, current_input_device, current_camera_device, face_capture = get_user_input(
            whisper_model=whisper_model,
            current_input_device=current_input_device,
            current_camera_device=current_camera_device,
        )

        if user_text is None:
            print_ts("Goodbye.")
            break

        if not user_text:
            continue

        command = normalize_command(user_text)

        if command in {"exit", "quit"}:
            print_ts("Goodbye.")
            break

        if command == "clear":
            history.clear()
            print_ts("Conversation history cleared.")
            continue

        facial_hint = face_capture.summary_text if face_capture else None
        face_emotion_json = face_capture.as_json if face_capture else default_face_emotion_json()

        emotion_result = detect_emotion(
            client=client,
            transcribed_text=user_text,
            facial_emotion_hint=facial_hint,
        )

        llm_emotion_json = {
            "emotion": emotion_result.emotion,
            "confidence": emotion_result.confidence,
            "reason": emotion_result.reason,
        }

        print_ts("LLM emotion JSON:")
        print(json.dumps(llm_emotion_json, indent=2))
        print()

        print_ts("Face emotion JSON:")
        print(json.dumps(face_emotion_json, indent=2))
        print()

        reply = generate_response(
            client=client,
            user_text=user_text,
            emotion_result=emotion_result,
            history=history,
            face_emotion_json=face_emotion_json,
        )

        print_ts(f"Assistant: {reply}")
        print()

        history.append({
            "role": "user",
            "content": user_text,
            "facial_emotion_hint": facial_hint,
            "face_emotion_json": face_emotion_json,
            "llm_emotion_json": llm_emotion_json,
        })
        history.append({"role": "assistant", "content": reply})
        history = trim_history(history)


if __name__ == "__main__":
    main()
