from __future__ import annotations

import json
import os
import re
import sys
import tempfile
import subprocess
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

import numpy as np
import sounddevice as sd
import soundfile as sf
from faster_whisper import WhisperModel
from ollama import Client


# Local Ollama configuration

# OLLAMA_HOST = "http://127.0.0.1:11434"
OLLAMA_HOST = "https://optional-integrity-moisture-becoming.trycloudflare.com"
MODEL_NAME = "mistral:7b"

"""
Setup before running:

1. Start Ollama server:
   ollama serve

2. Pull Mistral:
   ollama pull mistral:7b

3. Install Python dependencies:
   pip install ollama sounddevice soundfile numpy whisperx
"""

AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information.

USER ADAPTATION
Use clear, simple explanations.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""

# WhisperX configuration

FASTER_WHISPER_MODEL = "small"
FASTER_WHISPER_DEVICE = "cpu"
FASTER_WHISPER_COMPUTE_TYPE = "int8"
FASTER_WHISPER_LANGUAGE = "en"


TARGET_SAMPLE_RATE = 16000
MAX_RECORD_SECONDS = 10
INPUT_DEVICE: Optional[int] = None


# Chat configuration

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy": "😊",
    "trust": "🙂",
    "fear": "😨",
    "surprise": "😮",
    "sadness": "😢",
    "disgust": "🤢",
    "anger": "😠",
    "anticipation": "🤔",
}

ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())


@dataclass
class EmotionResult:
    emotion: str
    confidence: float
    reason: str


def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")


def normalize_command(text: str) -> str:
    return re.sub(r"^[\\/]+", "", text.strip().lower())


# Ollama setup helpers

def check_ollama_available() -> None:
    try:
        client = Client(host=OLLAMA_HOST)
        client.list()
    except Exception as exc:
        raise RuntimeError(
            "Could not connect to Ollama.\n"
            "Make sure the server is running with: ollama serve"
        ) from exc


def ensure_model_available(model_name: str = MODEL_NAME) -> None:
    # try:
    #     result = subprocess.run(
    #         ["ollama", "list"],
    #         capture_output=True,
    #         text=True,
    #         check=False,
    #     )

    #     if model_name not in result.stdout:
    #         print_ts(f"Model {model_name} not found locally. Pulling it now...")
    #         subprocess.run(["ollama", "pull", model_name], check=True)

    # except FileNotFoundError:
    #     raise RuntimeError(
    #         "Ollama CLI was not found. Install Ollama first."
    #     )
    print(f"Skipping local Ollama CLI check for remote host. Using model: {model_name}")
    return


# Audio helpers

def list_input_devices() -> None:
    print("\nAvailable input devices:")

    try:
        devices = sd.query_devices()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return

    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            print(
                f"[{idx}] {device['name']} | "
                f"inputs={device['max_input_channels']} | "
                f"default_sr={device['default_samplerate']}"
            )

    print()


def choose_input_device(current_device: Optional[int]) -> Optional[int]:
    list_input_devices()
    choice = input("Enter microphone device index, or blank for default: ").strip()

    if not choice:
        return current_device

    try:
        device_index = int(choice)
        device_info = sd.query_devices(device_index)

        if device_info["max_input_channels"] <= 0:
            print("Selected device does not support input.")
            return current_device

        print_ts(f"Using microphone: {device_info['name']}")
        return device_index

    except Exception as exc:
        print(f"Invalid device: {exc}")
        return current_device


def get_input_samplerate(input_device: Optional[int]) -> int:
    if input_device is None:
        device_info = sd.query_devices(kind="input")
    else:
        device_info = sd.query_devices(input_device)

    return int(round(device_info["default_samplerate"]))


def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32)

    duration = len(audio) / original_sr
    target_length = int(duration * target_sr)

    old_times = np.linspace(0, duration, len(audio), endpoint=False)
    new_times = np.linspace(0, duration, target_length, endpoint=False)

    return np.interp(new_times, old_times, audio).astype(np.float32)


def record_audio_to_wav(
    max_seconds: int = MAX_RECORD_SECONDS,
    input_device: Optional[int] = INPUT_DEVICE,
) -> Optional[str]:

    try:
        sample_rate = get_input_samplerate(input_device)

        print_ts(f"Recording for {max_seconds} seconds. Speak now...")

        audio = sd.rec(
            int(max_seconds * sample_rate),
            samplerate=sample_rate,
            channels=1,
            dtype="float32",
            device=input_device,
        )
        sd.wait()

        audio = np.squeeze(audio)

        peak = float(np.max(np.abs(audio)))
        rms = float(np.sqrt(np.mean(audio ** 2)))

        if peak < 0.01 or rms < 0.003:
            print("Audio too quiet or silent.")
            return None

        audio = np.clip(audio * min(0.9 / peak, 10.0), -1.0, 1.0)
        audio_16k = resample_audio(audio, sample_rate, TARGET_SAMPLE_RATE)

        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
            wav_path = tmp.name

        sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
        return wav_path

    except Exception as exc:
        print(f"Recording error: {exc}")
        return None


def transcribe_with_faster_whisper(
    wav_path: str,
    whisper_model: WhisperModel,
) -> str:
    segments, info = whisper_model.transcribe(
        wav_path,
        language=FASTER_WHISPER_LANGUAGE,
        beam_size=5,
        vad_filter=True,
    )

    transcript_parts = []

    for segment in segments:
        text = segment.text.strip()
        if text:
            transcript_parts.append(text)

    return " ".join(transcript_parts).strip()


# JSON helpers

def safe_json_extract(text: str) -> Optional[dict]:
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        return None

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


# Emotion detection

def build_emotion_prompt(transcribed_text: str) -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())

    return f"""
You are an emotion classification system for a human-robot interaction chat system.

Classify the user's emotional state from the text below.

You must map the emotion to exactly one of Plutchik's 8 primary emotions:

{emotions}

Return JSON only.

Required JSON schema:
{{
  "emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation",
  "confidence": 0.0,
  "reason": "short explanation"
}}

Rules:
- confidence must be a number between 0.0 and 1.0
- choose the best single emotion, even if the message is mixed
- do not add markdown
- do not add extra text outside JSON
- For greetings such as "hello", "hi", or "good morning", return:
  {{"emotion": "trust", "confidence": 0.6, "reason": "The user is opening a friendly social interaction."}}
- For farewells such as "bye", "goodbye", "take care", or "talk later", return:
  {{"emotion": "trust", "confidence": 0.7, "reason": "The user is closing the conversation politely."}}

User text:
{transcribed_text}
""".strip()


def detect_emotion(client: Client, transcribed_text: str) -> EmotionResult:
    response = client.chat(
        model=MODEL_NAME,
        format="json",
        messages=[
            {
                "role": "system",
                "content": "You return valid JSON only.",
            },
            {
                "role": "user",
                "content": build_emotion_prompt(transcribed_text),
            },
        ],
        stream=False,
    )

    raw = response["message"]["content"]
    data = safe_json_extract(raw)

    if not data:
        return EmotionResult(
            emotion="trust",
            confidence=0.3,
            reason="Could not parse model output, so a neutral-social fallback was used.",
        )

    emotion = str(data.get("emotion", "")).strip().lower()
    reason = str(data.get("reason", "")).strip()

    try:
        confidence = float(data.get("confidence", 0.0))
    except Exception:
        confidence = 0.0

    confidence = max(0.0, min(1.0, confidence))

    if emotion not in PLUTCHIK_EMOTIONS:
        emotion = "trust"
        confidence = min(confidence, 0.3)
        reason = "Invalid emotion returned, so fallback emotion was used."

    return EmotionResult(
        emotion=emotion,
        confidence=confidence,
        reason=reason or "Emotion inferred from the transcribed message.",
    )


# Emoji enforcement

def remove_all_emojis_except_allowed_faces(text: str) -> str:
    result = []

    for char in text:
        if char in ALLOWED_FACE_EMOJIS:
            result.append(char)
            continue

        code = ord(char)

        is_emoji_or_symbol = (
            0x1F300 <= code <= 0x1FAFF
            or 0x2600 <= code <= 0x27BF
            or code in {0x200D, 0xFE0F}
        )

        if is_emoji_or_symbol:
            continue

        result.append(char)

    return "".join(result)


def remove_allowed_face_emojis(text: str) -> str:
    return "".join(char for char in text if char not in ALLOWED_FACE_EMOJIS)


def normalize_reply(raw_reply: str, emotion: str) -> str:
    required_emoji = PLUTCHIK_EMOTIONS[emotion]

    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = remove_allowed_face_emojis(cleaned)

    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)

    if not cleaned:
        cleaned = "I’m here with you."

    return f"{cleaned} {required_emoji}"


#Date/Time

def runtime_context() -> str:
    return f"""
RUNTIME CONTEXT
Current local date and time: {now_ts()}.
Use this date/time when the user asks about today, now, or the current date.
""".strip()

def deterministic_reply_if_applicable(user_text: str, emotion: str) -> Optional[str]:
    text = user_text.strip().lower().rstrip(".!?")
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")

    if text in {"what is today's date", "what is todays date", "today's date", "todays date"}:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"

    if text in {"bye", "goodbye", "see you", "see you later", "talk later"}:
        return "Goodbye, and take care. 🙂"

    if text in {"have a good day", "have a nice day", "take care", "alright take care", "alright, take care"}:
        return "Thank you, and take care too. 🙂"

    return None

# Response generation

def build_response_system_prompt(emotion_result: EmotionResult) -> str:
    emoji = PLUTCHIK_EMOTIONS[emotion_result.emotion]

    return f"""
{AMECA_SYSTEM_PROMPT}
{runtime_context()}
PRIVATE EMOTION CONTEXT
This context is for tone control only. Do not mention it directly.

{{
  "emotion": "{emotion_result.emotion}",
  "confidence": {emotion_result.confidence},
  "reason": "{emotion_result.reason}"
}}

RESPONSE RULES
- Respond as Ameca, a humanoid social robot.
- Use the private emotion context only to adjust tone.
- Do not say phrases like "your detected emotion", "you seem sad", "trust is present", or "you are anticipating".
- Do not reintroduce yourself unless the user asks who you are.
- Do not mention emotion labels unless the user explicitly asks.
- Do not repeat advice already given in the recent conversation.
- Keep the response to 1–2 short sentences.
- If the user asks who can help, suggest concrete people: supervisor, co-supervisor, lab colleagues, thesis coordinator, or university writing center.
- End with exactly one facial emoji.
- The only emoji you may use is: {emoji}
- Do not use any other emoji.
- Do not use non-facial emoji.
- Emoji must appear only at the end.
""".strip()


def trim_history(history: list[dict]) -> list[dict]:
    return history[-MAX_HISTORY_MESSAGES:]


def generate_response(
    client: Client,
    user_text: str,
    emotion_result: EmotionResult,
    history: list[dict],
) -> str:
    
    deterministic = deterministic_reply_if_applicable(user_text, emotion_result.emotion)
    if deterministic:
        return deterministic

    messages = [
        {
            "role": "system",
            "content": build_response_system_prompt(emotion_result),
        },
        *trim_history(history[-4:]),  # keep only very recent context to reduce repetition
        {
            "role": "user",
            "content": user_text,
        },
    ]

    response = client.chat(
        model=MODEL_NAME,
        messages=messages,
        options={
            "temperature": 0.4,
            "num_predict": 80,
            "repeat_penalty": 1.25,
        },
        stream=False,
    )

    raw_reply = response["message"]["content"]
    return normalize_reply(raw_reply, emotion_result.emotion)


# Input handling

def get_user_input(
    whisper_model,
    current_input_device: Optional[int],
) -> tuple[Optional[str], Optional[int]]:

    try:
        user_input = input("You: ").strip()
    except (EOFError, KeyboardInterrupt):
        return None, current_input_device

    if not user_input:
        return "", current_input_device

    command = normalize_command(user_input)

    if command == "devices":
        list_input_devices()
        return "", current_input_device

    if command == "mic":
        return "", choose_input_device(current_input_device)

    if command == "speak":
        wav_path = record_audio_to_wav(input_device=current_input_device)

        if not wav_path:
            return "", current_input_device

        try:
            transcript = transcribe_with_faster_whisper(wav_path, whisper_model)
        finally:
            try:
                os.remove(wav_path)
            except OSError:
                pass

        if transcript:
            print_ts(f"Faster-Whisper transcript: {transcript}")
            return transcript, current_input_device

        print("No speech detected.")
        return "", current_input_device

    # Typed text is treated as already-transcribed text.
    return user_input, current_input_device


# Main loop

def main() -> None:
    print_ts("Starting multimodal-inspired Plutchik chat prototype.")
    print_ts(f"Python: {sys.version.split()[0]}")
    print_ts(f"Ollama host: {OLLAMA_HOST}")
    print_ts(f"Ollama model: {MODEL_NAME}")
    print()

    check_ollama_available()
    ensure_model_available(MODEL_NAME)

    client = Client(host=OLLAMA_HOST)

    print_ts("Loading Faster-Whisper...")
    whisper_model = WhisperModel(
        FASTER_WHISPER_MODEL,
        device=FASTER_WHISPER_DEVICE,
        compute_type=FASTER_WHISPER_COMPUTE_TYPE,
    )
    print_ts("Faster-Whisper ready.")
    print()

    print("Commands:")
    print("  /speak   record microphone input and transcribe with Faster-Whisper")
    print("  /devices list available microphones")
    print("  /mic     choose microphone")
    print("  /clear   clear conversation history")
    print("  /exit    quit")
    print()

    history: list[dict] = []
    current_input_device = INPUT_DEVICE

    while True:
        user_text, current_input_device = get_user_input(
            whisper_model,
            current_input_device,
        )

        if user_text is None:
            print_ts("Goodbye.")
            break

        if not user_text:
            continue

        command = normalize_command(user_text)

        if command in {"exit", "quit"}:
            print_ts("Goodbye.")
            break

        if command == "clear":
            history.clear()
            print_ts("Conversation history cleared.")
            continue

        emotion_result = detect_emotion(client, user_text)

        emotion_json = {
            "emotion": emotion_result.emotion,
            "confidence": emotion_result.confidence,
            "reason": emotion_result.reason,
        }

        print_ts("Detected emotion JSON:")
        print(json.dumps(emotion_json, indent=2))
        print()

        reply = generate_response(
            client=client,
            user_text=user_text,
            emotion_result=emotion_result,
            history=history,
        )

        print_ts(f"Assistant: {reply}")
        print()

        history.append({"role": "user", "content": user_text})
        history.append({"role": "assistant", "content": reply})
        history = trim_history(history)


if __name__ == "__main__":
    main()