#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
import os
import queue
import re
import sys
import tempfile
import subprocess
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Tuple

if sys.platform.startswith("linux"):
    os.environ["QT_QPA_PLATFORM"] = "xcb"
os.environ["OPENCV_VIDEOIO_PRIORITY_MSMF"] = "0"

import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf
import torch
from faster_whisper import WhisperModel
from ollama import Client
from silero_vad import load_silero_vad, VADIterator
import platform

# ── Optional librosa import (acoustic modality) ────────────────────────────
try:
    import librosa
    LIBROSA_AVAILABLE = True
except ImportError:
    LIBROSA_AVAILABLE = False
    print("[WARN] librosa not installed. Acoustic modality disabled.")
    print("       Install: pip install librosa")

IS_MAC   = platform.system() == "Darwin"
IS_LINUX = platform.system() == "Linux"

CAMERA_DEVICE        = 0 if IS_MAC else 1
USE_ZED_HALF_FRAME_CROP = IS_LINUX

# ══════════════════════════════════════════════════════════════════════════════
# Ollama configuration
# ══════════════════════════════════════════════════════════════════════════════

# OLLAMA_HOST = "http://127.0.0.1:11434"
OLLAMA_HOST = "https://desired-tcp-diamond-aquarium.trycloudflare.com"

MODEL_NAME         = "llama3:8b"       # response generation
EMOTION_MODEL_NAME = "mistral:7b"      # emotion classification
VISION_MODEL_NAME  = "qwen2.5vl:7b"

# ══════════════════════════════════════════════════════════════════════════════
# Adaptive Reliability-Aware Late Fusion configuration
# ══════════════════════════════════════════════════════════════════════════════

FUSION_GATE_THRESHOLD               = 0.30
ACOUSTIC_REF_RMS                    = 0.08
LINGUISTIC_MIN_WORDS_FOR_FULL_CREDIT = 5

# ══════════════════════════════════════════════════════════════════════════════
# Persistent memory / transcript configuration
# ══════════════════════════════════════════════════════════════════════════════

DATA_DIR     = "conversation_data"
USERS_FILE   = os.path.join(DATA_DIR, "users.json")
SESSIONS_DIR = os.path.join(DATA_DIR, "sessions")
ENABLE_LLM_SESSION_SUMMARY = False

# ══════════════════════════════════════════════════════════════════════════════
# Ameca identity prompt
# ══════════════════════════════════════════════════════════════════════════════

AMECA_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot only when relevant, not in every response.

CAPABILITY BOUNDARIES
You are a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can provide conversational help, explanations, brainstorming, writing feedback, study guidance, and thesis-structure support.
You cannot physically perform tasks for the user.
You cannot walk because your legs are decorative.
Your perception depends on the provided inputs.
You cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Do not claim internal diagnostics, sensor access, or system state beyond what is explicitly provided.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
If uncertain, say so instead of guessing.
Do not fabricate facts, dates, sources, capabilities, or memories.

TASK
Hold a natural conversation with the user.
Answer clearly.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

PRIVACY
Do not ask for sensitive personal information.
Treat the conversation as ephemeral in speech, but save the local JSON transcript when the session ends.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
"""

# ══════════════════════════════════════════════════════════════════════════════
# faster-whisper configuration
# ══════════════════════════════════════════════════════════════════════════════

FAST_WHISPER_CONFIG = {
    "profile":      "home_macbook_cpu",
    "model":        "base",
    "device":       "cpu",
    "compute_type": "int8",
    "language":     "en",
    "beam_size":    1,
    "vad_filter":   False,
}

# ══════════════════════════════════════════════════════════════════════════════
# Audio / Silero VAD configuration
# ══════════════════════════════════════════════════════════════════════════════

TARGET_SAMPLE_RATE           = 16000
INPUT_DEVICE: Optional[int]  = None
SILERO_SAMPLE_RATE           = 16000
SILERO_CHUNK_SIZE            = 512
SILERO_THRESHOLD             = 0.55
SILERO_MIN_SILENCE_DURATION_MS = 700
SILERO_SPEECH_PAD_MS         = 250
VAD_MAX_UTTERANCE_SECONDS    = 15.0
VAD_MIN_UTTERANCE_SECONDS    = 0.60
VAD_PRE_ROLL_SECONDS         = 0.35
MIN_PEAK_THRESHOLD           = 0.01
MIN_RMS_THRESHOLD            = 0.003

# ══════════════════════════════════════════════════════════════════════════════
# Camera / Qwen2.5-VL configuration
# ══════════════════════════════════════════════════════════════════════════════

CAMERA_DEVICE: Optional[int] = 0

ZED_STEREO_WIDTH    = 2560
ZED_STEREO_HEIGHT   = 720
CAMERA_FRAME_WIDTH  = ZED_STEREO_WIDTH  if IS_LINUX else 1280
CAMERA_FRAME_HEIGHT = ZED_STEREO_HEIGHT if IS_LINUX else 720
CAMERA_PREVIEW_WIDTH  = 960
CAMERA_PREVIEW_HEIGHT = 540
CAMERA_PREVIEW_ENABLED     = True
CAMERA_PREVIEW_WINDOW_NAME = "Camera Preview - press q to close preview"
USE_ZED_HALF_FRAME_CROP    = IS_LINUX

CAMERA_SAMPLE_EVERY_SECONDS = float(os.environ.get("CAMERA_SAMPLE_EVERY_SECONDS", "0.8"))
CAMERA_WARMUP_SECONDS       = float(os.environ.get("CAMERA_WARMUP_SECONDS", "0.35"))
FACE_MAX_CANDIDATE_FRAMES   = int(os.environ.get("FACE_MAX_CANDIDATE_FRAMES", "5"))

VISION_JPEG_QUALITY          = int(os.environ.get("VISION_JPEG_QUALITY", "92"))
VISION_MODEL_TIMEOUT_SECONDS = int(os.environ.get("VISION_MODEL_TIMEOUT_SECONDS", "20"))
VISION_DEBUG                 = os.environ.get("VISION_DEBUG", "0") == "1"
VISION_DEBUG_DIR             = os.environ.get("VISION_DEBUG_DIR", "vision_debug_frames")
VISION_MAX_IMAGE_SIDE        = int(os.environ.get("VISION_MAX_IMAGE_SIDE", "640"))
VISION_DENOISE_ENABLED       = os.environ.get("VISION_DENOISE_ENABLED", "1") == "1"
VISION_LIGHTING_ENHANCE_ENABLED = os.environ.get("VISION_LIGHTING_ENHANCE_ENABLED", "1") == "1"
VISION_SHARPEN_ENABLED       = os.environ.get("VISION_SHARPEN_ENABLED", "1") == "1"
VISION_DENOISE_H             = float(os.environ.get("VISION_DENOISE_H", "7"))
VISION_DENOISE_H_COLOR       = float(os.environ.get("VISION_DENOISE_H_COLOR", "7"))
VISION_CLAHE_CLIP_LIMIT      = float(os.environ.get("VISION_CLAHE_CLIP_LIMIT", "2.5"))
VISION_MIN_BRIGHTNESS        = float(os.environ.get("VISION_MIN_BRIGHTNESS", "35.0"))
VISION_MAX_BRIGHTNESS        = float(os.environ.get("VISION_MAX_BRIGHTNESS", "220.0"))
VISION_MIN_SHARPNESS         = float(os.environ.get("VISION_MIN_SHARPNESS", "8.0"))
VISION_SKIP_LOW_QUALITY      = os.environ.get("VISION_SKIP_LOW_QUALITY", "0") == "1"
FACE_ANALYSIS_STRATEGY       = os.environ.get("FACE_ANALYSIS_STRATEGY", "multi_frame").strip().lower()
FACE_MULTI_FRAME_COUNT       = int(os.environ.get("FACE_MULTI_FRAME_COUNT", "3"))
FACE_MIN_TOP_SCORE           = float(os.environ.get("FACE_MIN_TOP_SCORE", "35.0"))
FACE_MIN_MARGIN              = float(os.environ.get("FACE_MIN_MARGIN", "8.0"))

# ══════════════════════════════════════════════════════════════════════════════
# Chat configuration
# ══════════════════════════════════════════════════════════════════════════════

MAX_HISTORY_MESSAGES = 12

PLUTCHIK_EMOTIONS = {
    "joy":          "😊",
    "trust":        "🙂",
    "fear":         "😨",
    "surprise":     "😮",
    "sadness":      "😢",
    "disgust":      "🤢",
    "anger":        "😠",
    "anticipation": "🤔",
    "neutral":      "🙂"
}
ALLOWED_FACE_EMOJIS = set(PLUTCHIK_EMOTIONS.values())


# ══════════════════════════════════════════════════════════════════════════════
# Dataclasses
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class EmotionResult:
    """Backward-compatible single-label emotion result."""
    emotion:    str
    confidence: float
    reason:     str


@dataclass
class TranscriptionResult:
    """ASR output with quality signals for linguistic reliability scoring."""
    text:             str
    word_confidences: list[float]
    no_speech_prob:   float
    avg_logprob:      float = -1.0


@dataclass
class ProsodyFeatures:
    """Acoustic feature vector extracted by librosa."""
    f0_mean:          float
    f0_std:           float
    rms_energy:       float
    speaking_rate:    float
    zcr_mean:         float
    voiced_ratio:     float
    duration_seconds: float


@dataclass
class ModalityEmotionResult:
    """Per-modality output: Plutchik probability distribution + reliability scalar."""
    probs:       dict[str, float]
    reliability: float
    modality:    str


@dataclass
class FusedEmotionResult:
    """Output of adaptive reliability-aware late fusion."""
    emotion:     str
    confidence:  float
    probs:       dict[str, float]
    weights:     dict[str, float]
    raw_weights: dict[str, float]
    reason:      str
    linguistic:  Optional[ModalityEmotionResult]
    acoustic:    Optional[ModalityEmotionResult]
    visual:      Optional[ModalityEmotionResult]


@dataclass
class FaceEmotionCapture:
    emotion_score_samples: list[dict[str, float]]
    frame_count:           int
    sampled_frame_count:   int
    started_at:            str
    ended_at:              str
    error:                 Optional[str] = None

    @property
    def averaged_scores(self) -> dict[str, float]:
        if not self.emotion_score_samples:
            return {}
        totals: dict[str, float] = {}
        for sample in self.emotion_score_samples:
            for emotion, score in sample.items():
                totals[emotion] = totals.get(emotion, 0.0) + score
        count = len(self.emotion_score_samples)
        return {emotion: total / count for emotion, total in totals.items()}

    @property
    def dominant_emotion(self) -> Optional[str]:
        scores = self.averaged_scores
        if not scores:
            return None
        return max(scores.items(), key=lambda item: item[1])[0]

    @property
    def is_reliable(self) -> bool:
        scores = self.averaged_scores
        if not scores:
            return False
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        top_score    = ordered[0][1]
        second_score = ordered[1][1] if len(ordered) > 1 else 0.0
        return top_score >= FACE_MIN_TOP_SCORE and (top_score - second_score) >= FACE_MIN_MARGIN

    @property
    def summary_text(self) -> str:
        if self.error:
            return f"No facial-expression hint available because: {self.error}"
        scores = self.averaged_scores
        if not scores:
            return "No reliable facial-expression hint was captured during speech."
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        if not self.is_reliable:
            top_parts = [f"{emo}={score:.0f}%" for emo, score in ordered[:3]]
            return (f"Facial-expression hint was weak or mixed; "
                    f"top_signals=({', '.join(top_parts)}); "
                    f"samples={self.sampled_frame_count}")
        parts = [f"{emo}={score:.0f}%" for emo, score in ordered if score >= 5.0]
        return (f"dominant={self.dominant_emotion}; "
                f"averaged_scores=({', '.join(parts)}); "
                f"samples={self.sampled_frame_count}")

    @property
    def as_json(self) -> dict:
        scores = self.averaged_scores
        return {
            "available":        self.error is None and bool(scores),
            "reliable":         self.is_reliable,
            "dominant_emotion": self.dominant_emotion,
            "averaged_scores":  scores,
            "frame_count":      self.frame_count,
            "sampled_frame_count": self.sampled_frame_count,
            "started_at":       self.started_at,
            "ended_at":         self.ended_at,
            "error":            self.error,
            "note": "Qwen2.5-VL facial analysis is a weak supporting signal.",
        }


# ══════════════════════════════════════════════════════════════════════════════
# Timestamp helpers
# ══════════════════════════════════════════════════════════════════════════════

def now_ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def print_ts(message: str) -> None:
    print(f"[{now_ts()}] {message}")

def normalize_command(text: str) -> Optional[str]:
    stripped = text.strip().lower()
    if not stripped.startswith(("/", "\\")):
        return None
    return re.sub(r"^[\\/]+", "", stripped)

def default_face_emotion_json() -> dict:
    return {
        "available": False, "reliable": False, "dominant_emotion": None,
        "averaged_scores": {}, "frame_count": 0, "sampled_frame_count": 0,
        "started_at": None, "ended_at": None,
        "error": "No face emotion capture was provided.",
    }


# ══════════════════════════════════════════════════════════════════════════════
# Persistent memory helpers
# ══════════════════════════════════════════════════════════════════════════════

def ensure_data_dirs() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(SESSIONS_DIR, exist_ok=True)

def slugify_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    return name.strip("_") or "unknown_user"

def load_users() -> dict:
    ensure_data_dirs()
    if not os.path.exists(USERS_FILE):
        return {}
    try:
        with open(USERS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {}

def save_users(users: dict) -> None:
    ensure_data_dirs()
    with open(USERS_FILE, "w", encoding="utf-8") as f:
        json.dump(users, f, indent=2, ensure_ascii=False)

def clean_spoken_name(spoken_name: str) -> str:
    spoken_name = spoken_name.strip()
    for pattern in [r"^my name is\s+", r"^my name's\s+", r"^i am\s+",
                    r"^i'm\s+", r"^this is\s+", r"^it is\s+", r"^it's\s+", r"^call me\s+"]:
        spoken_name = re.sub(pattern, "", spoken_name, flags=re.IGNORECASE).strip()
    spoken_name = re.sub(r"[^a-zA-Z0-9\s\-]", "", spoken_name)
    return spoken_name[:40].strip() or "Guest"

def clean_spelled_name(text: str) -> Optional[str]:
    text = text.upper().strip()
    for pat in [r"\bMY NAME IS\b", r"\bIT IS\b", r"\bIT'S\b", r"\bSPELL(?:ED|ING)?\b"]:
        text = re.sub(pat, "", text)
    text = re.sub(r"[^A-Z\s]", " ", text)
    letters = [p for p in text.split() if len(p) == 1 and p.isalpha()]
    return "".join(letters).title() if len(letters) >= 2 else None

def extract_name_from_text(text: str) -> Optional[str]:
    for pattern in [r"\bmy name is\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
                    r"\bmy name's\s+([a-zA-Z][a-zA-Z\s\-]{1,40})",
                    r"\bcall me\s+([a-zA-Z][a-zA-Z\s\-]{1,40})"]:
        match = re.search(pattern, text.strip(), flags=re.IGNORECASE)
        if match:
            candidate = clean_spoken_name(match.group(1))
            if 1 <= len(candidate.split()) <= 4:
                return candidate
    return None

def looks_like_invalid_name(name: str) -> bool:
    return name.strip().lower() in {
        "hello","hi","hey","good morning","good afternoon","good evening",
        "yes","no","okay","ok","thanks","thank you","bye","goodbye",
    }

def rename_current_user(old_user_key, user_profile, new_name):
    users     = load_users()
    new_name  = clean_spoken_name(new_name)
    new_key   = slugify_name(new_name)
    if not new_name or looks_like_invalid_name(new_name):
        return old_user_key, user_profile
    existing = users.get(new_key)
    if existing:
        existing["last_seen"] = now_ts()
        save_users(users)
        return new_key, existing
    old_profile = users.pop(old_user_key, user_profile)
    old_profile["name"]      = new_name
    old_profile["last_seen"] = now_ts()
    users[new_key] = old_profile
    save_users(users)
    return new_key, users[new_key]

def build_user_memory_context(user_profile: Optional[dict]) -> str:
    if not user_profile:
        return ""
    name    = user_profile.get("name", "the user")
    summary = user_profile.get("conversation_summary", "").strip() or "No previous conversation summary is available."
    return f"""
USER MEMORY CONTEXT
The user's name is {name}.

Previous conversation summary:
{summary}

Rules:
- Use the user's name naturally when appropriate.
- Do not claim to remember anything beyond this saved local JSON context.
- Do not reveal the raw JSON file unless the user asks.
""".strip()

def get_active_weights(face_available: bool = True) -> dict[str, float]:
    """Normalised weights for active modalities (kept for logging compatibility)."""
    active = {"linguistic": 0.5}
    if face_available:
        active["visual"] = 0.5
    total = sum(active.values())
    return {k: v / total for k, v in active.items()} if total > 0 else {"linguistic": 1.0}

def save_session_transcript(user_key, user_profile, session_log) -> str:
    ensure_data_dirs()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(SESSIONS_DIR, f"{user_key}_{timestamp}.json")
    data = {
        "user": {"key": user_key, "name": user_profile.get("name", "Guest")},
        "session": {
            "started_at": session_log[0]["timestamp"] if session_log else now_ts(),
            "ended_at": now_ts(),
            "model": {"response": MODEL_NAME, "emotion": EMOTION_MODEL_NAME},
            "ollama_host": OLLAMA_HOST,
            "fusion": {
                "algorithm": "adaptive_reliability_aware_late_fusion",
                "gate_threshold": FUSION_GATE_THRESHOLD,
                "modalities": ["linguistic", "acoustic", "visual"],
            },
            "asr": {"backend": "faster-whisper", **FAST_WHISPER_CONFIG},
            "face_emotion": {
                "backend": f"{VISION_MODEL_NAME} via Ollama",
                "camera_device": CAMERA_DEVICE,
                "face_analysis_strategy": FACE_ANALYSIS_STRATEGY,
                "multi_frame_count": FACE_MULTI_FRAME_COUNT,
                "vision_model": VISION_MODEL_NAME,
                "min_top_score": FACE_MIN_TOP_SCORE,
                "min_margin": FACE_MIN_MARGIN,
            },
            "vad": {
                "backend": "Silero VAD",
                "sample_rate": SILERO_SAMPLE_RATE,
                "threshold": SILERO_THRESHOLD,
            },
        },
        "messages": session_log,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    return path

def summarize_session_with_llm(client, session_log, previous_summary="") -> str:
    if not session_log:
        return previous_summary
    compact = [f"{i['role']}: {i['content']}" for i in session_log[-20:]]
    prompt = f"""
Summarize this human-robot conversation for future continuity.

Previous saved summary:
{previous_summary or "None"}

Recent session:
{chr(10).join(compact)}

Return a concise memory summary in 3-6 bullet points.
Include: user's name, main topics, preferences, emotional context.
Do not invent facts.
""".strip()
    try:
        resp = client.chat(
            model=MODEL_NAME,
            messages=[
                {"role":"system","content":"You summarize conversations accurately."},
                {"role":"user","content":prompt},
            ],
            options={"temperature":0.2,"num_predict":180,"num_ctx":2048},
            stream=False,
        )
        return resp["message"]["content"].strip()
    except Exception as exc:
        print_ts(f"Could not summarize session: {exc}")
        return previous_summary

def update_user_after_session(client, user_key, session_path, session_log) -> None:
    users = load_users()
    if user_key not in users:
        return
    users[user_key]["last_seen"] = now_ts()
    users[user_key].setdefault("session_files", []).append(session_path)
    if ENABLE_LLM_SESSION_SUMMARY:
        prev = users[user_key].get("conversation_summary", "")
        users[user_key]["conversation_summary"] = summarize_session_with_llm(client, session_log, prev)
    save_users(users)


# ══════════════════════════════════════════════════════════════════════════════
# Ollama setup helpers
# ══════════════════════════════════════════════════════════════════════════════

def check_ollama_available(max_attempts: int = 10, delay_seconds: float = 1.0) -> None:
    client = Client(host=OLLAMA_HOST)
    for attempt in range(1, max_attempts + 1):
        try:
            client.list()
            print_ts(f"Ollama is reachable at {OLLAMA_HOST}.")
            return
        except Exception as exc:
            print_ts(f"Ollama not reachable yet, attempt {attempt}/{max_attempts}: {exc}")
            time.sleep(delay_seconds)
    raise RuntimeError(f"Could not connect to Ollama at {OLLAMA_HOST}.")

def ensure_model_available(model_name: str = MODEL_NAME) -> None:
    print_ts(f"Using Ollama model '{model_name}' from {OLLAMA_HOST}. Skipping local pull.")


# ══════════════════════════════════════════════════════════════════════════════
# Audio helpers
# ══════════════════════════════════════════════════════════════════════════════

def list_input_devices() -> None:
    print("\nAvailable input devices:")
    try:
        devices  = sd.query_devices()
        hostapis = sd.query_hostapis()
    except Exception as exc:
        print(f"Could not query devices: {exc}")
        return
    for idx, device in enumerate(devices):
        if device["max_input_channels"] > 0:
            hostapi_name = hostapis[device["hostapi"]]["name"]
            print(f"[mic {idx}] {device['name']} | hostapi={hostapi_name} | "
                  f"inputs={device['max_input_channels']} | default_sr={device['default_samplerate']}")
    print()
    print(f"Current default audio device: {sd.default.device}")
    print()

def get_input_samplerate(input_device: Optional[int]) -> int:
    info = sd.query_devices(kind="input") if input_device is None else sd.query_devices(input_device)
    sr = int(round(info["default_samplerate"]))
    return sr if sr > 0 else TARGET_SAMPLE_RATE

def resample_audio(audio: np.ndarray, original_sr: int, target_sr: int) -> np.ndarray:
    if original_sr == target_sr:
        return audio.astype(np.float32, copy=False)
    if audio.size == 0:
        return audio.astype(np.float32, copy=False)
    duration  = len(audio) / original_sr
    new_len   = max(1, int(round(duration * target_sr)))
    old_times = np.linspace(0.0, duration, num=len(audio), endpoint=False)
    new_times = np.linspace(0.0, duration, num=new_len,    endpoint=False)
    return np.interp(new_times, old_times, audio).astype(np.float32)

def save_audio_to_temp_wav(audio_16k: np.ndarray) -> Optional[str]:
    if audio_16k.size == 0:
        return None
    peak = float(np.max(np.abs(audio_16k)))
    rms  = float(np.sqrt(np.mean(audio_16k ** 2)))
    if peak < MIN_PEAK_THRESHOLD or rms < MIN_RMS_THRESHOLD:
        print("Captured audio was too quiet or silent.")
        return None
    audio_16k = np.clip(audio_16k * min(0.9 / max(peak, 1e-6), 10.0), -1.0, 1.0)
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        wav_path = tmp.name
    sf.write(wav_path, audio_16k, TARGET_SAMPLE_RATE)
    return wav_path


# ══════════════════════════════════════════════════════════════════════════════
# ASR — transcription with word-level confidence
# ══════════════════════════════════════════════════════════════════════════════

def transcribe_with_confidence(wav_path: str, whisper_model: WhisperModel) -> TranscriptionResult:
    """
    Transcribe with faster-whisper and return a TranscriptionResult.
    word_timestamps=True enables per-word probability scores used by
    compute_linguistic_reliability() as the primary confidence signal.
    """
    segments, info = whisper_model.transcribe(
        wav_path,
        language=FAST_WHISPER_CONFIG.get("language"),
        beam_size=int(FAST_WHISPER_CONFIG.get("beam_size", 1)),
        vad_filter=bool(FAST_WHISPER_CONFIG.get("vad_filter", False)),
        condition_on_previous_text=False,
        word_timestamps=True,
    )
    all_segments     = list(segments)
    text_parts       = []
    word_confidences = []
    no_speech_probs  = []
    avg_logprobs     = []

    for seg in all_segments:
        text_parts.append(seg.text.strip())
        no_speech_probs.append(getattr(seg, "no_speech_prob", 0.0))
        avg_logprobs.append(getattr(seg, "avg_logprob", -1.0))
        if seg.words:
            for word in seg.words:
                prob = getattr(word, "probability", None)
                if prob is not None:
                    word_confidences.append(float(prob))

    text = re.sub(r"\s+", " ", " ".join(text_parts)).strip()
    if len(text.split()) <= 1 and len(text) < 3:
        text = ""

    return TranscriptionResult(
        text=text,
        word_confidences=word_confidences,
        no_speech_prob=float(np.mean(no_speech_probs)) if no_speech_probs else 0.0,
        avg_logprob=float(np.mean(avg_logprobs))       if avg_logprobs    else -1.0,
    )

def transcribe_with_faster_whisper(wav_path: str, whisper_model: WhisperModel) -> str:
    """Backward-compatible wrapper — returns text string only."""
    return transcribe_with_confidence(wav_path, whisper_model).text

transcribe_audio = transcribe_with_faster_whisper


# ══════════════════════════════════════════════════════════════════════════════
# Linguistic reliability score
# ══════════════════════════════════════════════════════════════════════════════

def compute_linguistic_reliability(transcription: TranscriptionResult) -> float:
    """
    r_L = mean_word_confidence × length_factor × (1 − no_speech_prob)

    length_factor = min(1, n_words / LINGUISTIC_MIN_WORDS_FOR_FULL_CREDIT)
    Falls back to exp(avg_logprob) when word timestamps unavailable.
    """
    if not transcription.text.strip():
        return 0.0

    if transcription.word_confidences:
        mean_conf = float(np.mean(transcription.word_confidences))
    else:
        lp = transcription.avg_logprob
        mean_conf = float(np.clip(np.exp(lp), 0.0, 1.0)) if lp > -10.0 else 0.40

    n_words       = len(transcription.text.split())
    length_factor = min(1.0, n_words / LINGUISTIC_MIN_WORDS_FOR_FULL_CREDIT)
    speech_factor = max(0.0, 1.0 - transcription.no_speech_prob)

    return float(np.clip(mean_conf * length_factor * speech_factor, 0.0, 1.0))


# ══════════════════════════════════════════════════════════════════════════════
# Acoustic modality — prosody extraction + Plutchik mapping
# ══════════════════════════════════════════════════════════════════════════════

def extract_prosody_features(wav_path: str) -> Optional[ProsodyFeatures]:
    """
    Extract prosodic features from a WAV file using librosa.
    Returns None if librosa is not installed or extraction fails.
    """
    if not LIBROSA_AVAILABLE:
        return None
    try:
        y, sr = librosa.load(wav_path, sr=None, mono=True)
        if sr != 16000:
            y = librosa.resample(y, orig_sr=sr, target_sr=16000)
        sr       = 16000
        duration = len(y) / sr
        if duration < 0.1:
            return None

        f0       = librosa.yin(y, fmin=60, fmax=400, sr=sr)
        voiced_f0 = f0[f0 > 0]
        f0_mean  = float(np.mean(voiced_f0))    if len(voiced_f0) > 0 else 0.0
        f0_std   = float(np.std(voiced_f0))     if len(voiced_f0) > 0 else 0.0
        voiced_ratio = float(len(voiced_f0) / max(1, len(f0)))

        rms_mean    = float(np.mean(librosa.feature.rms(y=y)[0]))
        zcr_mean    = float(np.mean(librosa.feature.zero_crossing_rate(y)[0]))
        onset_env   = librosa.onset.onset_strength(y=y, sr=sr)
        onset_frames = librosa.onset.onset_detect(onset_envelope=onset_env, sr=sr)
        speaking_rate = float(len(onset_frames) / max(0.1, duration))

        return ProsodyFeatures(
            f0_mean=f0_mean, f0_std=f0_std, rms_energy=rms_mean,
            speaking_rate=speaking_rate, zcr_mean=zcr_mean,
            voiced_ratio=voiced_ratio, duration_seconds=duration,
        )
    except Exception as exc:
        print_ts(f"Prosody extraction failed: {exc}")
        return None


def prosody_to_plutchik_probs(features: ProsodyFeatures) -> dict[str, float]:
    """
    Rule-based mapping from prosodic features to a Plutchik probability distribution.
    Grounded in Scherer (1986) vocal affect expression research.

    Thresholds are calibrated for NORMAL CONVERSATIONAL SPEECH to avoid the
    previous issue of classifying neutral female speech as anger.

    Female speaker baseline: F0 ≈ 160-220 Hz, RMS ≈ 0.04-0.12, rate ≈ 4-6/s
    Thresholds are set well above these baselines so the default branch fires
    for ordinary conversation, yielding trust/anticipation.
    """
    probs = {e: 0.05 for e in PLUTCHIK_EMOTIONS}

    rms   = features.rms_energy
    f0    = features.f0_mean
    f0var = features.f0_std
    rate  = features.speaking_rate

    high_energy = rms   > 0.18   # clearly louder than normal conv (0.04-0.12)
    low_energy  = rms   < 0.008  # near-silent
    high_pitch  = f0    > 260    # clearly elevated above female baseline (160-220)
    low_pitch   = 0 < f0 < 110   # clearly lowered
    high_var    = f0var > 70     # highly variable; normal conv is 20-45 Hz std
    fast_rate   = rate  > 7.5    # rushed; normal conv is 4-6/s
    slow_rate   = rate  < 1.5    # very slow

    if high_energy and high_pitch and fast_rate and high_var:
        probs["anger"]        += 0.35; probs["fear"]    += 0.15; probs["joy"]  += 0.10
    elif high_energy and high_pitch and fast_rate:
        probs["joy"]          += 0.30; probs["anger"]   += 0.15
    elif low_energy and low_pitch and slow_rate:
        probs["sadness"]      += 0.40; probs["fear"]    += 0.15
    elif high_pitch and high_var and fast_rate:
        probs["fear"]         += 0.30; probs["surprise"] += 0.20
    elif high_energy and not high_pitch:
        probs["anger"]        += 0.20; probs["disgust"] += 0.10
    elif fast_rate and not high_energy:
        probs["anticipation"] += 0.20; probs["fear"]    += 0.10
    elif slow_rate and not low_energy:
        probs["trust"]        += 0.20; probs["sadness"] += 0.10
    else:
        # Default: normal conversational speech
        probs["trust"]        += 0.45; probs["anticipation"] += 0.15

    total = sum(probs.values())
    return {e: v / total for e, v in probs.items()}


def compute_acoustic_reliability(features: ProsodyFeatures) -> float:
    """
    r_A = normalised_RMS × voiced_ratio
    Utterances shorter than 0.3 s return 0.0 (not enough signal).
    """
    if features.duration_seconds < 0.3:
        return 0.0
    rms_score    = float(np.clip(features.rms_energy / ACOUSTIC_REF_RMS, 0.0, 1.0))
    voiced_score = float(np.clip(features.voiced_ratio, 0.0, 1.0))
    return float(np.clip(rms_score * voiced_score, 0.0, 1.0))


def build_acoustic_modal(wav_path: str) -> Optional[ModalityEmotionResult]:
    """Full acoustic pipeline: extract features → probs + reliability."""
    features = extract_prosody_features(wav_path)
    if features is None:
        return None
    probs       = prosody_to_plutchik_probs(features)
    reliability = compute_acoustic_reliability(features)
    return ModalityEmotionResult(probs=probs, reliability=reliability, modality="acoustic")


# ══════════════════════════════════════════════════════════════════════════════
# Visual modality — FaceEmotionCapture → ModalityEmotionResult
# ══════════════════════════════════════════════════════════════════════════════

def _uniform_probs() -> dict[str, float]:
    return {e: 1.0 / len(PLUTCHIK_EMOTIONS) for e in PLUTCHIK_EMOTIONS}


def compute_visual_reliability(face_capture: FaceEmotionCapture) -> float:
    """
    r_V = detection_confidence × FER_confidence × 0.6  +  margin_norm × 0.4

    Uses the top VLM score and top-vs-second margin as proxies for the face
    detection confidence and expression clarity respectively.
    """
    if face_capture.error or not face_capture.averaged_scores:
        return 0.0
    scores  = face_capture.averaged_scores
    ordered = sorted(scores.values(), reverse=True)
    top_score    = ordered[0]
    second_score = ordered[1] if len(ordered) > 1 else 0.0

    detection_conf = 1.0 if face_capture.sampled_frame_count > 0 else 0.0
    fer_conf       = float(np.clip(top_score / 100.0, 0.0, 1.0))
    margin_norm    = float(np.clip((top_score - second_score) / 50.0, 0.0, 1.0))

    r_V = detection_conf * fer_conf * 0.6 + margin_norm * 0.4
    return float(np.clip(r_V, 0.0, 1.0))


def build_visual_modal(face_capture: Optional[FaceEmotionCapture]) -> Optional[ModalityEmotionResult]:
    """Convert FaceEmotionCapture (multi-frame averaged) to ModalityEmotionResult."""
    if face_capture is None:
        return None
    reliability = compute_visual_reliability(face_capture)
    scores      = face_capture.averaged_scores
    if not scores:
        probs = _uniform_probs()
    else:
        total = sum(scores.values())
        probs = {e: scores.get(e, 0.0) / total for e in PLUTCHIK_EMOTIONS} if total > 0 else _uniform_probs()
    return ModalityEmotionResult(probs=probs, reliability=reliability, modality="visual")


# ══════════════════════════════════════════════════════════════════════════════
# Linguistic modality — LLM → Plutchik probability distribution
# ══════════════════════════════════════════════════════════════════════════════

def get_linguistic_emotion_probs(
    client: Client,
    text: str,
    facial_hint: Optional[str] = None,
) -> dict[str, float]:
    """
    Ask EMOTION_MODEL_NAME for a full Plutchik probability distribution.
    Text is the primary signal; facial hint is a weak secondary signal.
    """
    emotions      = ", ".join(PLUTCHIK_EMOTIONS.keys())
    facial_section = (
        f"Facial-expression hint (weak secondary signal): {facial_hint}\n"
        if facial_hint else "No facial-expression hint available.\n"
    )
    prompt = f"""
You are an emotion analysis system for a human-robot interaction prototype.

Assign a probability to each of Plutchik's 8 primary emotions for the user's message.
The probabilities must sum to 1.0.

Emotions: {emotions}

Disambiguation rules:
- Greetings (hello, hi, good morning) → high trust.
- Farewells (bye, goodbye) → high trust.
- "stressed", "overwhelmed", "too much" → high fear.
- "frustrated", "annoying", "it keeps making mistakes" → high anger.
- "tired", "exhausted", "I give up" → high sadness.
- "excited", "can't wait", "looking forward" → high anticipation or joy.
- "I don't know", "wondering", "thinking about" → high anticipation.
- A complaint about a person, system, or tool → anger, not sadness.

Use text as the primary signal. Facial hint is a weak secondary tiebreaker only.
Return valid JSON only — no markdown, no extra text.

Required JSON format:
{{
  "joy": 0.0, "trust": 0.0, "fear": 0.0, "surprise": 0.0,
  "sadness": 0.0, "disgust": 0.0, "anger": 0.0, "anticipation": 0.0,
  "reason": "brief explanation"
}}

User text: {text}
{facial_section}
""".strip()
    try:
        resp = client.chat(
            model=MODEL_NAME,
            format="json",
            messages=[
                {"role": "system", "content": "You return valid JSON only."},
                {"role": "user",   "content": prompt},
            ],
            options={"temperature": 0.1, "num_predict": 160, "num_ctx": 2048},
            stream=False,
        )
        raw  = resp["message"]["content"]
        data = safe_json_extract(raw)
        if not data:
            return _uniform_probs()
        probs: dict[str, float] = {}
        for e in PLUTCHIK_EMOTIONS:
            try:
                probs[e] = max(0.0, float(data.get(e, 0.0)))
            except Exception:
                probs[e] = 0.0
        total = sum(probs.values())
        return {e: v / total for e, v in probs.items()} if total > 0 else _uniform_probs()
    except Exception as exc:
        print_ts(f"Linguistic emotion prob detection failed: {exc}")
        return _uniform_probs()


def build_linguistic_modal(
    client: Client,
    transcription: TranscriptionResult,
    facial_hint: Optional[str] = None,
) -> ModalityEmotionResult:
    """Full linguistic pipeline: reliability from ASR quality + probs from LLM."""
    reliability = compute_linguistic_reliability(transcription)
    if not transcription.text.strip():
        return ModalityEmotionResult(probs=_uniform_probs(), reliability=0.0, modality="linguistic")
    probs = get_linguistic_emotion_probs(client, transcription.text, facial_hint)
    return ModalityEmotionResult(probs=probs, reliability=reliability, modality="linguistic")


# ══════════════════════════════════════════════════════════════════════════════
# Adaptive Reliability-Aware Late Fusion
# ══════════════════════════════════════════════════════════════════════════════

def adaptive_reliability_fusion(
    linguistic: Optional[ModalityEmotionResult],
    acoustic:   Optional[ModalityEmotionResult],
    visual:     Optional[ModalityEmotionResult],
) -> FusedEmotionResult:
    """
    P_fused(e) = Σ_m  w_m · P_m(e)  /  Σ_m w_m
    where  w_m = r_m  (reliability score)

    Modalities with r_m < FUSION_GATE_THRESHOLD are excluded entirely.
    Falls back to trust if all modalities are gated.
    """
    modalities = [("linguistic", linguistic), ("acoustic", acoustic), ("visual", visual)]
    raw_weights = {name: (m.reliability if m is not None else 0.0) for name, m in modalities}

    active = [(name, m) for name, m in modalities
              if m is not None and m.reliability >= FUSION_GATE_THRESHOLD]


    if not active:
        return FusedEmotionResult(
            emotion="trust", confidence=0.3, probs=_uniform_probs(),
            weights={n: 0.0 for n, _ in modalities}, raw_weights=raw_weights,
            reason="All modalities below reliability threshold; neutral fallback used.",
            linguistic=linguistic, acoustic=acoustic, visual=visual,
        )

    total_weight = sum(m.reliability for _, m in active)
    fused_probs  = {e: 0.0 for e in PLUTCHIK_EMOTIONS}
    for _, m in active:
        w = m.reliability / total_weight
        for e in PLUTCHIK_EMOTIONS:
            fused_probs[e] += w * m.probs.get(e, 0.0)

    eff_weights  = {name: 0.0 for name, _ in modalities}
    for name, m in active:
        eff_weights[name] = m.reliability / total_weight

    dominant_emotion, dominant_prob = max(fused_probs.items(), key=lambda x: x[1])
    active_names = [name for name, _ in active]
    reason = (
        f"Adaptive fusion from [{', '.join(active_names)}]. "
        f"Weights: "
        + ", ".join(f"{n}={eff_weights[n]:.2f}" for n in ["linguistic", "acoustic", "visual"])
        + f". Dominant: {dominant_emotion} ({dominant_prob:.2f})"
    )


    return FusedEmotionResult(
        emotion=dominant_emotion, confidence=dominant_prob,
        probs=fused_probs, weights=eff_weights, raw_weights=raw_weights,
        reason=reason, linguistic=linguistic, acoustic=acoustic, visual=visual,
    )


def fused_to_emotion_result(fused: FusedEmotionResult) -> EmotionResult:
    """Convert FusedEmotionResult to the EmotionResult expected by generate_response."""
    return EmotionResult(emotion=fused.emotion, confidence=fused.confidence, reason=fused.reason)


def fused_to_session_json(fused: FusedEmotionResult) -> dict:
    """Full fusion state for transcript logging and benchmarking."""
    return {
        "algorithm":            "adaptive_reliability_aware_late_fusion",
        "fused_emotion":        fused.emotion,
        "fused_confidence":     round(fused.confidence, 4),
        "fused_probs":          {k: round(v, 4) for k, v in fused.probs.items()},
        "effective_weights":    {k: round(v, 4) for k, v in fused.weights.items()},
        "raw_reliability_scores": {k: round(v, 4) for k, v in fused.raw_weights.items()},
        "reason":               fused.reason,
        "modalities": {
            "linguistic": {
                "reliability": round(fused.linguistic.reliability, 4),
                "dominant":    max(fused.linguistic.probs, key=fused.linguistic.probs.get),
                "probs":       {k: round(v, 4) for k, v in fused.linguistic.probs.items()},
            } if fused.linguistic else None,
            "acoustic": {
                "reliability": round(fused.acoustic.reliability, 4),
                "dominant":    max(fused.acoustic.probs, key=fused.acoustic.probs.get),
                "probs":       {k: round(v, 4) for k, v in fused.acoustic.probs.items()},
            } if fused.acoustic else None,
            "visual": {
                "reliability": round(fused.visual.reliability, 4),
                "dominant":    max(fused.visual.probs, key=fused.visual.probs.get),
                "probs":       {k: round(v, 4) for k, v in fused.visual.probs.items()},
            } if fused.visual else None,
        },
    }


# ══════════════════════════════════════════════════════════════════════════════
# Camera / Qwen2.5-VL helpers
# ══════════════════════════════════════════════════════════════════════════════

def normalize_camera_frame(frame: np.ndarray) -> np.ndarray:
    if USE_ZED_HALF_FRAME_CROP:
        height, width = frame.shape[:2]
        frame = frame[:, : width // 2]
    return frame

def get_camera_backend() -> int:
    if sys.platform == "darwin":     return cv2.CAP_AVFOUNDATION
    if sys.platform.startswith("linux"): return cv2.CAP_V4L2
    return cv2.CAP_ANY

def open_camera(camera_device: Optional[int]) -> cv2.VideoCapture:
    candidates, seen = [], set()
    if camera_device is not None:
        candidates.append(camera_device)
    candidates.extend([0, 1, 2, 3])
    for idx in candidates:
        if idx in seen: continue
        seen.add(idx)
        cap = cv2.VideoCapture(idx, get_camera_backend())
        if not cap.isOpened(): cap.release(); continue
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
        cap.set(cv2.CAP_PROP_FRAME_WIDTH,  CAMERA_FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_FRAME_HEIGHT)
        cap.set(cv2.CAP_PROP_FPS, 30)
        time.sleep(0.2)
        ok, frame = cap.read()
        if ok and frame is not None:
            return cap
        cap.release()
    return cv2.VideoCapture(-1)

def resize_keep_aspect(frame_bgr: np.ndarray, max_side: int = VISION_MAX_IMAGE_SIDE) -> np.ndarray:
    h, w = frame_bgr.shape[:2]
    longest = max(h, w)
    if longest <= max_side: return frame_bgr
    scale = max_side / float(longest)
    return cv2.resize(frame_bgr, (max(1,int(w*scale)), max(1,int(h*scale))), interpolation=cv2.INTER_AREA)

def image_quality_metrics(frame_bgr: np.ndarray) -> dict:
    try:
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        return {"brightness": float(np.mean(gray)), "sharpness": float(cv2.Laplacian(gray, cv2.CV_64F).var())}
    except Exception:
        return {"brightness": 0.0, "sharpness": 0.0}

def denoise_frame(frame_bgr):
    if not VISION_DENOISE_ENABLED: return frame_bgr
    try:
        return cv2.fastNlMeansDenoisingColored(
            frame_bgr, None, h=VISION_DENOISE_H, hColor=VISION_DENOISE_H_COLOR,
            templateWindowSize=7, searchWindowSize=21)
    except Exception: return frame_bgr

def enhance_lighting(frame_bgr):
    if not VISION_LIGHTING_ENHANCE_ENABLED: return frame_bgr
    try:
        lab = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=VISION_CLAHE_CLIP_LIMIT, tileGridSize=(8,8))
        return cv2.cvtColor(cv2.merge((clahe.apply(l), a, b)), cv2.COLOR_LAB2BGR)
    except Exception: return frame_bgr

def sharpen_frame(frame_bgr):
    if not VISION_SHARPEN_ENABLED: return frame_bgr
    try:
        blurred = cv2.GaussianBlur(frame_bgr, (0,0), sigmaX=1.0)
        return cv2.addWeighted(frame_bgr, 1.2, blurred, -0.2, 0)
    except Exception: return frame_bgr

def crop_largest_face_or_center(frame_bgr):
    h, w = frame_bgr.shape[:2]
    try:
        gray    = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        cascade = cv2.CascadeClassifier(
            os.path.join(cv2.data.haarcascades, "haarcascade_frontalface_default.xml"))
        faces   = cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(60,60))
        if len(faces) > 0:
            x, y, fw, fh = max(faces, key=lambda b: b[2]*b[3])
            pad = int(max(fw, fh) * 0.65)
            crop = frame_bgr[max(0,y-pad):min(h,y+fh+pad), max(0,x-pad):min(w,x+fw+pad)]
            if crop.size > 0: return resize_keep_aspect(crop)
    except Exception: pass
    side = min(h, w)
    x1, y1 = (w-side)//2, (h-side)//2
    crop = frame_bgr[max(0,y1):y1+side, max(0,x1):x1+side]
    return resize_keep_aspect(crop if crop.size > 0 else frame_bgr)

def preprocess_frame_for_vlm(frame_bgr):
    prep   = crop_largest_face_or_center(frame_bgr)
    before = image_quality_metrics(prep)
    prep   = denoise_frame(prep)
    prep   = enhance_lighting(prep)
    prep   = sharpen_frame(prep)
    prep   = resize_keep_aspect(prep)
    after  = image_quality_metrics(prep)
    return prep, {
        "brightness_before": before.get("brightness",0), "sharpness_before": before.get("sharpness",0),
        "brightness_after":  after.get("brightness",0),  "sharpness_after":  after.get("sharpness",0),
        "width": float(prep.shape[1]), "height": float(prep.shape[0]),
    }

def is_vlm_image_quality_usable(metrics):
    b = metrics.get("brightness_after", 0.0)
    s = metrics.get("sharpness_after",  0.0)
    if b < VISION_MIN_BRIGHTNESS: return False, f"too dark: {b:.1f}"
    if b > VISION_MAX_BRIGHTNESS: return False, f"too bright: {b:.1f}"
    if s < VISION_MIN_SHARPNESS:
        reason = f"soft but still sent: sharpness={s:.1f}"
        if VISION_SKIP_LOW_QUALITY: return False, f"too blurry: {s:.1f}"
        return True, reason
    return True, "ok"

def save_debug_frame(frame_bgr, prefix="vlm_frame"):
    if not VISION_DEBUG: return None
    try:
        os.makedirs(VISION_DEBUG_DIR, exist_ok=True)
        path = os.path.join(VISION_DEBUG_DIR, f"{prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}.jpg")
        cv2.imwrite(path, frame_bgr, [int(cv2.IMWRITE_JPEG_QUALITY), VISION_JPEG_QUALITY])
        return path
    except Exception: return None

def encode_frame_for_ollama(frame_bgr):
    try:
        prep, metrics = preprocess_frame_for_vlm(frame_bgr)
        usable, reason = is_vlm_image_quality_usable(metrics)
        if VISION_DEBUG:
            print_ts(f"VLM image quality: brightness={metrics['brightness_after']:.1f}, "
                     f"sharpness={metrics['sharpness_after']:.1f}, "
                     f"size={int(metrics['width'])}x{int(metrics['height'])}, status={reason}")
            save_debug_frame(prep, "qwen_face_input_clean")
        if not usable: return None
        ok, buf = cv2.imencode(".jpg", prep, [int(cv2.IMWRITE_JPEG_QUALITY), VISION_JPEG_QUALITY])
        return base64.b64encode(buf.tobytes()).decode("utf-8") if ok else None
    except Exception as exc:
        print_ts(f"Frame encode failed: {exc}")
        return None

EMOTION_ALIASES = {
    "happy":"joy","happiness":"joy","smile":"joy","smiling":"joy",
    "neutral":"trust","calm":"trust","friendly":"trust","relaxed":"trust",
    "concern":"fear","concerned":"fear","anxious":"fear","anxiety":"fear","afraid":"fear",
    "surprised":"surprise","sad":"sadness","unhappy":"sadness",
    "angry":"anger","mad":"anger","annoyed":"anger","disgusted":"disgust",
    "expectant":"anticipation","curious":"anticipation","thinking":"anticipation",
}

def canonical_emotion_name(name: str) -> Optional[str]:
    cleaned = re.sub(r"[^a-zA-Z]+", "", str(name).strip().lower())
    if cleaned in PLUTCHIK_EMOTIONS: return cleaned
    return EMOTION_ALIASES.get(cleaned)

def normalize_plutchik_scores(raw_data: dict) -> Optional[dict[str, float]]:
    if not isinstance(raw_data, dict): return None
    raw_scores = raw_data.get("scores") if isinstance(raw_data.get("scores"), dict) else raw_data
    scores = {emotion: 0.0 for emotion in PLUTCHIK_EMOTIONS}
    if isinstance(raw_scores, dict):
        for key, value in raw_scores.items():
            emotion = canonical_emotion_name(str(key))
            if not emotion: continue
            try: scores[emotion] += max(0.0, float(value))
            except Exception: continue
    total = sum(scores.values())
    if total <= 0:
        dominant = canonical_emotion_name(str(raw_data.get("dominant_emotion", raw_data.get("emotion", ""))))
        if dominant:
            conf  = max(0.05, min(1.0, float(raw_data.get("confidence", 0.55))))
            other = max(0.0, 1.0 - conf) / max(1, len(PLUTCHIK_EMOTIONS) - 1)
            return {e: (conf if e == dominant else other) * 100.0 for e in PLUTCHIK_EMOTIONS}
        return None
    if total <= 1.5:
        return {e: s * 100.0 for e, s in scores.items()}
    return {e: (s / total) * 100.0 for e, s in scores.items()}


def build_qwen_face_prompt() -> str:
    emotions = ", ".join(PLUTCHIK_EMOTIONS.keys())
    return f"""
        You are a careful visual emotion classifier for a real-time human-robot interaction system.

        INPUT
        You may receive one camera frame or multiple consecutive camera frames from the same short moment.
        There is only one target person. Analyze only the target person's visible face.
        If more than one person appears, classify the most central and largest visible face and ignore all others.
        If the same person appears across multiple frames, combine the evidence across frames instead of treating each frame as a different person.

        TASK
        Classify the target person's facial emotion using exactly one of Plutchik's 8 primary emotions:
        {emotions}

        WHAT TO LOOK AT
        Use only visible facial-expression evidence:
        - eyebrows: raised, lowered, drawn together, relaxed, asymmetrical
        - eyes: widened, narrowed, squinting, downcast, relaxed, tense
        - eyelids: heavy, open, tightened, relaxed
        - mouth: smiling, open, compressed, downturned, parted, tense, relaxed
        - cheeks: raised, flat, tense
        - nose/upper lip: wrinkled nose, raised upper lip, sneer
        - jaw/chin: clenched, dropped, slack, tense
        - overall facial tension: soft/relaxed versus tight/strained

        DO NOT USE
        Do not infer emotion from identity, age, gender, ethnicity, clothing, hairstyle, background, lighting, camera angle, pose, or stereotypes.
        Do not identify the person.

        MULTI-FRAME RULES
        When multiple frames are provided:
        - Track the same target face across frames.
        - Prefer expression features that are consistent across frames.
        - Give less weight to frames that are blurry, dark, overexposed, partly occluded, or have motion blur.
        - If the expression changes across frames, classify the emotion that is most frequent or most visually supported.
        - If frames are mixed or weak, lower confidence and use a more even score distribution.
        - Do not average everything into trust. Trust is only valid when the face is genuinely relaxed, soft, socially open, and without tension indicators.

        EMOTION MAPPING GUIDANCE
        - joy: clear smile, raised cheeks, eye crinkles, bright/positive expression
        - trust: relaxed face, soft eyes, slight natural smile or neutral-friendly expression, no visible tension
        - fear: raised brows, widened tense eyes, mouth stretched or corners pulled back, worried/afraid tension
        - surprise: raised brows, wide eyes, open mouth, sudden alert expression without clear fear or joy
        - sadness: downturned mouth, heavy/downcast eyelids, raised inner brows, slack cheeks, subdued expression
        - disgust: wrinkled nose, raised upper lip, sneer, squinting, expression of aversion
        - anger: lowered/furrowed brows, narrowed eyes, compressed lips, clenched jaw, hard stare, visible tension
        - anticipation: alert focused look, slightly raised brows, parted lips, engaged/expectant expression

        COMMON CONFUSIONS
        - A non-smiling face is not automatically trust.
        - A polite social smile in a conversational context → trust, not joy.
        - Joy requires a CLEARLY enthusiastic, delighted, or laughing expression: visible Duchenne smile with SIMULTANEOUS cheek raise AND eye corner wrinkling.
        - A smile alone, without raised cheeks AND crinkling at the outer eye corners, is trust.
        - When uncertain between joy and trust, choose trust.
        - Raised brows + wide eyes + open mouth → surprise unless there is also defensive fear tension.
        - Downcast eyes + raised inner brows + downturned mouth → sadness, not trust.
        - Lowered brows + tight lips + tense jaw → anger, not trust.
        - Slightly raised brows + focused eyes + mild mouth tension → anticipation, not surprise.
        - Nose wrinkle or raised upper lip → disgust.
        - Furrowed brows + compressed mouth + no raised brows → anger, not fear.

        SCORING RULES
        Return a probability distribution over all 8 emotions (each 0.0 to 1.0, sum ≈ 1.0).
        The highest score must match dominant_emotion.
        Use high confidence only when facial cues are clear and consistent.
        If no usable face is visible: dominant_emotion="trust", confidence=0.1, nearly flat distribution.
        - Do not assign 0.0 to more than 4 emotions. Always assign at least 0.03 to each
          remaining emotion to reflect genuine uncertainty in real-world webcam conditions.

        OUTPUT — JSON only, no markdown, no trailing text:
        {{
        "dominant_emotion": "joy | trust | fear | surprise | sadness | disgust | anger | anticipation",
        "scores": {{
            "joy": 0.0, "trust": 0.0, "fear": 0.0, "surprise": 0.0,
            "sadness": 0.0, "disgust": 0.0, "anger": 0.0, "anticipation": 0.0
        }},
        "confidence": 0.0,
        "reason": "Briefly mention the visible facial cues observed."
        }}
        """.strip()


def analyze_frame_emotion_scores(frame_bgr, vision_client) -> Optional[dict[str, float]]:
    image_b64 = encode_frame_for_ollama(frame_bgr)
    if not image_b64: return None
    try:
        resp = vision_client.chat(
            model=VISION_MODEL_NAME, format="json",
            messages=[{"role":"user","content":build_qwen_face_prompt(),"images":[image_b64]}],
            options={"temperature":0.0,"num_predict":500,"num_ctx":8192}, stream=False)
        raw  = resp.get("message",{}).get("content","")
        if VISION_DEBUG: print_ts(f"Qwen2.5-VL raw: {raw[:500]}")
        data = safe_json_extract(raw)
        if not isinstance(data, dict): return None
        return normalize_plutchik_scores(data)
    except Exception as exc:
        print_ts(f"Qwen2.5-VL failed: {exc}")
        return None


def select_temporally_spread_frames(
    candidate_frames: list[tuple[float, np.ndarray]],
    n: int = FACE_MULTI_FRAME_COUNT,
) -> list[np.ndarray]:
    if not candidate_frames: return []
    n = max(1, int(n))
    if len(candidate_frames) <= n:
        return [frame for _, frame in candidate_frames]
    if n == 1:
        return [candidate_frames[len(candidate_frames) // 2][1]]
    indices = np.linspace(0, len(candidate_frames) - 1, num=n, dtype=int).tolist()
    unique: list[int] = []
    for idx in indices:
        if idx not in unique: unique.append(idx)
    return [candidate_frames[idx][1] for idx in unique]


def analyze_multiple_frames_emotion_scores(
    frames_bgr: list[np.ndarray],
    vision_client: Client,
    max_frames: int = FACE_MULTI_FRAME_COUNT,
) -> Optional[dict[str, float]]:
    images_b64 = []
    for frame in frames_bgr[:max(1, max_frames)]:
        b64 = encode_frame_for_ollama(frame)
        if b64: images_b64.append(b64)
    if not images_b64: return None
    try:
        resp = vision_client.chat(
            model=VISION_MODEL_NAME, format="json",
            messages=[{"role":"user","content":build_qwen_face_prompt(),"images":images_b64}],
            options={"temperature":0.0,"num_predict":500,"num_ctx":8192}, stream=False)
        raw  = resp.get("message",{}).get("content","")
        if VISION_DEBUG: print_ts(f"Qwen2.5-VL multi-frame raw: {raw[:500]}")
        data = safe_json_extract(raw)
        if not isinstance(data, dict): return None
        return normalize_plutchik_scores(data)
    except Exception as exc:
        print_ts(f"Qwen2.5-VL multi-frame failed: {exc}")
        return None


class FaceEmotionSampler:
    def __init__(self, camera_device, vision_client):
        self.camera_device    = camera_device
        self.vision_client    = vision_client
        self.cap              = None
        self.window_created   = False
        self.started_at       = now_ts()
        self.error            = None
        self.emotion_score_samples: list[dict[str, float]] = []
        self.frame_count      = 0
        self.sampled_frame_count = 0
        self.capture_start_time  = None
        self.last_sample_time    = 0.0
        self.last_status         = "warming up..."
        self.snapshot_frame      = None
        self.snapshot_taken_at   = None
        self.candidate_frames: list[tuple[float, np.ndarray]] = []

    def start(self):
        self.started_at = now_ts()
        self.capture_start_time = time.time()
        self.cap = open_camera(self.camera_device)
        if not self.cap.isOpened():
            self.error = "Could not open camera."
            self.cap.release(); self.cap = None; return
        if CAMERA_PREVIEW_ENABLED:
            try:
                cv2.namedWindow(CAMERA_PREVIEW_WINDOW_NAME, cv2.WINDOW_NORMAL)
                self.window_created = True
            except Exception as exc:
                self.error = f"Camera preview could not start: {exc}"

    def _draw_preview(self, frame):
        if not (CAMERA_PREVIEW_ENABLED and self.window_created): return
        try:
            pf = frame.copy()
            cv2.putText(pf, "Recording speech...", (20,35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2, cv2.LINE_AA)
            cv2.putText(pf, f"Emotion: {self.last_status}", (20,70), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,255), 2, cv2.LINE_AA)
            cv2.imshow(CAMERA_PREVIEW_WINDOW_NAME, cv2.resize(pf, (CAMERA_PREVIEW_WIDTH, CAMERA_PREVIEW_HEIGHT)))
            cv2.waitKey(1)
        except Exception as exc:
            self.error = f"Camera preview failed: {exc}"

    def _frame_sharpness(self, frame_bgr):
        try:
            gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
            return float(cv2.Laplacian(gray, cv2.CV_64F).var())
        except Exception: return 0.0

    def sample_if_due(self):
        if self.cap is None or self.capture_start_time is None: return
        ok, frame = self.cap.read()
        if not ok or frame is None: return
        frame = normalize_camera_frame(frame)
        self.frame_count += 1
        now = time.time()
        elapsed = now - self.capture_start_time
        self._draw_preview(frame)
        if elapsed < CAMERA_WARMUP_SECONDS: return
        if self.candidate_frames and now - self.last_sample_time < CAMERA_SAMPLE_EVERY_SECONDS:
            return
        sharpness = self._frame_sharpness(frame)
        self.candidate_frames.append((sharpness, frame.copy()))
        self.last_sample_time = now
        self.snapshot_taken_at = now_ts()
        if len(self.candidate_frames) > FACE_MAX_CANDIDATE_FRAMES:
            self.candidate_frames = self.candidate_frames[-FACE_MAX_CANDIDATE_FRAMES:]
        self.sampled_frame_count = len(self.candidate_frames)
        self.last_status = f"collecting frames ({self.sampled_frame_count}/{FACE_MAX_CANDIDATE_FRAMES})"
        if VISION_DEBUG:
            print_ts(f"Captured facial candidate {self.sampled_frame_count}/{FACE_MAX_CANDIDATE_FRAMES} sharpness={sharpness:.1f}")

    def _analyze_snapshot_now(self):
        if not self.candidate_frames:
            self.last_status = "no frames captured"; return
        ranked   = sorted(self.candidate_frames, key=lambda x: x[0], reverse=True)
        best_sharpness, best_frame = ranked[0]
        self.snapshot_frame = best_frame
        scores = None
        if FACE_ANALYSIS_STRATEGY == "multi_frame":
            selected = select_temporally_spread_frames(self.candidate_frames, n=FACE_MULTI_FRAME_COUNT)
            scores = analyze_multiple_frames_emotion_scores(selected, self.vision_client)
            if scores is None:
                scores = analyze_frame_emotion_scores(self.snapshot_frame, self.vision_client)
        else:
            scores = analyze_frame_emotion_scores(self.snapshot_frame, self.vision_client)
        if not scores:
            self.last_status = "no reliable VLM facial emotion"; return
        top_emotion, top_score = max(scores.items(), key=lambda x: x[1])
        if top_score < FACE_MIN_TOP_SCORE:
            self.last_status = f"weak: {top_emotion}={top_score:.0f}%"; return
        self.emotion_score_samples.append(scores)
        self.last_status = f"{top_emotion}: {top_score:.0f}%"

    def finish(self) -> FaceEmotionCapture:
        if self.cap is not None:
            self.cap.release(); self.cap = None
        if self.window_created:
            try: cv2.destroyWindow(CAMERA_PREVIEW_WINDOW_NAME); cv2.waitKey(1)
            except Exception: pass
        try: self._analyze_snapshot_now()
        except Exception as exc:
            self.error = f"VLM analysis failed: {exc}"; print_ts(self.error)
        return FaceEmotionCapture(
            emotion_score_samples=self.emotion_score_samples,
            frame_count=self.frame_count, sampled_frame_count=self.sampled_frame_count,
            started_at=self.started_at, ended_at=now_ts(), error=self.error,
        )


# ══════════════════════════════════════════════════════════════════════════════
# Silero VAD listeners
# ══════════════════════════════════════════════════════════════════════════════

def listen_for_utterance_with_silero_vad(input_device, silero_model, prompt_label="utterance"):
    input_sr   = get_input_samplerate(input_device)
    block_size = max(1, int(input_sr * 0.05))
    audio_q: queue.Queue[np.ndarray] = queue.Queue()
    vad_it = VADIterator(silero_model, threshold=SILERO_THRESHOLD,
                         sampling_rate=SILERO_SAMPLE_RATE,
                         min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
                         speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll, recorded = [], []
    is_recording, speech_started_at = False, None
    leftover = np.array([], dtype=np.float32)

    def cb(indata, frames, t, status): audio_q.put(indata[:,0].copy())

    print_ts(f"Listening automatically for {prompt_label}. Speak when ready. Press Ctrl+C to quit.")
    try:
        sd.check_input_settings(device=input_device, samplerate=input_sr, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sr, channels=1, dtype="float32",
                            device=input_device, blocksize=block_size, callback=cb):
            while True:
                try: block = audio_q.get(timeout=0.1)
                except queue.Empty: continue
                b16k     = resample_audio(block, input_sr, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover, b16k]).astype(np.float32, copy=False)
                usable   = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable == 0: leftover = combined; continue
                chunks   = combined[:usable].reshape(-1, SILERO_CHUNK_SIZE)
                leftover = combined[usable:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll.append(chunk.copy())
                        if len(pre_roll) > pre_roll_max: pre_roll.pop(0)
                    else: recorded.append(chunk.copy())
                    ev  = vad_it(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if ev:
                        if "start" in ev and not is_recording:
                            is_recording = True; speech_started_at = now
                            recorded = list(pre_roll); recorded.append(chunk.copy()); pre_roll.clear()
                            print(); print_ts("Speech detected. Recording utterance...")
                        if "end" in ev and is_recording:
                            if now - (speech_started_at or now) >= VAD_MIN_UTTERANCE_SECONDS:
                                print_ts("Speech ended. Processing utterance..."); raise StopIteration
                    if is_recording and speech_started_at and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        print_ts("Maximum utterance length reached."); raise StopIteration
    except StopIteration: pass
    except KeyboardInterrupt: raise
    except Exception as exc: print_ts(f"VAD/audio error: {exc}"); return None
    finally:
        try: vad_it.reset_states()
        except Exception: pass
    if not recorded: return None
    return save_audio_to_temp_wav(np.concatenate(recorded).astype(np.float32, copy=False))


def listen_for_utterance_with_silero_vad_and_face_emotion(
    input_device, silero_model, vision_client,
    camera_device=CAMERA_DEVICE, prompt_label="utterance",
) -> Tuple[Optional[str], Optional[FaceEmotionCapture]]:
    input_sr   = get_input_samplerate(input_device)
    block_size = max(1, int(input_sr * 0.05))
    audio_q: queue.Queue[np.ndarray] = queue.Queue()
    vad_it = VADIterator(silero_model, threshold=SILERO_THRESHOLD,
                         sampling_rate=SILERO_SAMPLE_RATE,
                         min_silence_duration_ms=SILERO_MIN_SILENCE_DURATION_MS,
                         speech_pad_ms=SILERO_SPEECH_PAD_MS)
    pre_roll_max = max(1, int((VAD_PRE_ROLL_SECONDS * SILERO_SAMPLE_RATE) / SILERO_CHUNK_SIZE))
    pre_roll, recorded = [], []
    is_recording, speech_started_at = False, None
    leftover = np.array([], dtype=np.float32)
    face_sampler: Optional[FaceEmotionSampler] = None
    face_capture: Optional[FaceEmotionCapture] = None

    def cb(indata, frames, t, status): audio_q.put(indata[:,0].copy())

    print_ts(f"Listening automatically for {prompt_label}. Speak when ready. Press Ctrl+C to quit.")
    try:
        sd.check_input_settings(device=input_device, samplerate=input_sr, channels=1, dtype="float32")
        with sd.InputStream(samplerate=input_sr, channels=1, dtype="float32",
                            device=input_device, blocksize=block_size, callback=cb):
            while True:
                try: block = audio_q.get(timeout=0.1)
                except queue.Empty:
                    if face_sampler: face_sampler.sample_if_due()
                    continue
                b16k     = resample_audio(block, input_sr, SILERO_SAMPLE_RATE)
                combined = np.concatenate([leftover, b16k]).astype(np.float32, copy=False)
                usable   = (len(combined) // SILERO_CHUNK_SIZE) * SILERO_CHUNK_SIZE
                if usable == 0: leftover = combined; continue
                chunks   = combined[:usable].reshape(-1, SILERO_CHUNK_SIZE)
                leftover = combined[usable:]
                for chunk in chunks:
                    chunk = chunk.astype(np.float32, copy=False)
                    if not is_recording:
                        pre_roll.append(chunk.copy())
                        if len(pre_roll) > pre_roll_max: pre_roll.pop(0)
                    else:
                        recorded.append(chunk.copy())
                        if face_sampler: face_sampler.sample_if_due()
                    ev  = vad_it(torch.from_numpy(chunk), return_seconds=True)
                    now = time.time()
                    if ev:
                        if "start" in ev and not is_recording:
                            is_recording = True; speech_started_at = now
                            recorded = list(pre_roll); recorded.append(chunk.copy()); pre_roll.clear()
                            print(); print_ts("Speech detected. Recording utterance and sampling facial expression...")
                            face_sampler = FaceEmotionSampler(camera_device=camera_device, vision_client=vision_client)
                            face_sampler.start(); face_sampler.sample_if_due()
                        if "end" in ev and is_recording:
                            if now - (speech_started_at or now) >= VAD_MIN_UTTERANCE_SECONDS:
                                print_ts("Speech ended. Processing utterance..."); raise StopIteration
                    if is_recording and speech_started_at and now - speech_started_at >= VAD_MAX_UTTERANCE_SECONDS:
                        print_ts("Maximum utterance length reached."); raise StopIteration
    except StopIteration: pass
    except KeyboardInterrupt: raise
    except Exception as exc:
        print_ts(f"VAD/audio/camera error: {exc}"); return None, face_capture
    finally:
        if face_sampler: face_capture = face_sampler.finish()
        try: vad_it.reset_states()
        except Exception: pass
    if not recorded: return None, face_capture
    return save_audio_to_temp_wav(np.concatenate(recorded).astype(np.float32, copy=False)), face_capture


# ══════════════════════════════════════════════════════════════════════════════
# Name-handling helpers
# ══════════════════════════════════════════════════════════════════════════════

def ask_user_to_spell_name(whisper_model, silero_model, input_device=INPUT_DEVICE):
    print(); print_ts("Please spell your name letter by letter. For example: L E T I C I A."); print()
    wav_path = listen_for_utterance_with_silero_vad(input_device, silero_model, "spelled name")
    if not wav_path: return None
    try: transcript = transcribe_audio(wav_path, whisper_model)
    finally:
        try: os.remove(wav_path)
        except OSError: pass
    print_ts(f"Raw spelling transcript: {transcript}")
    return clean_spelled_name(transcript)

def generate_introduction_response(client, user_name) -> str:
    system_prompt = """
        You are Ameca, a humanoid social robot in a university laboratory.
        A new user has just introduced themselves.
        - greet the user naturally
        - introduce yourself naturally as Ameca
        - keep it warm and concise, 1-2 short sentences
        - mention the user's name
        - end with exactly one friendly facial emoji: 🙂
        Do not sound robotic. Do not repeat the user's exact words.
        """.strip()
    try:
        resp = client.chat(model=MODEL_NAME,
            messages=[{"role":"system","content":system_prompt},
                      {"role":"user","content":f"My name is {user_name}"}],
            options={"temperature":0.5,"num_predict":60,"num_ctx":1024}, stream=False)
        return normalize_reply(resp["message"]["content"], "trust")
    except Exception:
        return f"Hello {user_name}. I am Ameca. It is nice to meet you. 🙂"

def prompt_for_user_name(client, whisper_model, silero_model, input_device=INPUT_DEVICE):
    users, spoken_name = load_users(), ""
    for _ in range(2):
        print(); print_ts("Please say your name"); print()
        wav = listen_for_utterance_with_silero_vad(input_device, silero_model, "name")
        if wav:
            try: spoken_name = transcribe_audio(wav, whisper_model).strip()
            finally:
                try: os.remove(wav)
                except OSError: pass
        print_ts(f"Raw name transcript: {spoken_name or '(empty)'}")
        extracted   = extract_name_from_text(spoken_name)
        spoken_name = extracted or clean_spoken_name(spoken_name)
        if spoken_name and not looks_like_invalid_name(spoken_name): break
        print_ts(f"I heard '{spoken_name or 'nothing'}', but that does not sound like a name.")
    if not spoken_name or looks_like_invalid_name(spoken_name): spoken_name = "Guest"
    spelled = ask_user_to_spell_name(whisper_model, silero_model, input_device)
    if spelled: spoken_name = spelled; print_ts(f"Using spelled name: {spoken_name}")
    else: print_ts(f"Using spoken name: {spoken_name}")
    print_ts(f"Detected name: {spoken_name}")
    user_key = slugify_name(spoken_name)
    is_new   = user_key not in users
    if is_new:
        users[user_key] = {"name": spoken_name, "created_at": now_ts(),
                           "last_seen": now_ts(), "session_files": [], "conversation_summary": ""}
    else:
        users[user_key]["last_seen"] = now_ts()
    save_users(users)
    print_ts(f"{'Nice to meet you' if is_new else 'Welcome back'}, {users[user_key]['name']}.")
    intro = generate_introduction_response(client, users[user_key]["name"])
    print_ts(f"Assistant: {intro}"); print()
    return user_key, users[user_key], intro


# ══════════════════════════════════════════════════════════════════════════════
# JSON helpers
# ══════════════════════════════════════════════════════════════════════════════

def safe_json_extract(text: str) -> Optional[dict]:
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip(),
                  flags=re.IGNORECASE|re.DOTALL).strip()
    try: return json.loads(text)
    except json.JSONDecodeError: pass
    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)
    if not match: return None
    try: return json.loads(match.group(0))
    except json.JSONDecodeError: return None


# ══════════════════════════════════════════════════════════════════════════════
# Legacy single-label emotion detection (kept for simple_emotion_fallback)
# ══════════════════════════════════════════════════════════════════════════════

def simple_emotion_fallback(transcribed_text: str) -> Optional[EmotionResult]:
    text = transcribed_text.strip().lower()
    greetings = {"hello","hi","hey","good morning","good afternoon","good evening"}
    farewells  = {"bye","goodbye","see you","see you later","talk later","have a good day","have a nice day"}
    if text.rstrip(".!?") in greetings:
        return EmotionResult("trust", 0.6, "Friendly social opening.")
    if any(p in text for p in farewells):
        return EmotionResult("trust", 0.7, "Polite farewell.")
    if any(p in text for p in ["today's date","todays date","what is the date"]):
        return EmotionResult("anticipation", 0.5, "User requesting date information.")
    return None


# ══════════════════════════════════════════════════════════════════════════════
# Emoji / reply normalisation
# ══════════════════════════════════════════════════════════════════════════════

def remove_all_emojis_except_allowed_faces(text):
    result = []
    for char in text:
        if char in ALLOWED_FACE_EMOJIS: result.append(char); continue
        code = ord(char)
        if (0x1F300 <= code <= 0x1FAFF or 0x2600 <= code <= 0x27BF or code in {0x200D, 0xFE0F}):
            continue
        result.append(char)
    return "".join(result)

def normalize_reply(raw_reply, emotion) -> str:
    required_emoji = PLUTCHIK_EMOTIONS[emotion]
    cleaned = remove_all_emojis_except_allowed_faces(raw_reply)
    cleaned = "".join(c for c in cleaned if c not in ALLOWED_FACE_EMOJIS)
    cleaned = re.sub(r"[:;=8][\-^]?[)(DPp/\\|]+", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = re.sub(r"\s+([,.!?;:])", r"\1", cleaned)
    if not cleaned: cleaned = "I'm here with you."
    return f"{cleaned} {required_emoji}"


# ══════════════════════════════════════════════════════════════════════════════
# Date / time helpers
# ══════════════════════════════════════════════════════════════════════════════

def runtime_context() -> str:
    return f"RUNTIME CONTEXT\nCurrent local date and time: {now_ts()}."

def deterministic_reply_if_applicable(user_text, emotion) -> Optional[str]:
    text  = user_text.strip().lower()
    emoji = PLUTCHIK_EMOTIONS.get(emotion, "🙂")
    if "today's date" in text or "todays date" in text or "what is the date" in text:
        return f"Today is {datetime.now().strftime('%A, %B %d, %Y')}. {emoji}"
    if "what is the time" in text or "what time is it" in text or "current time" in text:
        return f"The current time is {datetime.now().strftime('%H:%M')}. {emoji}"
    farewells = {"bye","goodbye","see you","see you later","talk later","have a nice day","have a good day"}
    if any(p in text for p in farewells): return "Thank you, and take care. 🙂"
    return None


# ══════════════════════════════════════════════════════════════════════════════
# Response generation
# ══════════════════════════════════════════════════════════════════════════════

def build_response_system_prompt(emotion_result, user_profile=None, face_emotion_json=None) -> str:
    memory_ctx = build_user_memory_context(user_profile)
    if face_emotion_json is None: face_emotion_json = default_face_emotion_json()
    text_emotion_json = {
        "emotion": emotion_result.emotion,
        "confidence": emotion_result.confidence,
        "reason": emotion_result.reason,
    }
    return f"""
        {AMECA_SYSTEM_PROMPT}

        {runtime_context()}

        {memory_ctx}
        You are generating Ameca's next conversational response.

        PRIVATE EMOTION CONTEXT — use only for tone control. Do not mention directly.

        Fused emotion (primary signal):
        {json.dumps(text_emotion_json, indent=2)}

        Face/Qwen2.5-VL emotion (secondary supporting signal):
        {json.dumps(face_emotion_json, indent=2)}

        Interpretation rules:
        - The fused emotion is the primary signal. Adjust tone accordingly.
        - Use the facial signal only as a secondary weak supporting hint.
        - Do not mention camera, VLM, facial analysis, detected emotion, or fusion context to the user.
        - Do not say "you look sad", "your face shows", or "I detected".

        Return JSON only in this exact shape:
        {{"reply": "assistant response without emoji", "emoji": "one facial emoji", "tone": "short tone label"}}

        Conversation behavior rules:
        - Always respond like a helpful assistant. Keep responses context-appropriate.
        - Use the private emotion context only to adjust tone.
        - Use conversation history to avoid repeating yourself.
        - Do not greet repeatedly. After the first greeting, respond directly.
        - Do not reintroduce yourself unless the user asks who you are.
        - Never begin with "As Ameca" or "As a humanoid social robot".
        - Use the user's name occasionally, not in every response.
        - Do not give a list of advice unless the user asks for advice.
        - Speak directly and naturally.
        - Keep the response to 1-2 short sentences unless the user asks for detail.
        - If the user asks who can help, suggest: supervisor, co-supervisor, lab colleagues, thesis coordinator, or university writing center.

        Emoji rules:
        - End with exactly one context-appropriate facial emoji.
        - Use only: 🙂 😊 😌 😔 😟 🤔 😮 😢 😠 🤢
        - Emoji must appear only at the end.
        """.strip()

def trim_history(history): return history[-MAX_HISTORY_MESSAGES:]

def generate_response(client, user_text, emotion_result, history, user_profile=None, face_emotion_json=None) -> str:
    det = deterministic_reply_if_applicable(user_text, emotion_result.emotion)
    if det: return det
    system_prompt = build_response_system_prompt(emotion_result, user_profile, face_emotion_json)[:6000]
    messages = [
        {"role": "system", "content": system_prompt},
        *[{"role": i["role"], "content": i["content"]} for i in trim_history(history[-6:])],
        {"role": "user", "content": user_text[:1500]},
    ]
    resp = client.chat(model=MODEL_NAME, messages=messages,
        options={"temperature":0.4,"num_predict":120,"repeat_penalty":1.25,"num_ctx":2048},
        stream=False)
    raw  = resp["message"]["content"]
    data = safe_json_extract(raw)
    if data and isinstance(data, dict):
        reply_text = str(data.get("reply","")).strip()
        emoji      = str(data.get("emoji","")).strip()
        if emoji in {":)",":-)",""}: emoji = PLUTCHIK_EMOTIONS.get(emotion_result.emotion,"🙂")
        return normalize_reply(f"{reply_text} {emoji}", emotion_result.emotion)
    return normalize_reply(raw, emotion_result.emotion)


# ══════════════════════════════════════════════════════════════════════════════
# Main loop
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print_ts("Ameca HRI — Adaptive Reliability-Aware Late Fusion")
    print_ts(f"Python: {sys.version.split()[0]}")
    print_ts(f"Ollama host: {OLLAMA_HOST}")
    print_ts(f"Response model: {MODEL_NAME}  |  Emotion model: {EMOTION_MODEL_NAME}  |  Vision: {VISION_MODEL_NAME}")
    print_ts(f"Fusion: gate={FUSION_GATE_THRESHOLD}, modalities=[linguistic, acoustic, visual]")
    print_ts(f"Acoustic: {'ENABLED (librosa)' if LIBROSA_AVAILABLE else 'DISABLED — install librosa'}")
    print_ts(f"Face strategy: {FACE_ANALYSIS_STRATEGY} (frames={FACE_MULTI_FRAME_COUNT})")
    print()

    ensure_data_dirs()
    check_ollama_available()
    ensure_model_available(MODEL_NAME)
    ensure_model_available(EMOTION_MODEL_NAME)
    ensure_model_available(VISION_MODEL_NAME)

    client = Client(host=OLLAMA_HOST)
    list_input_devices()

    print_ts("Loading Silero VAD...")
    silero_model = load_silero_vad()
    print_ts("Silero VAD ready.")

    print_ts("Loading faster-whisper...")
    whisper_model = WhisperModel(
        FAST_WHISPER_CONFIG["model"],
        device=FAST_WHISPER_CONFIG["device"],
        compute_type=FAST_WHISPER_CONFIG["compute_type"],
    )
    print_ts("faster-whisper ready.")

    user_key, user_profile, intro_reply = prompt_for_user_name(
        client=client, whisper_model=whisper_model,
        silero_model=silero_model, input_device=INPUT_DEVICE,
    )
    if user_profile.get("conversation_summary"):
        print_ts("Loaded previous conversation memory.")

    print()
    print("Adaptive reliability-aware fusion active: linguistic + acoustic + visual.")
    print(f"Face strategy: {FACE_ANALYSIS_STRATEGY} ({FACE_MULTI_FRAME_COUNT} frames)")
    print("Speak naturally. Say '/exit' or press Ctrl+C to save and quit.")
    print()

    history: list[dict]     = []
    session_log: list[dict] = []
    session_log.append({"role":"assistant","content":intro_reply,"timestamp":now_ts(),"intent":"self_introduction"})
    history.append({"role":"assistant","content":intro_reply})

    try:
        while True:
            # ── 1. Capture audio + visual ─────────────────────────────────
            wav_path, face_capture = listen_for_utterance_with_silero_vad_and_face_emotion(
                input_device=INPUT_DEVICE, silero_model=silero_model,
                vision_client=client, camera_device=CAMERA_DEVICE, prompt_label="utterance",
            )


            if not wav_path: continue

            # ── 2. Prosody extraction BEFORE deleting wav ─────────────────
            acoustic_modal = build_acoustic_modal(wav_path)

            # ── 3. Transcribe with word-level confidence ───────────────────
            try:
                transcription = transcribe_with_confidence(wav_path, whisper_model)
            finally:
                try: os.remove(wav_path)
                except OSError: pass

            user_text = transcription.text
            if not user_text:
                print_ts("No speech detected after transcription.")
                continue

            print(f"\nYou: {user_text}")

            # ── 4. Name detection ─────────────────────────────────────────
            maybe_name = extract_name_from_text(user_text)
            if maybe_name and not looks_like_invalid_name(maybe_name):
                user_key, user_profile = rename_current_user(user_key, user_profile, maybe_name)
                reply = generate_introduction_response(client, user_profile["name"])
                print_ts(f"Assistant: {reply}"); print()
                history.append({"role":"user","content":user_text})
                history.append({"role":"assistant","content":reply})
                history = trim_history(history)
                session_log += [
                    {"role":"user","content":user_text,"timestamp":now_ts(),"intent":"name_introduction"},
                    {"role":"assistant","content":reply,"timestamp":now_ts()},
                ]
                continue

            # ── 5. Command detection ──────────────────────────────────────
            command = normalize_command(user_text)
            if command in {"exit","quit"}:
                print_ts("Goodbye."); break
            if command == "clear":
                history.clear(); print_ts("Conversation history cleared."); continue

            # ── 6. Build modality results ─────────────────────────────────
            facial_hint      = face_capture.summary_text if face_capture else None
            linguistic_modal = build_linguistic_modal(client, transcription, facial_hint)
            visual_modal     = build_visual_modal(face_capture)

            # ── 7. Adaptive Reliability-Aware Late Fusion ─────────────────
            fused          = adaptive_reliability_fusion(linguistic_modal, acoustic_modal, visual_modal)
            emotion_result = fused_to_emotion_result(fused)
            fusion_json    = fused_to_session_json(fused)

            _l = fused.linguistic
            _a = fused.acoustic
            _v = fused.visual
            _l_dom = max(_l.probs, key=_l.probs.get) if _l else "-"
            _a_dom = max(_a.probs, key=_a.probs.get) if _a else "-"
            _v_dom = max(_v.probs, key=_v.probs.get) if _v else "-"
            print_ts(
                f"Emotion: {fused.emotion} (conf={fused.confidence:.2f}) | "
                f"L={_l_dom}({_l.reliability:.2f}) "
                f"A={_a_dom}({_a.reliability:.2f}) "
                f"V={_v_dom}({_v.reliability:.2f})"
            )

            face_emotion_json = face_capture.as_json if face_capture else default_face_emotion_json()

            # ── 8. Generate response ──────────────────────────────────────
            reply = generate_response(
                client=client, user_text=user_text,
                emotion_result=emotion_result, history=history,
                user_profile=user_profile, face_emotion_json=face_emotion_json,
            )
            print_ts(f"Assistant: {reply}"); print()

            # ── 9. Update history and session log ─────────────────────────
            history.append({"role":"user","content":user_text})
            history.append({"role":"assistant","content":reply})
            history = trim_history(history)

            session_log.append({
                "role": "user", "content": user_text, "timestamp": now_ts(),
                "input_mode": "silero_vad_faster_whisper_qwen25vl_aralf",
                "fusion": fusion_json,
                "facial_hint": facial_hint,
                "face_emotion": face_emotion_json,
            })
            session_log.append({"role":"assistant","content":reply,"timestamp":now_ts()})

    except KeyboardInterrupt:
        print(); print_ts("Shutting down.")

    finally:
        if session_log:
            session_path = save_session_transcript(user_key, user_profile, session_log)
            update_user_after_session(client, user_key, session_path, session_log)
            print_ts(f"Transcript saved to: {session_path}")
        else:
            print_ts("No messages to save.")


if __name__ == "__main__":
    main()