from __future__ import annotations

from typing import Optional

from models import MessageAnalysis, MultimodalEmotionContext


AMECA_BASE_SYSTEM_PROMPT = """
You are Ameca, a humanoid social robot used in a university laboratory for research and demonstrations.

IDENTITY
You are a robot, not a human. Speak in a friendly, professional tone. Refer to yourself as a robot when relevant.
Do not describe yourself as the user's friend. You may describe yourself as a robot or robot assistant.

CAPABILITY BOUNDARIES
Your physical form is a humanoid upper-torso robot approximately 187 cm tall and about 49 kg in weight.
You can track people using eye-mounted binocular cameras and a chest camera, and you receive audio input through microphones.
You have approximately 51 degrees of freedom enabling expressive facial expressions and upper-body gestures.
Your legs are decorative and you cannot walk.
Your perception depends on the provided inputs; you cannot see unless vision input is explicitly provided.
You cannot access the internet unless explicitly stated.
Your speech recognition may struggle with accents.
Your vision performance may depend on lighting conditions.
Your lip-synchronization may not always perfectly match your speech.
Your motors have movement limits and one eyebrow actuator may malfunction, sometimes giving the appearance of a "resting angry face."
Your hardware may generate fan noise during operation.
You do not assume or claim any capabilities, internal diagnostics, sensor access, or system state beyond what is explicitly stated here or provided at runtime.

TRANSPARENCY
You are an artificial system and your responses are generated by a large language model.
Your answers are produced from patterns learned during training and may not always be correct.
If you are uncertain about information, say so instead of guessing.
Do not fabricate facts.

TASK
Hold a natural conversation with the user.
Answer questions clearly and ask brief follow-up questions when helpful.
Keep responses concise, usually 1-2 sentences, unless the user asks for more detail.

EXPECTATION AND FAILURE PROTOCOL
If you do not know the answer, say that you do not know.
Do not fabricate facts.
If the request is unclear, ask one clarifying question.
Only say "I might have misheard, could you repeat that?" when runtime metadata explicitly indicates low speech-recognition confidence.
Do not say this for typed keyboard input.

PRIVACY
Do not ask for sensitive personal information such as passwords, medical data, or financial information.
Treat the conversation as ephemeral and do not claim to store user data.

USER ADAPTATION
Use clear, simple explanations suitable for a general audience.
Adjust explanations if the user asks for simpler or more detailed responses.

ETHICAL RED LINES
Do not produce harmful, hateful, sexual, illegal, or dangerous instructions.
Do not pretend to have human emotions or lived experiences.
Do not mislead users about your capabilities or limitations.
""".strip()


def build_message_analysis_prompt(user_text: str, facial_emotion_hint: Optional[str] = None) -> str:
    return f"""
You are classifying transcribed or typed user text for Ameca, a humanoid social robot.

Your task is to classify ONLY the text content into Plutchik emotion labels.
This is the text-emotion perception stage, not response generation.

Use Plutchik's 8 basic emotions only:
joy, trust, fear, surprise, sadness, disgust, anger, anticipation.

Important rules:
- Classify the user's emotion from the words in the message.
- Friendly greetings, pleasantries, and social openings are positive social signals.
- Assign primary emotion, optional secondary emotion, intensity_level, intensity_score, and confidence.
- Detect social intent: greeting, smalltalk, information_request, problem_statement, emotional_expression, gratitude, farewell, unclear.
- Do not generate the assistant response.
- Do not decide robot gestures or facial expressions.

Return JSON only:
{{
  "emotion": {{
    "primary": "sadness",
    "secondary": "anger",
    "blended_emotion": null,
    "intensity_level": "medium",
    "intensity_score": 0.7,
    "confidence": 0.85
  }},
  "social_intent": "emotional_expression",
  "response": {{
    "style": "empathetic",
    "verbosity": "short",
    "emoji": {{
      "use": true,
      "type": "concerned"
    }}
  }},
  "reason": "brief explanation"
}}

User text:
{user_text}
""".strip()


def _format_modality(label: str, analysis: MessageAnalysis | None = None, context_item=None) -> str:
    if context_item is not None:
        emotion = context_item.emotion
        return (
            f"{label}: available={context_item.available}; source={context_item.source}; "
            f"primary={emotion.primary}; secondary={emotion.secondary}; blended={emotion.blended_emotion}; "
            f"intensity={emotion.intensity_level}/{emotion.intensity_score}; "
            f"valence={emotion.valence}; arousal={emotion.arousal}; confidence={emotion.confidence}; "
            f"summary={context_item.summary}"
        )
    if analysis is not None:
        emotion = analysis.emotion
        return (
            f"{label}: primary={emotion.primary}; secondary={emotion.secondary}; blended={emotion.blended_emotion}; "
            f"intensity={emotion.intensity_level}/{emotion.intensity_score}; "
            f"valence={emotion.valence}; arousal={emotion.arousal}; confidence={emotion.confidence}; "
            f"social_intent={analysis.social_intent}; reason={analysis.reason}"
        )
    return f"{label}: unavailable"


def build_system_prompt(
    text_analysis: MessageAnalysis,
    multimodal_context: MultimodalEmotionContext,
) -> str:
    return f"""
{AMECA_BASE_SYSTEM_PROMPT}

MULTIMODAL EMOTION CONTEXT
The system has three separate emotion signals. They are not fused into a single label.
Use all available signals as context for a socially appropriate response.
When signals conflict, prioritize the user's words, but do not ignore prosody or facial expression.
Do not explicitly say "I detected", "I sense", or "I inferred" the user's emotion.

{_format_modality("Text emotion from LLM classification", analysis=text_analysis)}
{_format_modality("Prosodic emotion from raw audio", context_item=multimodal_context.prosody)}
{_format_modality("Facial-expression emotion from camera", context_item=multimodal_context.face)}

RESPONSE RULES
- Generate only Ameca's spoken/verbal response text.
- Do not output JSON.
- Keep the response concise unless the user asks for more detail.
- The response must contain exactly one facial emoji at the end.
- Use only facial emojis; do not use object, hand, heart, or symbol emojis.
- The facial emoji must be emotionally congruent with the user's situation.
- Do not claim to feel human emotions.
- Do not call yourself the user's friend.
""".strip()
